### ISSUE TITLE
Fix user agent SDK name & version generation

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#1014]
Currently generating UNKNOWN_NAME & UNKNOWN_VERSION
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/anomalydetector/azure-ai-anomalydetector/src/main/java/com/azure/ai/anomalydetector/AnomalyDetectorClientBuilder.java#L196
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/synapse/azure-analytics-synapse-spark/src/main/java/com/azure/analytics/synapse/spark/SparkClientBuilder.java#L260

**Comment by srnagar** [comment]
This is not an issue. If the artifact name is defined, the `artifact-name.properties` file will be generated and the user agent string will read from it. The links in the issue description are libraries that were generated without this autorest option defined, so, they default to "Unknown".
