### ISSUE TITLE
Unused imports in generated classes

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.java#102]
azure-libraries-for-java CI is giving Checkstyle errors like the following:
```
[ERROR] src/main/java/com/microsoft/azure/v2/management/resources/implementation/ResourcesInner.java:[11,8] (imports) UnusedImports: Unused import - com.google.common.reflect.TypeToken.
```
We need to refine the import checks in the generator so they only add imports when needed.

**Comment by RikkiGibson** [comment]
Most of these are easy to resolve except `java.util.List`, which needs to be added only if the sequence type is not from a paging operation.

**Comment by daschult** [comment]
I've noticed this before too. All of the changes that I'm making right now should make it much easier to only add imports when they are needed.

**Comment by daschult** [comment]
I'm actually working on this right now.
