### ISSUE TITLE
Only Apply JsonFlatten when x-ms-flatten is Used

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/autorest.java#1024]
Only annotate generated classes or interfaces with `@JsonFlatten` when `x-ms-flatten` is used. Currently, flattening is also applied is the discriminator for inheritance contains a `.` ([code](https://github.com/Azure/autorest.java/blob/v4/javagen/src/main/java/com/azure/autorest/mapper/ModelMapper.java#L164)). A common discriminator is `@odata.type` which results in many classes being marked for flattening when it doesn't apply.

**Comment by weidongxu-microsoft** [comment]
Removing it breaks this test https://github.com/Azure/autorest.java/blob/v4/vanilla-tests/swagger/discriminator-flattening.json

**Comment by weidongxu-microsoft** [comment]
Maybe one can add a flag to avoid `@JsonFlatten` if one knows the situation will never happen to that particular client.

**Comment by alzimmermsft** [comment]
Closing as there have been changes to how `JsonFlatten` is applied which prevents it from being added if a `.` exists in the serialized name and it isn't actually flattened.
