### ISSUE TITLE
Pagination support in protocol methods

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#1034]
Generation pagination methods as described in https://gist.github.com/jianghaolu/77fea6fa1e5bda4b5746ab2235e1bfbe#pageable-operations

Test with this API: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/translation/azure-ai-documenttranslator/src/main/java/com/azure/ai/documenttranslator/BatchDocumentTranslationRestClient.java#L599

**Comment by srnagar** [comment]
@qwordy has merged the PR for this work.
