### ISSUE TITLE
Support partial updates to Java file to replace/update generated protocol methods

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1050]
This is a follow-up task of https://github.com/Azure/autorest.java/issues/1049. Autorest should support updating a Java file that has a mixture of generated and handwritten methods based on the method annotation.

**Comment by weidongxu-microsoft** [comment]
This probably is not easy for autorest. autorest.java send the content of the file to autorest for writing.

Fluent codegen did some tricky stuff to first read the file (relative to `output-folder`), then write a new one based on its previous content, and finally send it to autorest.
https://github.com/Azure/autorest.java/blob/v4/fluentgen/src/main/java/com/azure/autorest/fluent/model/projectmodel/Project.java#L290-L302
It is probably not the best solution for large numbers of java files.

.NET can use partial class, which is not available to Java.

**Comment by qwordy** [comment]
Another approach to persist manual change is writing [customizations](https://github.com/Azure/autorest.java#customizations). It supports various types of customizations. However, it has limitations. It does not support adding custom code, e.g. changing the body of a method, adding a method. It is a common usage that add a wrapper on fundamental methods to provide high-level user experience.

**Comment by qwordy** [comment]
Study of the issue.
https://microsoft-my.sharepoint.com/:w:/p/fey/EWSuAr4hPhxChdCtrxLOXYABIDpjWVZbKbhzP6bRTv3Z_A?e=UmmlRL

**Comment by qwordy** [comment]
https://github.com/Azure/autorest.java/pull/1187

**Comment by weidongxu-microsoft** [comment]
A few cases you need to cover in test:

### Manually add class variable and method
They need to be kept.

### Manually update method signature
E.g. https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/webpubsub/azure-messaging-webpubsub/src/main/java/com/azure/messaging/webpubsub/WebPubSubServiceClient.java#L496-L500
permission changed from `String` to `WebPubSubPermission`.

### Manually remove method
E.g. https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/webpubsub/azure-messaging-webpubsub/src/main/java/com/azure/messaging/webpubsub/WebPubSubServiceClient.java#L108-L111
method changed to package private to remove it from public access.

### Updated swagger adding new method
They need to be added.

### Updated swagger removing method
They need to be removed if not customized.

### Updated swagger update method signature
They need to be updated if not customized.
