### ISSUE TITLE
Add only path parameters to parameter list

### ISSUE THREAD

**Issue by qwordy** [Azure/autorest.java#1084]
Add only path parameters to parameter list. Parameters can appear in many places in HTTP request. They can be in path, query, header, etc. Current behavior is required parameters will be exposed to users. I believe other languages face same problems. Maybe we should align the design across languages.

**Comment by weidongxu-microsoft** [comment]
For (1), I might slightly prefer the option of adding only path parameters (which gives best protection again swagger change). The rest required/optional parameter can go to the javadoc (similar as payload and response model).
Agree that we can just go consistent across all languages.

For (2), I believe Jianghao have plan and code for a improved javadoc on payload/response model, that you will be able to reuse later.
