### ISSUE TITLE
LLC header support

### ISSUE THREAD

**Issue by qwordy** [Azure/autorest.java#1087]
Return type of header test is wrong. Please fix it.
Current code:
```
public HeadersResponseExistingKeyResponse responseExistingKeyWithResponse(
            RequestOptions requestOptions, Context context)
```
The return type should be `Response<Void>` in this example.

**Comment by weidongxu-microsoft** [comment]
Seems nothing wrong? Response contains a header in swagger https://github.com/Azure/autorest.testserver/blob/main/swagger/header.json#L58-L63

**Comment by qwordy** [comment]
I prefer abandon models. We don't generate concrete Response class for models. We only provide general Response class in LLC.

**Comment by weidongxu-microsoft** [comment]
Sure. For LLC it only need a `Response`
