### ISSUE TITLE
Support x-ms-client-default

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1103]
https://github.com/Azure/autorest/blob/main/docs/extensions/readme.md#x-ms-client-default

m4 already put it to `Parameter.clientDefaultValue`. But current codegen seems only apply it in `ServiceClient`.

Sample in swagger https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2019-09-01/keyvault.json#L1074

**Comment by weidongxu-microsoft** [comment]
m4 appears already put it to `Parameter.clientDefaultValue`

**Comment by weidongxu-microsoft** [comment]
Handle for class property should be enough for first step.

**Comment by haolingdong-msft** [comment]
Issue fixed: https://github.com/Azure/autorest.java/pull/1189
