### ISSUE TITLE
Design and support ServiceVersion

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1110]
Reference to handwritten data-plane SDK `ServiceVersion`
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/appconfiguration/azure-data-appconfiguration/src/main/java/com/azure/data/appconfiguration/ConfigurationClientBuilder.java#L410-L413

**Solution**
`ClientBuilder` class will provide a method to set service version. It maps to `api-version` in swagger.
```
    public XXXClientBuilder serviceVersion(XXXServiceVersion version) {
        this.version = version;
        return this;
    }
```
`XXXServiceVersion` is an enum type. It defines service versions supported by service and latest version.
```
public enum XXXServiceVersion implements ServiceVersion {
    V2020_06_12("2020-06-12"),
    V2020_08_04("2020-08-04"),
    V2020_10_02("2020-10-02");

    private final String version;

    XXXServiceVersion(String version) {
        this.version = version;
    }

    @Override
    public String getVersion() {
        return this.version;
    }

    public static XXXVersion getLatest() {
        return V2020_10_02;
    }
}
```
Service version list is configured at config file or command parameter.
Config code is in yaml syntax. They are sorted in an ascending order. The bottom one is latest service version. Please add quotes around date.
```
service-versions:
  - "2020-06-12"
  - "2020-08-04"
  - "2020-10-02"
```
`ClientBuilder` class has
```
private XXXServiceVersion serviceVersion;

public XXXClientBuilder serviceVersion(XXXServiceVersion serviceVersion) {
    this.serviceVersion = serviceVersion;
    return this;
}

private XXXClientImpl buildInnerClient() {
    if (serviceVersion == null) {
        this.serviceVersion = XXXServiceVersion.getLatest();
    }
    ...
    XXXClientImpl client =
            new XXXClientImpl(pipeline, serializerAdapter, endpoint, serviceVersion.getVersion());
    ...
```
If user does not set service version, it will use latest service version by default.
`ClientImpl` class uses String type `apiVersion`.
```
private final String apiVersion;
```

**Comment by qwordy** [comment]
Add a test case
```
    @Test
    public void putValidWithApiVersion() throws Exception {
        BinaryData binaryData = BinaryData.fromString("{\"id\": 2, \"name\": \"abc\", \"color\": \"Magenta\"}");
        BasicClient tmpClient = new AutoRestComplexTestServiceBuilder().apiVersion("2020-01-01").buildBasicClient();
        tmpClient.putValid(binaryData, null);
    }
```
Service log
```
info: PUT /complex/basic/valid?api-version=2020-01-01 200 9.209 ms - -
```
Default API version is 2016-02-29.
```
    @Test
    public void putValid() throws Exception {
        BinaryData binaryData = BinaryData.fromString("{\"id\": 2, \"name\": \"abc\", \"color\": \"Magenta\"}");
        asyncClient.putValid(binaryData, null).block();
    }
```
```
info: PUT /complex/basic/valid?api-version=2016-02-29 200 12.954 ms - -
```
If all APIs do not define `api-version` parameter, builder will not have `apiVersion` method.

**Comment by qwordy** [comment]
`ClientBuilder` class will provide a method to set service version. It maps to `api-version` in swagger.
```
    public XXXClientBuilder serviceVersion(XXXServiceVersion version) {
        this.version = version;
        return this;
    }
```
If user does not set service version, it will use latest version by default. `buildInnerClient` method will set it.
`XXXServiceVersion` is an enum type. It defines service versions supported by service and latest version.
```
public enum XXXServiceVersion implements ServiceVersion {
    V2020_06_12("2020-06-12"),
    V2020_08_04("2020-08-04"),
    V2020_10_02("2020-10-02");

    private final String version;

    XXXServiceVersion(String version) {
        this.version = version;
    }

    @Override
    public String getVersion() {
        return this.version;
    }

    public static BlobServiceVersion getLatest() {
        return V2020_10_02;
    }
}
```

**Comment by weidongxu-microsoft** [comment]
@qwordy 

Could you elaborate a bit on the interface on Builder and Client?

I'd want to know which classes will use `ServiceVersion`, and which classes will use bare `apiVersion` String.

**Comment by qwordy** [comment]
@weidongxu-microsoft Updated. I put it at the beginning of page.
