### ISSUE TITLE
Unable to generate sync and async clients using the flags

### ISSUE THREAD

**Issue by daniel-rocha** [Azure/autorest.java#1157]
Hello,

I'm with the Azure Maps team and we're developing our SDKs now. Our codegen with sync convenience layers is working well (see logs) but when I try to build async convenience layers for Impls with "--generate-sync-async-clients", compilation is failing. 

Please see attached logs and let me know if I am doing anything wrong. Codegen is being tested with specs from azure-rest-api-specs (master), local autorest.java (v4) and autorest 3.3.2.

[autorest_failure1.txt](https://github.com/Azure/autorest.java/files/7013152/autorest_failure1.txt)
[autorest_success.txt](https://github.com/Azure/autorest.java/files/7013153/autorest_success.txt)
[autorest_failure2.txt](https://github.com/Azure/autorest.java/files/7013154/autorest_failure2.txt)

**Comment by weidongxu-microsoft** [comment]
@srnagar @jianghaolu this is data-plane, but I will take a quick look tomorrow. I will ping you if I cannot solve it.

**Comment by daniel-rocha** [comment]
adding @jianghaolu and @srnagar  per Weidong's instructions. 

Spec link: https://github.com/Azure/azure-rest-api-specs/tree/main/specification/maps 

The specific sub-project being tested is https://github.com/Azure/azure-rest-api-specs/tree/main/specification/maps/data-plane/Render

Command line: 

`autorest --track2 --version=3.3.2 --use=../autorest.java --generate-sync-async-clients=true --java.azure-libraries-for-java-folder=/tmp//sdk/maps --java --pipeline.modelerfour.additional-checks=false --pipeline.modelerfour.lenient-model-deduplication=true --verbose --sdk-integration --fluent=lite --java.fluent=lite --java.license-header=MICROSOFT_MIT_SMALL specification/maps/data-plane/Render/readme.md`

**Comment by srnagar** [comment]
@daniel-rocha and @weidongxu-microsoft `--fluent=lite` flag is set when running autorest. This is trying to generate management library. 
@daniel-rocha Can you try removing `--fluent=lite` and run it again if the swagger you are pointing to is for a data-plane service.

**Comment by weidongxu-microsoft** [comment]
Yes, something like this should get you started.

```
autorest --version=3.3.2 --use=../autorest.java --java --java.license-header=MICROSOFT_MIT_SMALL specification/maps/data-plane/Render/readme.md --generate-sync-async-clients=true --sync-methods=all
```

You may need to try a few other options after `--generate-sync-async-clients=true` (but never `--fluent` for data-plane).

**Comment by weidongxu-microsoft** [comment]
BTW @jianghaolu 

I will get this error if I target README from github (e.g. https://github.com/Azure/azure-rest-api-specs/blob/main/specification/maps/data-plane/Render/readme.md)
```
FATAL (Postprocessor): Unhandled error: Provider "https" not installed
java.nio.file.FileSystemNotFoundException: Provider "https" not installed
        at java.base/java.nio.file.Path.of(Path.java:212)
        at java.base/java.nio.file.Paths.get(Paths.java:97)
        at com.azure.autorest.postprocessor.Postprocessor.processInternal(Postprocessor.java:50)
        at com.azure.autorest.extension.base.plugin.NewPlugin.process(NewPlugin.java:206)
        at com.azure.autorest.postprocessor.Main.lambda$main$1(Main.java:12)
        at com.azure.autorest.extension.base.jsonrpc.Connection.lambda$dispatch$2(Connection.java:151)
        at com.azure.autorest.extension.base.jsonrpc.Connection.lambda$process$3(Connection.java:270)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
The problem is this line https://github.com/Azure/autorest.java/blob/v4/postprocessor/src/main/java/com/azure/autorest/postprocessor/Postprocessor.java#L50

**Comment by daniel-rocha** [comment]
Hi @srnagar @weidongxu-microsoft thanks for this. This particular issue is solved, there are others that I will investigate and talk to you in private. Thank you!
