### ISSUE TITLE
Add Flag to Prevent Generating a Client Builder

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/autorest.java#1174]
Add a flag which indicates to AutoRest to not generate a client builder for the generated service clients. This flag should be used in the cases when a hand-written service client will exist on top of the generated service client, effectively making the generated service client builder useless as the hand-written service client builders will provide that functionality. Instead, the constructors for the generated service clients will be made public and the hand-written service client builders will use those during construction.

**Comment by weidongxu-microsoft** [comment]
Add a flag would be easy. Or should we try to add a customization to remove a class? @jianghaolu
