### ISSUE TITLE
Improve javadoc for LLC clients

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1178]
The javadoc for `@return` tag for methods that return Mono<T> needs to be more descriptive.
See comment - https://github.com/Azure/azure-sdk-for-java/pull/23945/files/1bbee37a172546619b484bc106704f6d44e791c0#r703827414

**Comment by weidongxu-microsoft** [comment]
@srnagar 

Current code is doing certain heuristic on the description of method return.
https://github.com/Azure/autorest.java/blob/main/javagen/src/main/java/com/azure/autorest/mapper/ClientMethodMapper.java#L872-L917

Basically it first try the description of the operation (if we know it says "get something", then the return type would be "something").
Then it try the description on the schema of return type.
Finally it fallback to placeholder words like "completion" or "response", if it not able to find good candidate from swagger.

Any suggestion on improvement or wording?

**Comment by srnagar** [comment]
We can use something similar to the text below:

`Mono<Void>` - A {@link Mono} that completes when a successful response is received.
`Mono<T>` - Return "something" on successful completion of {@link Mono} (something here is the description in the operation)
`Mono<BinaryData>` - Returns the response body on successful completion of {@link Mono}

`void` - no @return tag
`Response<Void>` - Returns the {@link Response} 
`Response<T>` - Returns "something" along with {@link Response}
`Response<BinaryData>` - Returns the response body along with {@link Response}

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Please see if you can handle this. This applies to every client (not limited to LLC, include mgmt).

**Comment by XiaofeiCao** [comment]
> @XiaofeiCao Please see if you can handle this. This applies to every client (not limited to LLC, and it includes mgmt).

I've skimmed the client methods generated by autorest.java and the code that's generating the return type docs. I think it should be fine.

**Comment by XiaofeiCao** [comment]
Related PR: 
https://github.com/Azure/autorest.java/pull/1299

According to suggestion from @srnagar , code can be simplified to reduce complexity. Original PR's merged so will open another PR.

**Comment by XiaofeiCao** [comment]
Fixed in https://github.com/Azure/autorest.java/pull/1334
