### ISSUE TITLE
`settings.getServiceName()` throws NPE

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#1185]
There are multiple usages of `settings.getServiceName()` in the generator, especially for building service version related components. `--service-name` is an optional argument which could lead to NullPointerException.

Examples include:
https://github.com/Azure/autorest.java/blob/main/javagen/src/main/java/com/azure/autorest/Javagen.java#L129
https://github.com/Azure/autorest.java/blob/main/javagen/src/main/java/com/azure/autorest/mapper/ServiceClientMapper.java#L128

Alternative ways should be used from existing information in the code model.

**Comment by qwordy** [comment]
@jianghaolu Thanks for finding this bug. I will fix it as soon as possible.
