### ISSUE TITLE
[Java] Increase the test coverage up to 80% for code generator

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.java#1219]
Up to 80%

**Comment by ArthurMa1978** [comment]
Code coverage is 82% now

**Comment by weidongxu-microsoft** [comment]
coverage report added to CI of codegen for mgmt
https://github.com/Azure/autorest.java/runs/4415947353
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1230565&view=codecoverage-tab
