### ISSUE TITLE
codesnippet stub for LLC

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1221]
```
<!-- src_embed namespace.className.methodName(#paramType(-paramType)*)? -->
<!-- end namespace.className.methodName(#paramType(-paramType)*)? -->
```

doc on codesnippet tool: https://github.com/Azure/azure-sdk-tools/blob/main/packages/java-packages/codesnippet-maven-plugin/README.md

only required in `AsyncSyncClient` (hence it's related template).

Wait for confirmation on whether codesnippet tool support the case that no sample find for the stub (the case that dev did not provide the sample).

**Comment by XiaofeiCao** [comment]
Close as finished.
