### ISSUE TITLE
Reduce number of service method overloads

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.java#129]
Right now we generate 8(!) overloads for each REST API method in a common case.

- All parameters
  - Single<RestResponse<THeaders, TBody>>
  - Single<TBody>
  - ServiceFuture<TBody>
  - TBody
- Only required parameters (if any optional parameters exist)
  - Single<RestResponse<THeaders, TBody>>
  - Single<TBody>
  - ServiceFuture<TBody>
  - TBody

Having "only required parameters" overloads is handy for many REST APIs which have lots and lots of optional parameters that are almost never used. But every combination we support tends to cause the noise of these APIs to grow and grow. It's conceivable to think that searching for the exact name of a REST API method and seeing oodles of overloads winds up increasing confusion more than having the exactly most convenient type for each particular user alleviates that particular user's confusion.

I suggest we drop all but 2 of these overloads--the `Single<MyGetResponse>`-- and if our users prefer to convert to a different type they can use one of several simple conversions:

- `.blockingGet()`
- `.map(MyGetResponse::body)`
- `.toFuture()`
- `.to(SingleConversion.completableFuture())` which we would provide

At this point, the naming conventions would no longer be necessary and we could simply say `get` instead of `getWithRestResponseAsync`-- WithRestResponse is no longer needed and the Async suffix is a .NET-ism that doesn't really belong in Java. Every single method in these MethodGroup and ServiceClient classes will be async and the return types will convey that.

**Comment by JonathanGiles** [comment]
Simplifying API in terms of the 'overload generation' discussion is a great idea. I will need to understand better on the first topic regarding custom classes to simplify method signature, as this is not always a win.

**Comment by RikkiGibson** [comment]
Split and created issue #153

**Comment by RikkiGibson** [comment]
Ideally this will happen before service teams that depend on us go into public preview

**Comment by jianghaolu** [comment]
This is now obsolete with fewer overloads in v4 generator.
