### ISSUE TITLE
Add Java 8 support to generator

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.java#131]
The generator needs a way to produce code that takes advantage of Java 8's improvements. I think adding a flag such as `--java.version=8` would be scalable in the future (`--java.version=9`) and would be clear enough to show its intended meaning.

**Comment by RikkiGibson** [comment]
At some point within a few weeks or so, 7 support will be dropped in the runtime in a snapshot build. So 8 will be the only option for this for some time, right?

**Comment by daschult** [comment]
That’s partially correct. It would still be possible for someone to target an older version of the runtime. The generator should support that.

**Comment by RikkiGibson** [comment]
We can publish a beta before we go to 8 but the snapshots are ephemeral—eventually the ability to access the older ones we’ve published will go away

**Comment by RikkiGibson** [comment]
Is anything remaining on this besides moving off of Joda Time?

**Comment by daschult** [comment]
I think that's it.
