### ISSUE TITLE
Generate separate client builders for each operation group client

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1328]
Currently, we generate a single builder for creating clients for each operation group. We should instead generate separate builders for each client type.
For example, in [DeviceUpdate](https://apiview.dev/Assemblies/Review/849d24acb5dc4bf1bdd2d08e10e7c114#com.azure.iot.deviceupdate.DeviceUpdateClientBuilder), we have a single `DeviceUpdateClientBuilder` which builds `DeviceUpdateClient` and `DeviceManagementClient`. This issue is to track changing the generator to generate `DeviceUpdateClientBuilder` and `DeviceManagementClientBuilder`.

**Comment by weidongxu-microsoft** [comment]
This probably take some time to design (maybe multiple wrapper Builder for a single BuilderImpl?) and implement.

Do we have a date for this requirement?

**Comment by srnagar** [comment]
I guess this will need to be done before the next LLC client goes GA that has mulitple operation groups. I don't know if there's a specific date for it but I guess DeviceUpdate will be the first to GA that might need this

**Comment by weidongxu-microsoft** [comment]
Got it.

Any idea on the design? Does multiple wrapper Builder for a single BuilderImpl (similar to sync async client wraps ClientImpl) look good to you?

Also put it under an option like `builder-per-client`?

It could make customization a bit more difficult, as if we want to add `connectionString`, we will now need to add it to all Builder classes.
