### ISSUE TITLE
For output-only models, do not generate setter methods

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1336]
For models that are returned as part of response only and not used in any input requests, we should not generate setter methods and make the type immutable.

**Comment by sharathmalladi** [comment]
Upvoting this issue :).

**Comment by weidongxu-microsoft** [comment]
I should be able to get some time on it after Sept. 12 (after the Cadl Aug. work).

There was an early impl https://github.com/Azure/autorest.java/pull/1490 but that was closed.

**Comment by weidongxu-microsoft** [comment]
An additional consideration on output-only model is that, we do not want to have ctor with parameters (aka, only the default ctor), in case of "required-fields-as-ctor-args" option.

As adding required parameter to output-only model is not breaking change in REST, we do not want it to be breaking change in Java model.

**Comment by weidongxu-microsoft** [comment]
Will be included in 4.1.5 (not released yet).

Note the side effect of `--output-model-immutable` is that these model will have private ctor (Jackson can still de-serialize it) to avoid breaking changes when ctor changes.
