### ISSUE TITLE
Writing DPG customizations documentation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#1341]
As GA requirement for the project, we want to have explicitly written the documentation for service teams on how to grow-up their DPG into an improved SDK.

Documentation should be written with:
- Basics on customizations for this language
- One scenario, one section. Like a FAQ document

Required sections are (at the minimum):
- Change operation behavior (new signature, or any wrapping)
- Change client behavior (default pipeline configuration, etc.)
- Add models manually written

More sections might be added, and I'll update this initial text with date when I add them (for clarity)

**Comment by weidongxu-microsoft** [comment]
Doc https://github.com/Azure/autorest.java/pull/1392/files
Feedback welcomed.

I haven't find a good place for customization on LRO.
