### ISSUE TITLE
Use Traits in generated client builders.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/autorest.java#1342]
Azure Core introduced traits - interfaces that describe what client builders. See https://github.com/Azure/azure-sdk-for-java/pull/26562 for more details and example usage in non-generated client here https://github.com/Azure/azure-sdk-for-java/blob/5a0a5d77ee9b26b7dc9fbe85fd12326942b394be/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobClientBuilder.java#L62-L70 .

Generated client builders should use new traits where applicable.

**Comment by srnagar** [comment]
Done in https://github.com/Azure/autorest.java/pull/1408
