### ISSUE TITLE
Support for OASIS Request Repeatability Headers

### ISSUE THREAD

**Issue by mikekistler** [Azure/autorest.java#1343]
**Describe the issue or request**

The Azure API Guidelines say that all operations should be idempotent. This is mainly an issue for POST operations. For situations where a POST needs to be made idempotent, the guidelines recommend

☑️ YOU SHOULD support repeatable requests according as defined in [OASIS Repeatable Requests Version 1.0](https://docs.oasis-open.org/odata/repeatable-requests/v1.0/repeatable-requests-v1.0.html).

Some teams have begun following this advice and including the OASIS Request Repeatability headers in their REST API.

This raises the question of how the Azure SDKs should support OASIS Repeatability headers. 

**Describe your ideas for solutions**

 I think we should treat these headers specially -- meaning _not_ simply expose them as optional parameters that are set by the caller.  Instead, I think the SDK should set these headers within the method for any operation that supports them.

The headers involved are `Repeatability-Request-ID`, which the SDK should set to a freshly minted UUID, and `Repeatability-First-Sent`, which should be set to the current date/time.

The Java generator should check for the presence of these headers and produce the additional logic as described here.

**Comment by weidongxu-microsoft** [comment]
@mikekistler

Do we know if autorest/modelerfour intend to do some processing on `Repeatability-Request-ID` and `Repeatability-First-Sent` headers?

Ask because change in moderfour would very likely break any codegen in its downstream.

PS: data-plane using the headers https://github.com/Azure/azure-rest-api-specs/blob/main/specification/communication/data-plane/Chat/preview/2020-11-01-preview3/communicationserviceschat.json

**Comment by weidongxu-microsoft** [comment]
If there be no processing from modelerfour, codegen plan to do following:
1. Hide 2 headers from client method signature
2. When user calls the client method, fill a random GUID to `Repeatability-Request-ID` and RFC1123 datetime to `Repeatability-First-Sent` and call the internal method to send the REST call
3. [NO CHANGE] Default configure to azure-core pipeline would have request retried a few times, for most of 5xx, 408, 429

**Comment by mikekistler** [comment]
@weidongxu-microsoft This sounds like a great plan. Thanks!

**Comment by weidongxu-microsoft** [comment]
Discussion after Timothee and Laurent. The plan is to combine "ignore-headers" in m4 and a new pipeline (pre-request) in azure-core to have this exact effect. Laurent will raise it to architect for cross-language consistency.

**Comment by weidongxu-microsoft** [comment]
No update on azure-core.

m4 supports `specialHeaders` for "Repeatability-Request-Id", "Repeatability-First-Send".
https://github.com/Azure/autorest/pull/4433

Start codegen dev.

**Comment by weidongxu-microsoft** [comment]
It still require a new modelerfour release to work (as there is a fix there), likely 4.22.4

Will update codegen after m4 upgrade.
