### ISSUE TITLE
Add `sendRequest()` method to clients to support sending any HTTP request

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1356]
Add an `sendRequest()` method (method name is not final) that can send any HTTP request. This should be optionally added to clients either that are newly generated or for ones that have previously existed.

### Sync client
```java
HttpRequest httpRequest = ...
Response<BinaryData> response = client.sendRequest(httpRequest, context);
```

### Async client

```java
HttpRequest httpRequest = ...
Mono<Response<BinaryData>> response = client.sendRequest(httpRequest);

**Comment by weidongxu-microsoft** [comment]
- behind an option
- use pipeline.send without proxy method
