### ISSUE TITLE
Current customization module does not have latest code

### ISSUE THREAD

**Issue by daniel-rocha** [Azure/autorest.java#1385]
Hello,

The current maven module on https://search.maven.org/artifact/com.azure.tools/azure-autorest-customization does not seem to have the latest code.

How to reproduce: 

1. Download the module via pom file
2. Build a small customization that calls ClassCustomization.removeMethod();
3. This will not compile - it will say that ClassCustomization.removeMethod() is missing.

Older versions of this module seemed to have this functionality. I pulled it in August 2021 and it's there - my dev @khmic5 did the same today and the code isn't there. Having to use a locally built jar at the moment.

**Comment by weidongxu-microsoft** [comment]
cc @srnagar @alzimmermsft 

@daniel-rocha Let us know whether this is urgent. If urgent we might do a local build and try publish that.
Ideally we would like to have some automation to build and upload, and it could take a week or so.

**Comment by daniel-rocha** [comment]
@weidongxu-microsoft not urgent as we are still building everything locally. When we move to the pipeline (~mid April) then it will become a problem as the code will no longer compile pulling straight from the Maven repo.

**Comment by weidongxu-microsoft** [comment]
@daniel-rocha We still do not have automation from EngSys. So let me or Alan know when you need to lib, so that we can prepare manual publish to maven.
