### ISSUE TITLE
[DPG] We should not use LLC or low level clients in public document /autorest commands

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#1415]
As we are using to data plane codegen as our product name, please update the our public docs and autorest commands to stop using LLC/ low level clients.

In Java, it seems we are still using the flag like  --low-level-client
https://github.com/Azure/autorest.java/blob/main/docs/generate/dataplane.md

**Comment by weidongxu-microsoft** [comment]
@srnagar Any objection?

**Comment by weidongxu-microsoft** [comment]
@lirenhe Any common name of option for it, if we change?

**Comment by lirenhe** [comment]
> @lirenhe Any common name of option for it, if we change?

I would suggest '--data-plane' if this is not used.
