### ISSUE TITLE
[DPG]: Improve the layout of functions parameters in autogenerated document

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#1432]
The auto generated document for DPG contains some raw data which is not well formatted.
example:  https://docs.microsoft.com/en-us/java/api/com.azure.iot.deviceupdate.deviceupdateclient?view=azure-java-preview
Please improve the document to be consistent with other java libraries.

![image](https://user-images.githubusercontent.com/9100546/167241106-331ebf5f-e215-4986-b64c-25f0a5f19f50.png)

**Comment by weidongxu-microsoft** [comment]
Would do you mean by raw data?

Without these data, how does customer know what kind of model to set as payload and response body?
