### ISSUE TITLE
DPG, support merge of module-info for partial-update

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1439]
After enabling `generate-models` and configure of `custom-types`, `module-info.java` would become e.g.
```
module com.azure.communication.phonenumbersdemo {
    requires transitive com.azure.core;

    exports com.azure.communication.phonenumbersdemo;
    exports com.azure.communication.phonenumbersdemo.models;

    opens com.azure.communication.phonenumbersdemo.implementation.models to
            com.azure.core,
            com.fasterxml.jackson.databind;
    opens com.azure.communication.phonenumbersdemo.models to
            com.azure.core,
            com.fasterxml.jackson.databind;
}
```

from
```
module com.azure.communication.phonenumbersdemo {
    requires transitive com.azure.core;

    exports com.azure.communication.phonenumbersdemo;
}
```

And it need to be merged with previous version of `module-info.java`.

**Comment by haolingdong-msft** [comment]
@weidongxu-microsoft  I plan to parse the module file, and do the merge in the order of 'requires', 'exports', 'opens', 'uses', 'provides' directives. One minor issue is that it would be a bit hard to add an empty line between each type of directives. Please let me know if there is any concern.

**Comment by weidongxu-microsoft** [comment]
Sounds good.

Formatting is fine. As long as checkstyle on SDK repo does not report error, you have full freedom.
