### ISSUE TITLE
ClassCustomization.removeMethod Bug

### ISSUE THREAD

**Issue by khmic5** [Azure/autorest.java#1444]
There is a current workaround on using `removeAnnotation(@Override)` then removeMethod for this issue so it is not urgent

When there is `@Override` above the method, it doesn't remove `@Override` and causes format error (unable to remove method)

For example, shown through --skip-formatting:

The function call:
`ClassCustomization classCustomization = models.getClass("ErrorResponseException");`
`classCustomization .removeMethod("getValue");`

`@Override`
 `public ErrorResponse getValue() {`
          `    return (ErrorResponse) super.getValue();`
 `}`

Will leave this in the code instead of removing the entire method:
`@Override`

I am currently using this version of dependency in pom.xml:
`<dependency>`
  `    <groupId>com.azure.tools</groupId>`
  `    <artifactId>azure-autorest-customization</artifactId>`
 `     <version>1.0.0-beta.4</version>`
  `</dependency>`
  
  I am running it via:
  mvn install && autorest --java --use:@autorest/java@4.0.x

**Comment by weidongxu-microsoft** [comment]
@alzimmermsft 

Please let me know if you are familiar with this. Not very urgent since dev find a way to workaround (first remove that annotation).

Also do we recommend using `customizeAst` instead for complex customization completely within single class?

**Comment by alzimmermsft** [comment]
@weidongxu-microsoft I'll get a fix out for this soon.

> Also do we recommend using customizeAst instead for complex customization completely within single class? (personally I feel more comfortable working with customizeAst as JavaParser)

I wouldn't recommend it as the first choice, I initially added it for "this case isn't covered yet or is too complex for the customization framework" as it involves learning another library to make changes.
