### ISSUE TITLE
Paging doesn't use latest nextPageLink or respect top parameter

### ISSUE THREAD

**Issue by daschult** [Azure/autorest.java#145]
Created from [this](https://github.com/Azure/azure-libraries-for-java/issues/184) issue.

**Comment by RikkiGibson** [comment]
The customer let us know that the latest nextPageLink is actually being respected in their case. I think there's no way for the runtime/generator to automatically understand and respect the `top` parameter.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/consumption/resource-manager/Microsoft.Consumption/stable/2018-01-31/consumption.json#L77

PagedList itself has no way of knowing what to do except to follow a nextLink if one is given. I don't think there's anything for us to change on the 1.x side however I think we should remove the PagedList type along with the sync methods for 2.x.

**Comment by RikkiGibson** [comment]
Please reopen if you find something actionable based on customer feedback from the original issue.
