### ISSUE TITLE
Remove model-override-setter-from-superclass Configuration Setting

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/autorest.java#1454]
`model-override-setter-from-superclass` was added to help ease models to using full fluent style, before inherited classes could have this generation:

```java
public class SuperClass {
  public SuperClass setSomething(String something);
}

public class SubClass extends SuperClass {
  public SubClass setSomethingElse(boolean somethingElse);
}
```

Where the subclass wouldn't override the super class methods to use the subclass as the return type. This is now the standard guideline to have subclasses override the setters to maintain fluent calling, so the `model-override-setter-from-superclass` setting can be removed to ensure all new code generations use this pattern.

**Comment by weidongxu-microsoft** [comment]
mgmt and dpg always has it as default.

If vanilla can also have it as default, we should be able to remove it.

**Comment by weidongxu-microsoft** [comment]
already done https://github.com/Azure/autorest.java/pull/1571
