### ISSUE TITLE
Improve Javadoc to show optional/required properties and include sample codesnippets

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1464]

**Comment by mikekistler** [comment]
Just to make sure this detail isn't lost: 

@tg-msft made the specific suggestion to add a sentence just above the query parameters table along the lines of: "You can add these to a request with `request.queryParams.add( ...`" (or whatever the actual syntax is).

Also include the description and optional/required from the API definition for each property in the Response Body Schema section (and the Request Body Schema if it has a similar section).
