### ISSUE TITLE
DPG, content-type info lost, if body is not required

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1472]
swagger
https://github.com/Azure/autorest.testserver/blob/main/swagger/media_types.json#L56-L67

vanilla
https://github.com/Azure/autorest.java/blob/main/vanilla-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java#L187

but it "text/plain; charset=UTF-8" is lost in DPG.

---

Also add more tests on media-type

**Comment by weidongxu-microsoft** [comment]
Some possible case for non-required body.

PUT `/resources/{name}`
with all properties in body optional, hence that body itself can be optional.

But in this case, we want to avoid user to add `content-type=application/json` on every call with a body.

**Comment by haolingdong-msft** [comment]
For multiple content type case, we will add content-type in @param or param table section depends on the body is required or not.
For single content type, if body is required, code supply the content type. If body is optional, we need to add content-type in header param table section, and the description should mention the value required.


For more details, refer to issue：https://github.com/Azure/autorest.java/issues/1534

**Comment by weidongxu-microsoft** [comment]
@haolingdong-msft 

Do you remember whether we eventually did this: "For single content type, if body is required, code supply the content type. If body is optional, we will add content-type in header param table section, and the description mention the value required."?

**Comment by haolingdong-msft** [comment]
@weidongxu-microsoft , I think we did not handle the body optional case for single content type in TSP, but I remember we handle it for DPG previsouly. I can create an issue to track this.

DPG code:
https://github.com/Azure/autorest.java/blob/main/protocol-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java#L88-L123

swagger: https://github.com/Azure/autorest.testserver/blob/main/swagger/media_types.json#L52

**Comment by weidongxu-microsoft** [comment]
It should be same. Maybe there's some different on media-type data when converted from tsp.

**Comment by haolingdong-msft** [comment]
@weidongxu-microsoft Agree, created an issue to track: https://github.com/Azure/autorest.java/issues/2185

**Comment by weidongxu-microsoft** [comment]
We may use a similar trick to set it only when there is body, but `content-type` not set.

```java
        requestOptions.addRequestCallback(request -> {
            if (request.getBody() != null && request.getHeaders().stream().noneMatch(h -> h.getName().equalsIgnoreCase("content-type"))) {
                request.setHeader(HttpHeaderName.fromString("content-type"), "<single_content_type>");
            }
        });
```
