### ISSUE TITLE
Generate the JAVA SDK failure

### ISSUE THREAD

**Issue by qinqingxu** [Azure/autorest.java#1496]
I try to run these commands:

> **autorest readme.md  --csharp --azure-arm --tag=package-2022-05-10-privatepreview --output-folder=csharp_sdk/
> autorest readme.md  --python --azure-arm --tag=package-2022-05-10-privatepreview --output-folder=python_sdk/**

They are all succeeded.

But, when I try to run this command:

> **autorest readme.md  --java --azure-arm --tag=package-2022-05-10-privatepreview --output-folder=java_sdk/**

It show the error like:

```

AutoRest code generation utility [cli version: 3.6.1; node: v16.13.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.7.0.
info    |    Loading AutoRest core      'C:\Users\qinqiangxu\.autorest\@autorestcore@3.8.4\nodemodules\@autorest\core\dist' (3.8.4)

info    |    Installing AutoRest extension '@autorest/java' (^4.0.24 -> 4.0.24)
info    |    Installed AutoRest extension '@autorest/java' (^4.0.24->4.0.24)
error   |   Error: ENOENT: no such file or directory, scandir 'C:\Users\qinqiangxu\.autorest\@autorestjava@4.0.24\nodemodules\@autorest\java'
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
fatal   | Failed to install extension '@autorest/java' (^4.0.24)

```

**Comment by weidongxu-microsoft** [comment]
Java has lots of flags that is required for either data-plane for control-plane.
It is always recommended to use Azure pipeline for this.

See https://github.com/Azure/azure-sdk-for-java/wiki/%5BManagement%5D--OpenAPI-specs for control-plane
See https://github.com/Azure/azure-sdk-for-java/wiki/Protocol-Methods-Quickstart-with-AutoRest for data-plane

**Comment by qinqingxu** [comment]
Thanks, but if our API spec is still in the private repo, and if we just want to generate the SDK in the local, but without PR.

Is there any way to do that?

BTW, I want to generate the Control Plane SDK/CLI

**Comment by weidongxu-microsoft** [comment]
If you can make a PR (just a draft PR), SDK automation will also generate it for you, if you have this `swagger-to-sdk` part in your readme.md (and include `azure-sdk-for-java` item)
https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/samplefiles/samplereadme.md#swagger-to-sdk

**Comment by weidongxu-microsoft** [comment]
If you only only do in local, go with this python script
https://github.com/Azure/azure-sdk-for-java/wiki/%5BManagement%5D--OpenAPI-specs#use-python-script

**Comment by weidongxu-microsoft** [comment]
If you can't use the python script, you can try this
```
autorest --version=3.8.4 --use=@autorest/java@4.0.60 --java output-folder=<> --namespace=<> --azure-arm --generate-samples --fluent=lite
```

**Comment by weidongxu-microsoft** [comment]
Make sure you have Java runtime equal or higher than 11

`java -version`

**Comment by qinqingxu** [comment]
Finally, it is work with this command, thanks.

autorest --version=3.8.4 --use=@autorest/java@4.0.60 --java --output-folder=java_sdk/ --namespace=Microsoft.AppComplianceAutomation --azure-arm --generate-samples --fluent=lite readme.md
