### ISSUE TITLE
x-ms-skip-url-encoding has no Effect on Java Generated Code

### ISSUE THREAD

**Issue by ThomasMarquardt** [Azure/autorest.java#150]
I am using AutoRest 2.0.4245 and noticed that x-ms-skip-url-encoding has no effect on the Java generated code.  In the example swagger below, the path parameter is still URL encoded, even when  x-ms-skip-url-encoding is true:

``` 
{
  "swagger": "2.0",
  "info": {
    "description": "Test URL encoding.",
    "title": "Test",
    "version": "2018-02-18"
  },
  "host": "localhost",
  "schemes": [
    "http",
    "https"
  ],
  "paths": {
    "/{path}": {
      "get": {
        "operationId": "GetPath",
        "description": "Test Path Parameter.",
        "responses": {
          "200": {
            "description": "Test"
          }
        }
      },
      "parameters": [
        {
          "name": "path",
          "in": "path",
          "description": "The path to test.",
          "required": true,
          "type": "string",
          "x-ms-skip-url-encoding": "true"
        }
      ]
    }
  }
}
```

**Comment by RikkiGibson** [comment]
Will try to repro locally and publish a generator/runtime patch as needed.

It's particularly useful for us to know the version of autorest.java in use, which is displayed when you use AutoRest to generate Java code. For example:
```
AutoRest code generation utility [version: 2.0.4245; node: v8.3.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '/private/var/folders/1r/gbft_cds5s7988wxjpqbxkp40000gn/T/.autorest/@microsoft.azure_autorest-core@2.0.4245/node_modules/@microsoft.azure/autorest-core/dist' (2.0.4245)
   Loading AutoRest extension '@microsoft.azure/autorest.java' (~2.1.32->2.1.32)
```
`2.1.32` is the most relevant piece of version information for us. For now I will assume you are just using the `@latest` which is 2.0.20.

**Comment by ThomasMarquardt** [comment]
Sorry, I typed it by hand when I posted the issue originally.  The issue still exists,  `"x-ms-skip-url-encoding": true` has no effect on the generated code.  Whether it is true or false, the same code is generated.  The version info for AutoRest is below.

```
AutoRest code generation utility [version: 2.0.4245; node: v7.10.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\tmarq\AppData\Local\Temp\.autorest\@microsoft.azure_autorest-core@2.0.4245\node_
modules\@microsoft.azure\autorest-core\dist' (2.0.4245)
   Loading AutoRest extension '@microsoft.azure/autorest.java' (~2.1.32->2.1.32)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.38->2.3.38)

```

**Comment by RikkiGibson** [comment]
When I use `"x-ms-skip-url-encoding": true` I see the `'/'` characters getting escaped to %2F. I do notice that Retrofit (library we depend on) has a habit of encoding things it thinks shouldn't be in the path parameter regardless of whether we specify `@Path("...", encoded=true)` such as `' '` and `'#'` characters. Is it possible that's what's causing you problems?

**Comment by RikkiGibson** [comment]
`x-ms-skip-url-encoding: true` is only respected when `azure-arm: true` is specified. Since the extension isn't specified as being limited to Azure use cases I suggest changing it so it's respected for every generator mode. I've pushed the SkipUrlEncodingVanilla branch which implements this change.

**Comment by ThomasMarquardt** [comment]
Thanks, my team needs `x-ms-skip-url-encoding` and our API is not related to Azure ARM, so I hope this change can be committed soon.

**Comment by RikkiGibson** [comment]
AutoRest supports loading an extension from a GitHub branch. As a short-term stopgap you can pass the below argument to AutoRest to get the new behavior.
```
--use=Azure/autorest.java#SkipUrlEncodingVanilla
```
