### ISSUE TITLE
DPG: Async clients include LRO and non-LRO methods for same operation

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1508]
See Device Update:
https://apiview.dev/Assemblies/Review/da0da57333ed4ff68f533710ef52cead#com.azure.iot.deviceupdate.DeviceManagementAsyncClient

**Comment by weidongxu-microsoft** [comment]
This might be an artifact from very early version of DPG (LLC) that allow non-breaking-change, if service add the `x-ms-long-running-operation` to the swagger.
