### ISSUE TITLE
“path” parameters are URL encoded differently in Java than in C#

### ISSUE THREAD

**Issue by ThomasMarquardt** [Azure/autorest.java#151]
Using AutoRest 2.0.4245, I noticed that “path” parameters are URL encoded differently in Java than in C# (Swagger below).  In Java, “dir/file” is encoded as “dir%2Ffile”.  In C#, it is encoded as “dir/file”.  I like the way C# encodes paths and would like URL encoding to be consistent across the languages.

``` 
{
  "swagger": "2.0",
  "info": {
    "description": "Test URL encoding.",
    "title": "Test",
    "version": "2018-02-18"
  },
  "host": "localhost",
  "schemes": [
    "http",
    "https"
  ],
  "paths": {
    "/{path}": {
      "get": {
        "operationId": "GetPath",
        "description": "Test Path Parameter.",
        "responses": {
          "200": {
            "description": "Test"
          }
        }
      },
      "parameters": [
        {
          "name": "path",
          "in": "path",
          "description": "The path to test.",
          "required": true,
          "type": "string"
        }
      ]
    }
  }
}
```

**Comment by RikkiGibson** [comment]
I can't repro this behavior with .NET Core 2.0 on my Mac. When I generate the C# client with:

```sh
--use=@microsoft.azure/autorest.csharp@latest
```

and pass a URL parameter like `abc/123$@`, I see `abc%2F123%24%40%23` in my debugging proxy.

Will follow up after I try to repro on my PC.

**Comment by RikkiGibson** [comment]
I also see `%2F` instead of `/` in Fiddler when I run with .NET Core 2 on Windows. @ThomasMarquardt please double check whether the client you generated had `x-ms-skip-url-encoding` or not. Let me know if you have any idea of what could explain the difference in behavior between our environments.

It's not likely we'll support this unless I can find someone on the C# side who can tell me they definitely are skipping encoding `/`, and the fact that `/` is getting encoded in my environment is a bug.

@shahabhijeet do you know what the expected behavior of URL encoding '/' with the C# runtime is?

**Comment by ThomasMarquardt** [comment]
I made a mistake, and both C# and Java are incorrectly encoding `/`.  C# is calling `System.Uri.EscapeDataString(path)` but it should be calling `System.Uri.EscapeUriString(path)` because path is a parameter in the URI.

**Comment by RikkiGibson** [comment]
I've been looking around to try and make sure of what the spec is supposed to be. It appears that by default we need to escape slashes in path params. It sounds like C# and Java are doing this. Feel free to follow up with any suggestions if "x-ms-skip-url-encoding" is not enough to address your use case.

https://github.com/swagger-api/swagger-js/pull/280
https://github.com/OAI/OpenAPI-Specification/issues/892

**Comment by ThomasMarquardt** [comment]
Sorry, what I said in my previous post is incorrect.  Although C# uses System.Uri.EscapeDataString to escape path parameters, and the `/` character is encoded as `%2F` by that call, later when the request is sent across the wire the URL has `/` character--it is not encoded.  Java, on the other hand, sends it as %2F.  This is a problem for us.

**Comment by RikkiGibson** [comment]
It would be of great help to us if you could provide a sample project which reproduces the C# runtime behavior you describe.

**Comment by jianghaolu** [comment]
If you want to skip URL encoding for a path parameter, please use `x-ms-skip-url-encoding` as Rikki suggested above. See https://github.com/Azure/autorest/tree/main/docs/extensions#x-ms-skip-url-encoding for details and examples.

If this is still an issue with `x-ms-skip-url-encoding` added, please feel free to reopen.
