### ISSUE TITLE
Client, set/replace api-version in LRO URL

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1511]
Actually apply to all client.

Simple case is api-version is same across client.
A slight complex case is api-version per method (usually happen in mgmt, but also on synapse data-plane).

And we probably only handle for `api-version` in query. If service calls it another name, we probably not able to handle that.

It could be only addition if not available, or addition and replacement.

Might need support from azure-core.
```[tasklist]
### Tasks
- [ ] Use cadl-ranch azure core lro case to test if api version is correctly appended, add assertions in cadl-ranch as well
```

**Comment by haolingdong-msft** [comment]
From Srikanta: We only should be able to set/replace API versions in LRO and paging APIs when it's a query param. The API version should be the same as the client version created by the customer. Do not modify api versions that are part of the path param

**Comment by weidongxu-microsoft** [comment]
For api-version https://github.com/Azure/autorest.java/blob/main/javagen/src/main/java/com/azure/autorest/model/clientmodel/ParameterSynthesizedOrigin.java#L26 (path parameter will have this too)
