### ISSUE TITLE
DPG/Tests, update to latest autorest.testserver, add DPG tests

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1515]
new testserver breaks many existing tests, prepare for a day.

**Comment by weidongxu-microsoft** [comment]
you can add an issue to make DPG 100% in http://azure.github.io/autorest/dashboard.html

**Comment by haolingdong-msft** [comment]
issue created: https://github.com/Azure/autorest.java/issues/1549
