### ISSUE TITLE
Generate models required for specific operations in REST API

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1521]
Design for specifying operations/operation groups that need models. The generator should include only models that are needed by the specified operations in public package. The generator, however, may decide to generate all models in implementation package.

**Comment by weidongxu-microsoft** [comment]
One issue is how to specify this in CADL. (assume we discard autorest and its md configs)

**Comment by weidongxu-microsoft** [comment]
For now, we will use a `@convenienceMethod` decorator on CADL operation.

Then related model will get `usage: convenience-method` populated to all class/enum. And template will only write these.

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/autorest.java/issues/1670
