### ISSUE TITLE
Generate models with optional properties

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1524]
Generate models that have optional properties with fluent-style getter/setter methods.

**Comment by weidongxu-microsoft** [comment]
CADL with e.g. `description?:string` will be optional.

nullable in CADL would be e.g. `description: string | null`.

**Comment by weidongxu-microsoft** [comment]
the default value in CADL is for service, SDK does not use it.

https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1658523457132?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1658523457132&teamName=Azure%20SDK&channelName=Cadl%20Discussion%20%F0%9F%90%AE&createdTime=1658523457132
