### ISSUE TITLE
Generate models containing properties with built-in types

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1525]
- [x] boolean
- [x] string
- [x] byte
- [x] int (should this always be generated as long to be resilient?)
- [x] long
- [x] double
- [x] duration
- [x] datetime
- [x] array (mainly just for byte array)
- [x] list
- [x] map

**Comment by weidongxu-microsoft** [comment]
all types of int is generated as long.
all types of float is generated as double.
these is not format of bytes as Base64URL, so it is generated as ByteArray.

**Comment by weidongxu-microsoft** [comment]
as change to the ModelSpecs, we might want int instead (.NET distinguish int and long)

**Comment by weidongxu-microsoft** [comment]
CADL do not have a char, I assume we will use int for int8 or int 16.

int32 to int
int64 to long

uint treated same as int.

**Comment by weidongxu-microsoft** [comment]
float32 for now is still double.
