### ISSUE TITLE
Generate models with constants

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#1527]
Models should have a `private static final` variable defined for constants.

**Comment by weidongxu-microsoft** [comment]
Currently we only generate Constant for Enum with single value.

```
enum OperationStateValues {
  Running
}
```

**Comment by weidongxu-microsoft** [comment]
Another candidate is Type Literals https://github.com/microsoft/cadl/blob/main/docs/tutorial.md#type-literals

```
model BestDog {
  name: "Suki";
  age: 14;
  best: true;
}
```

At present it is done as `ExpandableStringEnum` (to void backward incompatible if it is change to Union. e.g. `sku: "Base" | "Premium"`)
