### ISSUE TITLE
DPG, investigation, CADL feature to M4 schema

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1544]
Check features in https://github.com/microsoft/cadl/blob/main/docs/tutorial.md, and see if current M4 schema supports that. If not, how we might do to augment the M4 (sketch would do).

Note that some feature is only for compiler, e.g. "type alias". One can ignore them.
But some is uncertain, like "interface".

Discuss and have a write-up.

---

Later, we might want to add some CADL file as tests (e.g. see how "interface" would affect emitter).

**Comment by weidongxu-microsoft** [comment]
one may use https://github.com/Azure/autorest.java/tree/cadl-code-model/cadl-extension

**Comment by haolingdong-msft** [comment]
https://microsoftapc-my.sharepoint.com/:x:/g/personal/haolingdong_microsoft_com/EWafV27KftVFl7_dSOUcDb4BcnVqDPKEgwb2IyuWP4E8zA?e=TxHFSJ

**Comment by weidongxu-microsoft** [comment]
Done P0 / P1.
