### ISSUE TITLE
verify m4 format: password type in java

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1554]
Please help check if Java codegen got this problem https://github.com/Azure/autorest.python/issues/1339

**Comment by XiaofeiCao** [comment]
Latest codegen does not report this error on my machine.

We modeled it to String and don't seem to have this problem.

```java
    /**
     * Gets the apiKey property: API Key of the user account.
     *
     * @return the apiKey value.
     */
    String apiKey();
```
