### ISSUE TITLE
Review Default Value for byte ArrayType

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/autorest.java#1570]
if I understand the problem correctly, I think the default  should be `null` so there is a way to represent an empty array and distinguish it from lack of value.

_Originally posted by @lmolkova in https://github.com/Azure/autorest.java/pull/1495#discussion_r898555318_

**Comment by weidongxu-microsoft** [comment]
I assume currently it is `byte[0]`? That likely being from the start of v4 codegen, and I hadn't really thought much about it.

What would be the difference on wire?

**Comment by alzimmermsft** [comment]
Closing as this is now a configuration to use either `null` (default) or `byte[0]`
