### ISSUE TITLE
Javadoc Changes Required for Java 18

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/autorest.java#1572]
Java 18 javadocs introduced a few new requirements for valid javadocs that will need to be supported in code generation for developers who wish to use Java 18 when developing Azure SDKs for Java.

- [ ] Descriptions are always required
  - Can no longer generate javadocs like `/** @return something */`
- [ ] Default constructors, or implicit constructions `new Something()`, are expected to have javadocs
  - Types that previously didn't declare a constructor will now need to declare a no-args constructor with javadocs.

**Comment by weidongxu-microsoft** [comment]
I think I've done a PR to solve the 1st (or most of it)

2nd is news to me. Need some investigate (likely we need a default ctor just for Javadoc, for many Model?).

**Comment by alzimmermsft** [comment]
Yeah, in cases where we had a simple model like

``java
/**
  * Description about the model.
  */
public class SimpleModel {
  /*
    * Description about the property.
    */
  private String property;

  /** @return The property  */
  public String getProperty() {
    return property;
  }

  /**
    * Sets the property
    * 
    * @param property The property
    * @return The updated SimpleModel
    */
    public SimpleModel setProperty(String property) {
      this.property = property;
      return this;
    } 
}
```

it would need to be generated as

``java
/**
  * Description about the model.
  */
public class SimpleModel {
  /*
    * Description about the property.
    */
  private String property;

  /**
    * Creates a new instance of SimpleModel.
    */
  public SimpleModel() {
  }

  /** 
    * Gets the property.
    * 
    * @return The property  
    */
  public String getProperty() {
    return property;
  }

  /**
    * Sets the property.
    * 
    * @param property The property
    * @return The updated SimpleModel
    */
    public SimpleModel setProperty(String property) {
      this.property = property;
      return this;
    } 
}
```

**Comment by alzimmermsft** [comment]
Closing as these have been fixed
