### ISSUE TITLE
Plug CADL ranch into CI 

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#1593]
This should include CI validation and CADL ranch report:

cc @timotheeguerin for help if neeeded

**Comment by weidongxu-microsoft** [comment]
@haolingdong-msft 

See a `cadl-ranch-coverage.json` generated. Please follow up with cadl-range on reporting (if available).

**Comment by haolingdong-msft** [comment]
> @haolingdong-msft
> 
> See a `cadl-ranch-coverage.json` generated. Please follow up with cadl-range on reporting (if available).

sure

**Comment by timotheeguerin** [comment]
I did add support for coverage collection which will create this cadl-ranch-coverage.json. By itself this will not complain about anything. You can use `cadl-ranch check-coverage` command to validate that this coverage file are covering 100% of the cases.

https://github.com/Azure/cadl-ranch/blob/56fa076c030275b69952094515bb5f8eb4984136/docs/using-cadl-ranch.md#validate-and-merge-coverage

For coverage reporting I haven't gotten to it just yet but hopefully will have that soon.

**Comment by weidongxu-microsoft** [comment]
@haolingdong-msft 

For now, you can just print the result of "cadl-ranch check-coverage" in CI.

Though I am not sure whether it requires stopping the server.

**Comment by weidongxu-microsoft** [comment]
current 81%

will do the rest in MQ https://github.com/Azure/autorest.java/issues/1863
