### ISSUE TITLE
[Java DPG]: Add support for tests from CADL test server

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#1606]
This item includes the following tasks:

- [x] Build the test framework to support cadl-ranch  https://github.com/Azure/cadl-ranch
- [x] Implement test cases for different scenarios of CADL input.
- [x] Add new scenarios into https://github.com/Azure/cadl-ranch/tree/main/packages/cadl-ranch-specs/http if needed.

**Comment by weidongxu-microsoft** [comment]
any difference to https://github.com/Azure/autorest.java/issues/1593 ?

**Comment by weidongxu-microsoft** [comment]
mark as resolved as targeting Aug MVP

further new case in cadl-ranch / test in repo will be added in sync with cadl-ranch. but that is not in Aug MVP as cadl-ranch is out of our control.
