### ISSUE TITLE
Support x-ms-skip-url-encoding from CADL

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#1636]
While it won't be called x-ms-skip-url-encoding in CADL, once https://github.com/microsoft/cadl/issues/851 is fixed we need to add that support in the language emitter.

**Comment by weidongxu-microsoft** [comment]
I didn't see either `relativeUrl` or `pathUrl` in Cadl.

Currently I will solve it as `string` to encode, `url` to skip encode.
