### ISSUE TITLE
Global request content type is ignored

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#165]
A custom request content type is defined here: https://github.com/xingwu1/azure-rest-api-specs/blob/3f9a6ad60b345afdbb2677b469cd19549ac4693f/specification/batch/data-plane/Microsoft.Batch/stable/2018-03-01.6.1/BatchService.json#L16

But the generator somehow ignores it and generates
```java
@Headers({ "Content-Type: application/json; charset=utf-8", "x-ms-logging-context: com.microsoft.azure.batch.protocol.Certificates list" }) 
```

**Comment by RikkiGibson** [comment]
Odd. It seems to just reference `RequestContentType` and I can't find any overrides or writes by us to this property.
https://github.com/Azure/autorest.java/blob/master/src/vanilla/Templates/MethodGroupRetrofitTemplate.cshtml#L19

**Comment by jianghaolu** [comment]
@RikkiGibson It reproduces in Python too. Issue reported to the modeler owners.

**Comment by jianghaolu** [comment]
v2/v3 generators deprecated. Feel free to reopen if the same issue exists in the v4 generator.
