### ISSUE TITLE
Cadl, investigate DPG from authoring in swagger

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1655]
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/Language/preview/2022-05-15-preview/analyzetext-authoring.json

Let us see how authoring in swagger generate DPG client (compare to what we had via Cadl). Ignore model for now.

One known issue is the "importx" in Cadl as "import" is reserved keyword in TS. This can be ignored.

There might be difference in LRO. https://github.com/Azure/autorest.java/pull/1652 (especially the signature of DELETE)

**Comment by weidongxu-microsoft** [comment]
try put the output to a repo, it might be needed in review.

**Comment by haolingdong-msft** [comment]
A summary of differences between cadl output and swagger output
**Focus:**
- protocol methods
- method signature
- sync client


**Comparison:**
Interface | Operation | Cadl | Swagger | Difference
-- | -- | -- | -- | --
Projects |   |   |   |  
  | createOrUpdate | public SyncPoller<BinaryData, BinaryData> beginCreateOrUpdate( | public Response<BinaryData> createProjectWithResponse( String   projectName, BinaryData body, RequestOptions requestOptions) |  
  |   | String projectName,   BinaryData optionalProperties, RequestOptions requestOptions) |   |  
  | get | public Response<BinaryData> getWithResponse(String projectName,   RequestOptions requestOptions) | public Response<BinaryData> getWithResponse(String projectName,   RequestOptions requestOptions) |  
  | delete | public SyncPoller<BinaryData, BinaryData> beginDelete(String   projectName, RequestOptions requestOptions) | public SyncPoller<BinaryData, BinaryData> beginDeleteProject(String   projectName, RequestOptions requestOptions) |  
  | list | public PagedIterable<BinaryData> list(RequestOptions   requestOptions) | public PagedIterable<BinaryData> listProjects(RequestOptions   requestOptions) |  
  | export | public SyncPoller<BinaryData, BinaryData> beginExport( | public SyncPoller<BinaryData, BinaryData> beginExport( |  
  |   | String projectName,   String projectFileVersion, RequestOptions requestOptions) | String projectName,   String stringIndexType, RequestOptions requestOptions) |  
  | import | public SyncPoller<BinaryData, BinaryData> beginImportx(String   projectName, RequestOptions requestOptions) | public SyncPoller<BinaryData, BinaryData> beginImportMethod( | 1. Cadl has no request body
  |   |   | String projectName,   BinaryData body, RequestOptions requestOptions) |  
  | train | public SyncPoller<BinaryData, BinaryData> beginTrain( | public SyncPoller<BinaryData, BinaryData> beginTrain( |  
  |   | String projectName,   BinaryData body, RequestOptions requestOptions) | String projectName,   BinaryData body, RequestOptions requestOptions) |  
Deployment | get | public Response<BinaryData> getDeploymentWithResponse( | public Response<BinaryData> getDeploymentWithResponse( |  
  |   | String projectName,   String deploymentName, RequestOptions requestOptions) | String projectName,   String deploymentName, RequestOptions requestOptions) |  
  | deployProject | public SyncPoller<BinaryData, BinaryData> beginDeployProject( | public SyncPoller<BinaryData, BinaryData> beginDeployProject( | 1. Cadl has no request body
  |   | String projectName,   String deploymentName, RequestOptions requestOptions) | String projectName,   String deploymentName, BinaryData body, RequestOptions requestOptions) |  
  | list | public PagedIterable<BinaryData> list(String projectName,   RequestOptions requestOptions) | public PagedIterable<BinaryData> listDeployments(String   projectName, RequestOptions requestOptions) |  
  | swap | public SyncPoller<BinaryData, BinaryData> beginSwapDeployments( | public SyncPoller<BinaryData, BinaryData> beginSwapDeployments( |  
  |   | String projectName,   BinaryData body, RequestOptions requestOptions) | String projectName,   BinaryData body, RequestOptions requestOptions) |  
Jobs | getDeploymentStatus | public Response<BinaryData> getDeploymentStatusWithResponse( | public Response<BinaryData> getDeploymentStatusWithResponse( |  
  |   | String projectName,   String deploymentName, String jobId, RequestOptions requestOptions) | String projectName,   String deploymentName, String jobId, RequestOptions requestOptions) |  
  | getSwapDeploymentsStatus | public Response<BinaryData> getSwapDeploymentsStatusWithResponse( | public Response<BinaryData> getSwapDeploymentsStatusWithResponse( |  
  |   | String projectName,   String deploymentName, String jobId, RequestOptions requestOptions) | String projectName,   String jobId, RequestOptions requestOptions) |  
Global | getSupportedLanguages | public PagedIterable<BinaryData>   getSupportedLanguages(RequestOptions requestOptions) | public PagedIterable<BinaryData>   getSupportedLanguages(RequestOptions requestOptions) |  
  | listTrainingConfigVersions | public PagedIterable<BinaryData>   listTrainingConfigVersions(RequestOptions requestOptions) | public PagedIterable<BinaryData> listTrainingConfigVersions(String   projectKind, RequestOptions requestOptions) | Cadl miss projectKind

**Comment by haolingdong-msft** [comment]
API view for swagger output: https://apiview.dev/Assemblies/Review/001f377cde784491a33a9e0ec55610ce
