### ISSUE TITLE
Cadl, support "title" in java.json

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1656]
ref to https://github.com/Azure/autorest.java/pull/1651

set it via `CadlPlugin.Options` to `SETTINGS_MAP` `title`.

**Comment by weidongxu-microsoft** [comment]
reason, authoring had a bad `ServiceTitle` https://github.com/Azure/cadl-azure/blob/main/packages/cadl-samples/data-plane/language/authoring/authoring.cadl#L20

**Comment by weidongxu-microsoft** [comment]
no need to add test in repo.

**Comment by XiaofeiCao** [comment]
Maybe we can reuse the existing `service-name` instead of inventing a new `title`? They seem to do the same trick.

**Comment by weidongxu-microsoft** [comment]
You can use `service-name`. But same you need to follow this to put it into `SETTINGS_MAP`.

**Comment by XiaofeiCao** [comment]
OK, guess we can have `title` in `java.json` and map it to `service-name` in `JavaSettings`?

**Comment by weidongxu-microsoft** [comment]
I see. `title` is set to code-model yaml by m4, so it is not need to be loaded from JavaSettings.

OK. let us try `service-name` first.
