### ISSUE TITLE
Generate subset of models/operations based on the convenience methods specified in a Cadl file

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#1670]
Pending https://github.com/Azure/cadl-azure/issues/1839
We should generate a subset of models/operations based on the convenience methods specified in a Cadl file.

While we are still discussing the CADL-DPG package,  let's use

@OpenAPI.extension("x-ms-convenient-api", true)
op foo(): {};

As a shortcut to unblock this work. Please note, the JSON/YAML that comes out of the emitter must be designed correctly from the start.

**Comment by weidongxu-microsoft** [comment]
user need to add `@cadl-lang/openapi` to their cadl project.
