### ISSUE TITLE
DPG, support tests/samples generation

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/autorest.java#1682]
Currently we only generate a sample template. We need to generate all samples and tests using the example data.

Epic: https://github.com/Azure/cadl-azure/issues/1946

**Comment by weidongxu-microsoft** [comment]
depends on https://github.com/Azure/typespec-azure/issues/2715

**Comment by weidongxu-microsoft** [comment]
follow up issue https://github.com/Azure/autorest.java/issues/2068
