### ISSUE TITLE
LRO basics from CADL

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#1690]
First level of support for LRO in CADL, is to consider the presence of `@Azure.Core.pollingOperation` as a boolean switch to generate LRO code, like `x-ms-long-running-operation: true` was doing in Swagger:

```
  @Azure.Core.pollingOperation(Authoring.createProjectStatusMonitor)
  createProject is Azure.Core.LongRunningResourceCreateWithServiceProvidedName<Project>;
```
([full example](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAY2FkbC1sYW5nL3ZlcnNpb25pbmciOwrJIGF6dXJlLXRvb2xzL8UsxhFjb3JlIjsKCkBzZXJ2aWNlVGl0bGUoIlRleHQgYXV0aG9yxEgpCi8vQFbJWC7HY2VkKFPGN8cccykKbmFtZXNwYWNlIMREQchDOwoKZW51bSDPMCB7CiAgdjE6ICIyMDIxLTDEAyIsxBQyxhQyLTA5LTEyIiwKfQoKQENhZGwuUmVzdC5yZXNvdXJjZSgicHJvamVjdHMiKQptb2RlbCBQxhHFW0BrZXnEB3Zpc2liaWxpdHkoInJlYWQiKQogIGlkOiBzdOYAniAgZGVzY3JpcHRpb24%2FyhgKICDkANLLEn0KCmludGVyZuQA5OkA4MVuY3JlYXRl5wCAU3RhdHVzTW9uaXRvciBpcyBDdXN0b21Db3JlLlBvbGxpbmdPcGVyYcRxPMc0PsVxQEHkAZsuxSpwzyooyXIu2m7kAN3NHsR%2Fy1VMb25nUnVu5AHLUucBSEPFL1dpdGjnAaJQcm92aWRlZE5hbWXuAJ9kZWxl2FrIT0TFJMs4ICBsaXN0xxBz1zZMaXN0zTRkZXBsb3nea0Fj5QFCCiAgIOgB%2B%2BQCQSDlAZLEAXNsb3TkAMbsAe0gIH3GJccyCiAgxXFnZegApNduUmVhZOsAo30K6wLx6gHhxXzrAq5wYXJlbnTIRChU5AGh9QLNb%2BgB6OQCzyAg5gLR6QH95gHlyEc8VD7vAKVGb3VuZMY%2FLs815wEO5wMQICDJaUntAwV95QKA5QCaSHR0cC5yb3V08gCXb3Ag8QLCVOYA%2FvAAk%2B0BOPkAycc85QFR))

**Comment by weidongxu-microsoft** [comment]
ref https://github.com/Azure/autorest.java/issues/1684

**Comment by weidongxu-microsoft** [comment]
@lmazuel 

Java might additional like to have the type information on polling result, as Java API response is of `PollerFlux<IntermediateModel, FinalResultModel>`.

Wondering whether there is actually
```ts
createProjectStatusMonitor is CustomCore.PollingOperation<ProjectMonitorModel>;
```
that the response of monitor API is the `ProjectMonitorModel`, instead of the `Project` as final result.

---

Also SDK need to hide "createProjectStatusMonitor" operation as it is included in polling.

**Comment by weidongxu-microsoft** [comment]
basically this task is done as DPG 1.0 fashion.

the remaining question is whether SDK should do special handling for the status monitor API.

**Comment by weidongxu-microsoft** [comment]
autorest https://github.com/Azure/azure-rest-api-specs/pull/20808/files#diff-1848b2ecf27a48dfecaaefb41cb4cf78b172f44b97d66911337f3a8442b571ad

**Comment by lmazuel** [comment]
I believe we should consider the status api as any method, and we may add a decorator to say "this method private only please" ar something like that. Thoughts?

**Comment by weidongxu-microsoft** [comment]
> I believe we should consider the status api as any method, and we may add a decorator to say "this method private only please" ar something like that. Thoughts?

Decorator will surely do!

We keep all API at same state, till we got feedback from service or arch that something needs special handling.

**Comment by weidongxu-microsoft** [comment]
completed via https://github.com/Azure/autorest.java/pull/1715
