### ISSUE TITLE
  found: no arguments   reason: actual and formal argument lists differ in length

### ISSUE THREAD

**Issue by halkeye** [Azure/autorest.java#1707]
@halkeye

What's kind of SDK are you generating?

Please remove "--generate-tests" option. The automatically generated tests is still experimental feature (that we are testing in mgmt-plane).

PS: If you can paste the class of `AppsListRegionsResponse`, it will help me fix that test issue (but this is not related to the Headers issue here).

_Originally posted by @weidongxu-microsoft in https://github.com/Azure/autorest.java/issues/1706#issuecomment-1248842579_

**Comment by halkeye** [comment]
> What's kind of SDK are you generating?

Digital ocean api. I'm afraid I don't know what the question means though.
the spec file is https://api-engineering.nyc3.digitaloceanspaces.com/spec-ci/DigitalOcean-public.v2.yaml

I stole the client_gen_config.md from work, so i'll see if i'm allowed to share publically it in a bug issue for the future. (i'll gladly email you the configs if it helps builds a more robust tool)

> The automatically generated tests is still experimental feature (that we are testing in mgmt-plane).

I can do that. I just wanted to find something to confirm things compiled right.

> PS: If you can paste the class of `AppsListRegionsResponse`, it will help me fix that test issue (but this is not related to the Headers issue here).

```
package com.digitalocean.api.models;

import com.azure.core.http.HttpHeaders;
import com.azure.core.http.HttpRequest;
import com.azure.core.http.rest.ResponseBase;

/** Contains all response data for the listRegions operation. */
public final class AppsListRegionsResponse extends ResponseBase<AppsListRegionsHeaders, Object> {
    /**
     * Creates an instance of AppsListRegionsResponse.
     *
     * @param request the request which resulted in this AppsListRegionsResponse.
     * @param statusCode the status code of the HTTP response.
     * @param rawHeaders the raw headers of the HTTP response.
     * @param value the deserialized value of the HTTP response.
     * @param headers the deserialized headers of the HTTP response.
     */
    public AppsListRegionsResponse(
            HttpRequest request, int statusCode, HttpHeaders rawHeaders, Object value, AppsListRegionsHeaders headers) {
        super(request, statusCode, rawHeaders, value, headers);
    }

    /**
     * Gets the deserialized response body.
     *
     * @return the deserialized response body.
     */
    @Override
    public Object getValue() {
        return super.getValue();
    }
}
```

**Comment by weidongxu-microsoft** [comment]
@halkeye

Thanks. I should skip this Client Response model of `AppsListRegionsResponse`. There is no JSON serialized/de-serialized about this class at all, and hence needs no such test generated for it.

Let me know if other things work OK or not.

**Comment by halkeye** [comment]
Thank you for all your rapid responses with this. I probably won't have a chance to really test this till the weekend. Its easy to run the cli in the background and report errors. I'll report back as quickly as possible though. I'm really excited about this.

**Comment by halkeye** [comment]
#1709 helps!

Was able to get a test script running
```
        GeneratedClient client = new GeneratedClientBuilder()
            .credential(tokenRequestContext -> {
                return Mono.fromCallable(() -> new AccessToken(System.getenv("DIGITALOCEAN_TOKEN"), OffsetDateTime.MAX));
            })
            .buildClient();
        Object all_regions = client.getRegions().listAsync(25, 1).block();
        Assert.assertEquals("something", ((HashMap) all_regions).get("regions").toString());
```
