### ISSUE TITLE
mgmt, generate-test skip JSON that fails CredScan in CI

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#1711]
https://github.com/Azure/azure-sdk-for-java/pull/31007#discussion_r973847738

CI failure: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1857734&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=7eee3a58-6120-518b-7fcb-7e943712aa81

**Comment by XiaofeiCao** [comment]
Suppression doesn't work, as it doesn't support wildcards.
https://secdevtools.azurewebsites.net/helpcredscan.html

**Comment by weidongxu-microsoft** [comment]
This one is `apiKey`.

Do you have other name that get flagged by CredScan?

**Comment by weidongxu-microsoft** [comment]
another `storageAccountPrimaryKey`.

**Comment by XiaofeiCao** [comment]
From our `CredScanSuppression.json`, I got `OAuth2ClientCredential`.

**Comment by weidongxu-microsoft** [comment]
> From our `CredScanSuppression.json`, I got `OAuth2ClientCredential`.

This is different thing. It is code from swagger, not tests. So it has to get to suppression else that RP just not correct.

**Comment by XiaofeiCao** [comment]
Found the source code and a seemingly exhaustive config list:
https://msazure.visualstudio.com/One/_git/e4f88693-d8b9-42a6-bd57-99bce573e20c?path=/src/CredScan.MCEScanner/Configuration/config.xml

I think we can use the regex that contains `CSCAN-AZURE0120_Code` (I assume it's used for scanning code)?
![image](https://user-images.githubusercontent.com/92354331/191160777-ebef7750-5b13-4477-85dd-b7b4773560e6.png)

**Comment by XiaofeiCao** [comment]
Not sure if this is in use...
` <Regex id="Regex_Ranker_CSCAN-AZURE0130_1dd3f4ad-9d76-4b5f-9f89-20ca2c45184f_339559_CEP2.0">(?i)(SharedAccess(Policy)?|SAS|Primary|Secondary)Key\W|SharedAccessSignature\W|SharedKey\W</Regex>`

**Comment by weidongxu-microsoft** [comment]
That one is likely too complicated.

Maybe we just skip either the test or the property if it has property contains "key" or "credential".

**Comment by weidongxu-microsoft** [comment]
May need to handle sample as well.
https://github.com/Azure/azure-sdk-for-java/pull/31685

Can replace it with "fakeTokenPlaceholder"
