### ISSUE TITLE
Lingering issues in Javadocs

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.java#172]
While inspecting a gencode diff for Storage I found this change:

```
-     * @return the {@link Completable} object if successful.
+     * @return a Single which performs the network request upon subscription.
Completable putBlockListAsync(...);
```

Will need to revisit this and make the Javadoc display an accurate return type. Ideally we could have `@link` tags for the raw types-- something like `Single<BlockList>` for instance is not allowed.

This is also an opportunity to go in and ensure we don't put pointless Javadocs on the private fields of models, and instead put the docs on the public getters and setters.

**Comment by jianghaolu** [comment]
No longer returning these types in v4 generator.
