### ISSUE TITLE
Cadl, emitter with Custom configuration options

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1737]
https://microsoft.github.io/cadl/docs/extending-cadl/emitters-basics/#custom-configuration-options

https://github.com/Azure/cadl-azure/issues/1751

epic: https://github.com/Azure/cadl-azure/issues/1947

**Comment by XiaofeiCao** [comment]
I'm considering adding a `CadlSettings` property to `JavaSettings` for cadl-specific settings like `output-folder`, `generate-convenience-methods`. The rest of the settings go directly to `CadlPlugin`'s `SETTINGS_MAP`.

Will draft a PR for discussion.

**Comment by weidongxu-microsoft** [comment]
For now, we may only want to have `output-folder`.

`generate-convenience-methods` is only for test. I won't expect user to set that.
