### ISSUE TITLE
Support for swagger byte format

### ISSUE THREAD

**Issue by rickle-msft** [Azure/autorest.java#174]
We’d like to request support for returning some sort of bytes object (ByteBuffer or byte[]) from the generated client in cases where the swagger string has a format “byte”. The use case is when our service returns the MD5 or something similar. Because most languages seem to yield bytes when producing an MD5 hash, it would be best for our users to be able to directly compare what they compute and what is returned without having to do any extra type conversions.

**Comment by RikkiGibson** [comment]
I think we already base64 decode strings under some circumstances. We'll want to investigate on our end why a "byte" formatted header doesn't translate as a String that gets base64 decoded to byte[] in the generated class.

**Comment by rickle-msft** [comment]
I think I was actually mistaken about this. My bad :)
