### ISSUE TITLE
Client, Java warning on .flatMapMany(Response::getValue) for StreamResponse

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1755]
Warning

```
##[warning] /Users/runner/work/1/s/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/implementation/CloudServiceRoleInstancesClientImpl.java(1974,26): warning :  /Users/runner/work/1/s/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/implementation/CloudServiceRoleInstancesClientImpl.java:[1974,26] found raw type: com.azure.core.http.rest.Response
[WARNING] /Users/runner/work/1/s/sdk/resourcemanager/azure-resourcemanager-compute/src/main/java/com/azure/resourcemanager/compute/implementation/CloudServiceRoleInstancesClientImpl.java:[1974,26] found raw type: com.azure.core.http.rest.Response
```

on code

```java
    @ServiceMethod(returns = ReturnType.SINGLE)
    public Flux<ByteBuffer> getRemoteDesktopFileAsync(
        String roleInstanceName, String resourceGroupName, String cloudServiceName) {
        return getRemoteDesktopFileWithResponseAsync(roleInstanceName, resourceGroupName, cloudServiceName)
            .flatMapMany(Response::getValue);
    }

    public Mono<StreamResponse> getRemoteDesktopFileWithResponseAsync(
        String roleInstanceName, String resourceGroupName, String cloudServiceName) {
```

Changing `.flatMapMany(Response::getValue)` to `.flatMapMany(StreamResponse::getValue)` fixes it.

**Comment by weidongxu-microsoft** [comment]
source seems here https://github.com/Azure/autorest.java/blob/c98b0d8/javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java#L780

Would changing it to `.flatMapMany(res -> res.getValue())` help? @alzimmermsft

**Comment by alzimmermsft** [comment]
> source seems here https://github.com/Azure/autorest.java/blob/c98b0d8/javagen/src/main/java/com/azure/autorest/template/ClientMethodTemplate.java#L780
> 
> Would changing it to `.flatMapMany(res -> res.getValue())` help? @alzimmermsft
> 
> One small problem of e.g. `res` in lambda is that it might conflict with name from parameters. so if choose this approach I probably going to use a longer name.

Yeah, changing this to `.flatMapMany(rest -> res.getValue())` would resolve this warning. We could call it something like `dataReponse` which explains what it is (`Flux<ByteBuffer>`) while also lowering the chance of a naming conflict.
