### ISSUE TITLE
x-ms-skip-url-encoding incorrectly generated by swagger

### ISSUE THREAD

**Issue by khmic5** [Azure/autorest.java#1759]
x-ms-skip-url-encoding is set to false in the swagger https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/maps/data-plane/DEM/preview/1.0/elevation.json but the generated code from mvn install && autorest --java --use:@autorest/java@4.0.62 generates encoded = true for getDataForPolyline

**Comment by weidongxu-microsoft** [comment]
try just remove the "x-ms-skip-url-encoding: false"?

**Comment by alzimmermsft** [comment]
I've used the same Swagger README to generate this using the latest version of `autorest/java` and don't see this generated incorrectly. Appears this may have been implicitly fixed at some point since `autorest/java@4.0.62`.
