### ISSUE TITLE
Update Java DPG GetStarted Guide to support CADL+DPG

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#1795]
Please update https://aka.ms/azsdk/dpcodegen/java to include the process for CADL+DPG

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/azure-sdk-for-java/wiki/Protocol-Methods-Quickstart-with-AutoRest#use-cadl

**Comment by weidongxu-microsoft** [comment]
Using a new page as recommended https://github.com/Azure/azure-sdk-for-java/wiki/Cadl-Java-Quickstart

We can review and improve it, before switching the aka link to it.

Changes are mostly in https://github.com/Azure/azure-sdk-for-java/wiki/Cadl-Java-Quickstart#generate-sdk

@haolingdong-msft @XiaofeiCao @dw511214992
