### ISSUE TITLE
Generate Java client from Autonomous Development Platform Cadl API description

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#1800]
This issue tracks validating that a DPG generator can generate the ADP client, models, convinience APIs and protocol methods from https://github.com/Azure/azure-rest-api-specs-pr/pull/9236/files, to achieve parity with what DPG v1.0 can generate from ADP OpenAPI description from the same PR

Inputs:
https://github.com/Azure/azure-rest-api-specs-pr/pull/9236/files

**Comment by weidongxu-microsoft** [comment]
Generated Java with unreleased codegen (model/convenienceAPI via dev option).
[https://github.com/Azure/azure-rest-api-specs-pr/tree/adp-java-sdk/specification/adp/data-plane/cadl](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs-pr%2Ftree%2Fadp-java-sdk%2Fspecification%2Fadp%2Fdata-plane%2Fcadl&data=05%7C01%7CWeidong.Xu%40microsoft.com%7C72ce90b2882b40927fef08dab26bd35a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638018473446972021%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F%2FBIUXzdCgKsp530kG5fNcc0ZoPvtlK62wKUGV19ynw%3D&reserved=0)

Build pass. Didn’t go any deeper.


There is pretty strange configure in Cadl

    #suppress "@azure-tools/cadl-azure-core/use-standard-operations" "ADP data-plane API uses custom LRO response template the LRO actions."
    @doc("Initiates the process of generating SAS signed URIs for uploading special files for the discovery.")
    @example(
      "./examples/public/ingestion/discovery/Discovery_GenerateSpecialFilesUploadInfo.json",
      "Initiates the process of generating SAS signed URIs for uploading special files for the discovery."
    )
    @extension("x-ms-long-running-operation", true)
    @asyncOperationOptions("location")
    @pollingOperation(ADP.Common.Operations.LongRunningOperationStatusLocation)
    generateSpecialFilesUploadInfo is CustomLongRunningResourceAction<
      Discovery,
      {},
      DiscoveryLroResponse
    >;

“pollingOperation” supposed to link to an operation, but they link to a model. Had to put an extra guard in codegen.

**Comment by weidongxu-microsoft** [comment]
One issue is following op

```ts
    createOrReplace is CustomResourceCreateOrReplace<
      Discovery,
      DiscoveryCreationParameters
    >;

@createsOrReplacesResource(TResource)
op CustomResourceCreateOrReplace<
  TResource,
  TResourceCreateParams
> is Foundations.ResourceOperation<
  TResource,
  Foundations.ResourceCreateOrReplaceModel<TResource> & TResourceCreateParams,
  CustomResourceCreatedOrOkResponse<TResource>
>;
```

It should use round trip model, but not so (maybe because of the "&" in template).

**Comment by haolingdong-msft** [comment]
The reason why it's not round-trip model is: It reuses the same model `Discovery` and add `@visibility("create")` for parameters that need to be used in create operation in `Discovery` and name the model `DiscoveryCreationParameters`.  Then make `DiscoveryCreationParameters` as `body` of the operation. So `DiscoveryCreationParameters` becomes body. So the request body is `DiscoveryCreationParameters` type and the response body is `Discovery` type. 

``` 
  @doc("Discovery resource creation parameters.")
  @friendlyName("DiscoveryCreationParameters")
  @withVisibility("create")
  @withoutOmittedProperties("discoveryId")
  model DiscoveryCreationParameters {
    ...Discovery;
  }
```
```
  @doc("A wrapper for optional parameter in the body. The intent of model is to add description to 'body'")
  model CustomBodyWrapper<T> {
    @body
    body?: T;
  }
```
```
@doc("Creates a new ingestion discovery instance.")
    createOrReplace is CustomResourceCreateOrReplace<
      Discovery,
      CustomBodyWrapper<DiscoveryCreationParameters>
    >;
```

**Comment by haolingdong-msft** [comment]
API view with only protocol methods: https://apiview.dev/Assemblies/Review/3b77bee6b3b940ad9c85df75cee51df1?revisionId=fd8d08276a2c46c29a1ca781aecc6e85&doc=False
API view with convenience method and models: https://apiview.dev/Assemblies/Review/3b77bee6b3b940ad9c85df75cee51df1?revisionId=99b078ce29204096b47a071265e8e7a1&doc=False

**Comment by weidongxu-microsoft** [comment]
@haolingdong-msft 

Could you list what could be the problem if we release ADP as it is?

**Comment by weidongxu-microsoft** [comment]
If you have question on Cadl definition, comment on their Cadl PR immediately.

**Comment by haolingdong-msft** [comment]
Regen based on new codegen and using single client. Below is API version:
Protocol method only:
https://apiview.dev/Assemblies/Review/3b77bee6b3b940ad9c85df75cee51df1?revisionId=6ed6963bdb8b4408aeabc7c4deb97e92&doc=False
Adding models and convenience methods:
https://apiview.dev/Assemblies/Review/3b77bee6b3b940ad9c85df75cee51df1?revisionId=4c5ccb0775ff416db7a2f86abe325fd3&doc=False

**Comment by haolingdong-msft** [comment]
adp repo: https://github.com/haolingdong-msft/adp-experiment

**Comment by haolingdong-msft** [comment]
Here is a potential issue for LRO:
cadl defnition: 
```javascript
  #suppress "@azure-tools/cadl-azure-core/use-standard-operations" "ADP data-plane API uses custom LRO response template the LRO actions."
  @doc("Initiates the process of completing the discovery and creating the upload file grouping manifest files.")
  @extension("x-ms-long-running-operation", true)
  @asyncOperationOptions("location")
  @pollingOperation(LongRunningOperations.getStatus)
  complete is CustomLongRunningResourceAction<
    Discovery,
    {},
    {},
    DiscoveryLroResponse
  >;
```
java code:
```java
    @Generated
    @ServiceMethod(returns = ReturnType.LONG_RUNNING_OPERATION)
    public SyncPoller<LongRunningOperation, Object> beginComplete(String discoveryId) {
        // Generated convenience method for beginCompleteWithModel
        return client.beginComplete(discoveryId).getSyncPoller();
    }
```
return type is `SyncPoller<LongRunningOperation, Object>`, `Object` is used as final return type.  
Our current LRO logic is:
1. if `@pollingOperation` is defined, we will use it's operation's return type as polling type, if it's not defined, we will not provide convenience method.
2. if `@pollingOperation` is defined and `@finalOperation` is defined, we will use `@finalOperation`'s return type as final type. If it's not defined, we will use all success (2xx) return types' parent type as response, in the cadl definition, the success responses are: `DiscoveryLroResponse` (with status code 202), `Discovery` (with status code 200). The parent class of the two is `Object`. So it becomes `Object`. This is propably not a correct behavior.


However, in this case, we can add `@finalOperation` as a workaround.

```javascript
  #suppress "@azure-tools/cadl-azure-core/use-standard-operations" "ADP data-plane API uses custom LRO response template the LRO actions."
  @doc("Initiates the process of completing the discovery and creating the upload file grouping manifest files.")
  @extension("x-ms-long-running-operation", true)
  @asyncOperationOptions("location")
  @pollingOperation(LongRunningOperations.getStatus)
  @finalOperation(DiscoveryOperations.get)
  complete is CustomLongRunningResourceAction<
    Discovery,
    {},
    {},
    DiscoveryLroResponse
  >;
```
The output will be:
```java
    @Generated
    @ServiceMethod(returns = ReturnType.LONG_RUNNING_OPERATION)
    public SyncPoller<LongRunningOperation, Discovery> beginComplete(String discoveryId, String operationId) {
        // Generated convenience method for beginCompleteWithModel
        return client.beginComplete(discoveryId, operationId).getSyncPoller();
    }
```

**Comment by weidongxu-microsoft** [comment]
https://apiview.dev/Assemblies/Review/3b77bee6b3b940ad9c85df75cee51df1

**Comment by haolingdong-msft** [comment]
Issue in investigation:
convenience method is not generated for LRO when using the latest service team's client.cadl

reason:
operation.cadl
```js
  #suppress "@azure-tools/cadl-azure-core/use-standard-operations" "ADP data-plane API uses custom LRO response template the LRO actions."
  @doc("Initiates the process of completing the discovery and creating the upload file grouping manifest files.")
  @extension("x-ms-long-running-operation", true)
  @asyncOperationOptions("location")
+  @pollingOperation(LongRunningOperationStatus)
  complete is CustomLongRunningResourceAction<
    Discovery,
    {},
    {},
    DiscoveryLroResponse
  >;


@tag("Long Running Operation")
op LongRunningOperationStatus is Adp.Shared.LongRunningOperations.getStatus;
```

client.cadl
```js
  interface LongRunningOperation {
    @convenienceAPI
    getLongRunning is Adp.DataManagement.LongRunningOperationStatus;
  }
```

In `operationCache`, the operation name is `getLongRunning`, but in `@pollingOperation` refers to `LongRunningOperationStatus`, the two name can't match, we can't [get](https://github.com/Azure/autorest.java/blob/main/cadl-extension/src/code-model-builder.ts#L483) the operation from cache, when polling operation is not found, we won't generate convenience method for the long running operation.

Ref:
code-model.yaml
```yaml
      - &ref_230
        language:
          default:
            name: completeDiscovery
            description: >-
              Initiates the process of completing the discovery and creating the
              upload file grouping manifest files.
        protocol: {}
        operationId: completeDiscovery
        apiVersions:
          - version: 2022-11-30-preview
        convenienceApi:
          language:
            default:
              name: completeDiscovery
              description: ''
          protocol: {}
        requests:
          - language:
              default:
                name: ''
                description: ''
            protocol:
              http:
                path: /discoveries/{discoveryId}:completeDiscovery
                method: post
                uri: '{endpoint}'
        parameters:
          - *ref_88
          - &ref_95
            language:
              default:
                name: discoveryId
                description: The discovery identifier.
                serializedName: discoveryId
            protocol:
              http:
                in: path
            schema: *ref_1
            implementation: Method
            required: true
            nullable: false
          - *ref_89
          - &ref_96
            language:
              default:
                name: operationId
                description: >-
                  The long running operation identifier. Operation-Id should be
                  valid UUID string.
                serializedName: operation-id
            protocol:
              http:
                in: header
            schema: *ref_1
            implementation: Method
            required: false
            nullable: false
          - language:
              default:
                name: accept
                description: Accept header
                serializedName: accept
            protocol:
              http:
                in: header
            schema: *ref_84
            implementation: Method
            origin: modelerfour:synthesized/accept
            required: true
        signatureParameters:
          - *ref_95
          - *ref_96
        responses:
          - language:
              default:
                name: completeDiscoveryResponse
                description: The request has succeeded.
            protocol:
              http:
                statusCodes:
                  - '200'
                headers: []
                mediaTypes:
                  - application/json
            schema: *ref_93
          - language:
              default:
                name: completeDiscoveryResponse
                description: >-
                  The request has been accepted for processing, but processing
                  has not yet completed.
            protocol:
              http:
                statusCodes:
                  - '202'
                headers:
                  - header: Operation-Location
                    schema: *ref_97
                    language:
                      default:
                        name: operationLocation
                        description: The location for monitoring the operation state.
                mediaTypes:
                  - application/json
            schema: *ref_98
        exceptions:
          - language:
              default:
                name: completeDiscoveryResponse
                description: An unexpected error response
            protocol:
              http:
                statusCodes:
                  - default
                headers:
                  - header: x-ms-error-code
                    schema: *ref_1
                    language:
                      default:
                        name: xMsErrorCode
                        description: Error code for specific error that occurred.
                mediaTypes:
                  - application/json
            schema: *ref_87
        operationLinks:
+          polling: {}
        extensions:
          x-ms-long-running-operation: true
```

**Comment by weidongxu-microsoft** [comment]
The `operationCache` is an implementation detail. Please see if you can fix/improve that.

**Comment by haolingdong-msft** [comment]
rest api review issue: https://github.com/Azure/azure-rest-api-specs-pr/issues/7483

**Comment by haolingdong-msft** [comment]
Latest API view: https://apiview.dev/Assemblies/Review/3b77bee6b3b940ad9c85df75cee51df1

**Comment by haolingdong-msft** [comment]
regen based on cadl compiler 0.38.0.
PR: https://github.com/Azure/azure-sdk-for-java-pr/pull/1388, API View: https://apiview.dev/Assemblies/Review/3b77bee6b3b940ad9c85df75cee51df1

**Comment by haolingdong-msft** [comment]
Close for now as mentioned in email that ADP is cancelled. Feel free to reopen if futrhur work needs to be done.
