### ISSUE TITLE
[Feature Req]Support sample generation for DPG generated data plane SDK

### ISSUE THREAD

**Issue by xboxeer** [Azure/autorest.java#1805]
**Describe the issue or request**
Support sample generation for DPG generated data plane SDK

**Describe your ideas for solutions**
Support sample generation for DPG generated data plane SDK

**Comment by weidongxu-microsoft** [comment]
Is it DPG or Cadl?

DPG has it as swagger has the jsons https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/devcenter/azure-developer-devcenter/src/samples/java/com/azure/developer/devcenter

Cadl does not have it as Cadl only supports it via cadl-autorest, which is not what we are going to use.

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/autorest.java/issues/1682

**Comment by weidongxu-microsoft** [comment]
pending on Cadl

**Comment by weidongxu-microsoft** [comment]
track https://github.com/Azure/autorest.java/issues/1682
