### ISSUE TITLE
Generate Java client from Anomaly Detector (aka MVAD) Cadl API description

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#1831]
This issue tracks validating that a DPG generator can generate the MVAD client, models, convinience APIs and protocol methods from https://github.com/Azure/azure-rest-api-specs/tree/feature/anomaly-detector-cadl/specification/cognitiveservices/data-plane/AnomalyDetector/stable/v1.1/cadl, to achieve parity with what DPG v1.0 can generate from MVAD OpenAPI description.

Inputs:
https://github.com/Azure/azure-rest-api-specs/tree/feature/anomaly-detector-cadl/specification/cognitiveservices/data-plane/AnomalyDetector/stable/v1.1/cadl

**Comment by weidongxu-microsoft** [comment]
https://apiview.dev/Assemblies/Review/24649c39b21e46768be4fd201a232e8a#com.azure.ai.anomalydetector.AnomalyDetectorServiceVersion

detail in email

**Comment by weidongxu-microsoft** [comment]
diff of Cadl and Swagger
https://apiview.dev/Assemblies/Review/077220369a574080afd4df85bd0ed871?diffRevisionId=05056228c2224452b71554d109e908b9&diffOnly=False&revisionId=9b17e22bae854f3689f18da80fc0dbac&doc=False
(one API name change)

Cadl with devoptions to generate all convenience APIs and models
https://apiview.dev/Assemblies/Review/077220369a574080afd4df85bd0ed871?diffRevisionId=9b17e22bae854f3689f18da80fc0dbac&diffOnly=False&revisionId=e73b22cce945436c898ff9dc4fc5f501&doc=False

**Comment by weidongxu-microsoft** [comment]
MVAD PR https://github.com/Azure/azure-sdk-for-java/pull/32066, their apiview within.

**Comment by weidongxu-microsoft** [comment]
PR from cadl https://github.com/Azure/azure-sdk-for-java/pull/32182
