### ISSUE TITLE
cadl, use "isApiVersion" method

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1859]
https://github.com/markcowl/cadl-azure/blob/1f58b502b1fa7dce4956c6afcb7f83aa9363bc21/packages/cadl-dpg/CHANGELOG.md

Here is 2 places in current emitter which checks "ApiVersion" in host and "api-version" in query. (both should have "TODO" in comment above)

Also add a test with "ApiVersion" in host. E.g. https://github.com/Azure/azure-rest-api-specs/blob/d102b547f56159b451bc66362f7fb8f4fb5e64fc/specification/cognitiveservices/data-plane/AnomalyDetector/stable/v1.1/cadl/main.cadl#L23-L25

---

You can see if "getDefaultApiVersion" can be used as well.

**Comment by haolingdong-msft** [comment]
fixed in https://github.com/Azure/autorest.java/pull/1934, pending on https://github.com/Azure/cadl-azure/pull/2520 to be release in cadl-dpg stable version, and update the remaining part.

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/autorest.java/pull/1965/commits/cc5a5516b60d36b7a44103d8b87b2af40a1f2808
