### ISSUE TITLE
cadl, keep updated with cadl-ranch updates

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1863]

**Comment by haolingdong-msft** [comment]
Share from Laurent: https://teams.microsoft.com/l/message/19:16f8f1ed70d044139be153707bdaee0e@thread.skype/1670954749275?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1670954749275&teamName=Azure%20SDK&channelName=Cadl%20Engineering&createdTime=1670954749275&allowXTenantAccess=false
 
Cadl Ranch was updated to use a storage account in the prod subscription this means you need to update your pipeline step to upload to teh right place
1.	Update the service connnection to use "Cadl Ranch Storage" 
2.	azureSubscription: "Cadl Ranch Storage"
2. Update the storageAccountName flag to --storageAccountName azuresdkcadlranch

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/autorest.java/issues/2057
