### ISSUE TITLE
Support isProtocol/isConvenient

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#1893]
See https://github.com/Azure/cadl-azure/issues/2362 for details

**Comment by weidongxu-microsoft** [comment]
isConvenient is done.
Pending for isProtocol.

@haolingdong-msft 
Let's have a design first.
We cannot remove the protocol API, because convenience API calls it.
Maybe we can make these package private.

**Comment by haolingdong-msft** [comment]
Design here: https://github.com/haolingdong-msft/working-docs/blob/main/cadl/support-isProtocol.md
Feel free to add any comment and suggestions.

**Comment by weidongxu-microsoft** [comment]
So far looks good to me.

Not sure the case that both is false, is it intended for an error, or intended as if the operation does not exist (but continue)?

**Comment by haolingdong-msft** [comment]
Hi @lmazuel, would like to confirm on an cornor case, if the user sets both protocolApi and convenientApi to false like below, what will be the expected behavior, do we expect emitter to throw error or assume the operation do not exist(but continue)?
```typescript
  @doc("When set protocol false and convenient false, this will throw error in emitter")
  @route("errorSetting")
  @get
  @convenientAPI(false)
  @protocolAPI(false)
  op errorSetting(@body body: Resource): Resource;
```

**Comment by srnagar** [comment]
@haolingdong-msft this should be `true`  for both `@convenientAPI` and `@protocolAPI`.
```js
  @doc("Setting protocol true and convenient true, both convenient and protocol methods will be generated")
  @route("bothConvenientAndProtocol")
  @get
  @convenientAPI(false) // update this
  @protocolAPI(false) // update this
  op bothConvenientAndProtocol(@body body: Resource): Resource;
```


Also, for the `errorSetting` method where both are false, we should still generate this method as package-private (not public) just to ensure the cadl definition looks good and all models are generated correctly. Note: both models and the client method should be package-private.


Add a comment on the protocol method below to say this is not a public method (package-private only).
```java
@Generated
@ServiceMethod(returns = ReturnType.SINGLE)
Response<BinaryData> onlyConvenientWithResponse(BinaryData body, RequestOptions requestOptions) {
    return this.client.onlyConvenientWithResponse(body, requestOptions).block();
}

@Generated
@ServiceMethod(returns = ReturnType.SINGLE)
public Resource onlyConvenient(Resource body) {
    // Generated convenience method for onlyConvenientWithResponse
    RequestOptions requestOptions = new RequestOptions();
    return onlyConvenientWithResponse(BinaryData.fromObject(body), requestOptions)
            .getValue()
            .toObject(Resource.class);
}
```

**Comment by weidongxu-microsoft** [comment]
Changing model to package-private could be an extra efforts, we probably want to delay it later. (that's likely involves another flag, that need to get propagated to children etc.)

For now, if both if false, could we only make protocol method package-private (while not generating convenience method, as usual)?

**Comment by haolingdong-msft** [comment]
Thanks @srnagar and @weidongxu-microsoft, I created an [issue](https://github.com/Azure/autorest.java/issues/1989) to track the change to make models package-private when convenience methods are disabled.

**Comment by haolingdong-msft** [comment]
For errorSetting case, Just generate package-private protocol methods.
