### ISSUE TITLE
cadl, upgrade compiler 0.39

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1923]

**Comment by weidongxu-microsoft** [comment]
https://www.npmjs.com/package/@cadl-lang/compiler

**Comment by haolingdong-msft** [comment]
Currently cadl-ranch has not been upgraded yet. We will get below error when `npm install` in `cadl-tests`:
![image](https://user-images.githubusercontent.com/87355844/212584389-34480902-9633-4f2e-b4dc-be79489e8d84.png)

**Comment by weidongxu-microsoft** [comment]
You can first upgrade and update the extension (to see what breaks). tests can be later (or you can remove the cadl-ranch dependencies and run just our tests).

**Comment by haolingdong-msft** [comment]
I've updated `cadl-extension` and run non-cadl-ranch tests previously, the tests seem OK. I will double check and create a draft pr.

**Comment by weidongxu-microsoft** [comment]
Please also take a quick check on deprecation. E.g. https://github.com/Azure/cadl-azure/blob/main/packages/cadl-dpg/src/decorators.ts#L30-L48

**Comment by weidongxu-microsoft** [comment]
For the `getConvenienceAPIName`, switch to use `shouldGenerateConvenient`.

For the name if "shouldGenerate", use `operation.name`.

You can remove `dev-options.generate-convenience-apis`

**Comment by haolingdong-msft** [comment]
released based on compiler 0.39: https://www.npmjs.com/package/@azure-tools/cadl-java/v/0.3.0
