### ISSUE TITLE
cadl, refine after upgrading to cadl compiler 0.39

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/autorest.java#1933]
1. investigate on how to pass in trait to make specialCharacters case work.

https://github.com/Azure/autorest.java/pull/1928#discussion_r1082084098

When upgrade to 0.39, we need to pass in trait.

2. read configuration from emitter options and then create dpgContext

https://github.com/Azure/autorest.java/pull/1928#discussion_r1082090239

3. update test cases to use `StandardResourceOperations` -> pending on David's reply in this conversation.

https://teams.microsoft.com/l/message/19:906c1efbbec54dc8949ac736633e6bdf@thread.skype/1674090432338?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1674021562604&teamName=Azure%20SDK&channelName=Cadl%20Discussion%20%F0%9F%90%AE&createdTime=1674090432338&allowXTenantAccess=false

link https://github.com/Azure/autorest.java/issues/1923

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/autorest.java/pull/1928#discussion_r1082271956

**Comment by weidongxu-microsoft** [comment]
versionedDependency -> useDependency

**Comment by weidongxu-microsoft** [comment]
not all tests updated.

**Comment by haolingdong-msft** [comment]
https://github.com/Azure/autorest.java/pull/1941
