### ISSUE TITLE
client, add copyright to generated pom.xml

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1970]
apply to all, include mgmt

example
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/pom.xml#L1-L4

**Comment by XiaofeiCao** [comment]
Do we need to refresh poms in autorest tests and resourcemanagers?

**Comment by weidongxu-microsoft** [comment]
> Do we need to refresh POMs in autorest tests and resourcemanagers?

I don't think so.
