### ISSUE TITLE
cadl, support generate pacakge-private convenient methods with pacakge-private models

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/autorest.java#1989]
When setting protocolApi and ConvenientApi to both false, we should still generate this method as package-private (not public) just to ensure the cadl definition looks good and all models are generated correctly. Note: both models and the client method should be package-private.

Ref: https://github.com/Azure/autorest.java/issues/1893#issuecomment-1435252705

**Comment by weidongxu-microsoft** [comment]
what are you talking about? currently disabled convenience method will not generate its model.

**Comment by haolingdong-msft** [comment]
You mean ff only one method disabled convenient api, the corresponding models will not be generated as well?

> what are you talking about? currently disabled convenience method will not generate its model.

**Comment by weidongxu-microsoft** [comment]
Yes, that's current behavior.

Hence I am not very keen to change this behavior (there is pending to move to getAllModels from cadl-dpg, also not eager to switch, but if you do this, you are likely not able to switch, or you need cadl-dpg to support this)

**Comment by haolingdong-msft** [comment]
Got it, if we don't need to generate package-private convenient methods, we can close this issue.

**Comment by weidongxu-microsoft** [comment]
BTW, model as package-private seems not even compile pass, as the client and models are in different packages...
