### ISSUE TITLE
cadl, first add new test case for protocol/convenient on/off

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#1991]
relate to https://github.com/Azure/autorest.java/issues/1893, preferable do this before impl of that issue.

Feel free to decide add on cadl-ranch or autorest.java

If autorest.java, requirement is:
- operation be POST, input and output be different model.
- different case (case of convenient on and convenient off) does not share model. -> to make sure model does not get affected by other case

If cadl-ranch, feel free to check with other languages.

**Comment by haolingdong-msft** [comment]
I'm also planning to add test cases before impl. I'm first adding it to autorest.java, because this test can not be verified using mock server, it needs manual verification on the generated code. I also checked with .net, they prefer adding the tests locally as well.
