### ISSUE TITLE
[Feature]: Support the decorator of @access

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#2051]
Please check the definition of this decorator:
https://azure.github.io/typespec-azure/docs/libraries/azure-dpg/reference/decorators#@Azure.ClientGenerator.Core.internal

The test was already added into Cadl-ranch:
https://github.com/Azure/cadl-ranch/pull/237

Please note: this decorator may cause breaking change for the SDK.

**Comment by weidongxu-microsoft** [comment]
we might want to see first how TOM could affect this.

**Comment by weidongxu-microsoft** [comment]
- https://github.com/Azure/autorest.java/pull/2285
- https://github.com/Azure/autorest.java/pull/2288
