### ISSUE TITLE
[DPG] Support of Unknown in models.

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2055]
`unknown` means that it can be anything. DPG should generate something that would allow anything to be passed (JSON object, array of string, null, etc.).

It's NOT the same thing as `object`, which means JSON object `{}`. It's acceptable for emitters to consider `object` and `unknown` as the same thing, depending of your language constraints.

This issue is focused on models as a success criteria. If the design is easy in query, header, etc. other part, there is no concern to add it. If this requires special design, then it's out of scope for now.

**Comment by weidongxu-microsoft** [comment]
It currently be Java `Object`, which is anything (same treatment as m4 `any`).

@srnagar Do we do anything different in DPG/TSP? I thought of `BinaryData`, but depends on the case (e.g. `Object` would win if it be simple integer or string, but we won't know as it is "unknown").

**Comment by weidongxu-microsoft** [comment]
`Object` is valid here.

Though will also check if we can use `BinaryData`. May do the swtich.
