### ISSUE TITLE
DPG, support special-header x-ms-client-request-id

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#2064]
It would not appear on method signature.

Impl automatically sets a random GUID, if not set by user.

Handle similar to RepeatableRequests https://github.com/Azure/autorest.java/issues/2063

**Comment by XiaofeiCao** [comment]
It's used as a correlation id among a group of request ids: https://github.com/Azure/azure-sdk/issues/576#issuecomment-1029635259

Will treat the same as the repeatability id.

**Comment by XiaofeiCao** [comment]
Seems we already have it in `RequestIdPolicy` in our default HttpPipeline? It applies to both dpg and mgmt...

**Comment by weidongxu-microsoft** [comment]
We can talk in meeting.

ARM always support x-ms-client-request-id, but not so for data-plane. I am not sure if service would behave unexpectedly, if we sent this when backend does not expect it.

**Comment by XiaofeiCao** [comment]
Close as discussed. 

We've already supported and will have future discussions if one service throws an error due to this header.
