### ISSUE TITLE
mgmt, handle weird resource path in eventgrid 

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2149]
(domain before eventSubscriptions): https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2023-06-01-preview/EventGrid.json#L2001

(topic before eventSubscriptions): https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2023-06-01-preview/EventGrid.json#L2067

Ideally they need to map to different resources. We can start with a workaround to enforce consistent mapping for `define` method, e.g. https://github.com/Azure/azure-sdk-for-java/pull/35026#pullrequestreview-1433721618

**Comment by weidongxu-microsoft** [comment]
I am also need to handle this to support a case of e.g. map a resource to `null` to avoid breaking changes (previous stable the resource only happen to response, but in new stable it now can be createOrUpdate).
