### ISSUE TITLE
tsp, generate protocol method only if the operation contains union types

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/autorest.java#2160]
Requirements:
1. Generate protocol method only if the operation contains union types, including response type, request type and header/query parameters.

Link https://github.com/Azure/autorest.java/issues/1958#issuecomment-1543423738

**Comment by weidongxu-microsoft** [comment]
remind, whitelist at least below
- Union on Literal e.g. `"success" | "fail"`, as it is Enum
- Union on Type and null e.g. `float | null`, as it is Float

**Comment by haolingdong-msft** [comment]
Update on 2023.5.31 meeting:

For the case if it is input model and the union  type is `string|string[]`, then we can probably generate convenient method.

```ts
op foo(name: string | string[])
public void foo(List<String> name)
```

```java
public void foo(List<String> name)

public Response<Void> fooWithResponse(BinaryData request, RequestOptions options)
```

**Comment by weidongxu-microsoft** [comment]
We has a pending job on Javadoc.
https://github.com/Azure/autorest.java/issues/2271
