### ISSUE TITLE
tsp, generate convenient method if it is overload method with non-union types

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/autorest.java#2161]
Currently we disable method generation(including protocol and convenient methods) for overload operations (the ones with @overload decortor). We need to generate convenient method if it is overload method with non-union types

Link: https://github.com/Azure/autorest.java/issues/1958#issuecomment-1562558219

**Comment by weidongxu-microsoft** [comment]
Logic for whether to generate convenient is same as normal operation (that is, currently, no JSON merge path, no multiple content-type; may have no Union after https://github.com/Azure/autorest.java/issues/2160).
