### ISSUE TITLE
Support generating ApiKey with prefix 

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2162]
This TypeSpec:
```
@useAuth({
  type: AuthType.http,
  scheme: "SharedAccessKey",
})
```

Means to authenticate using the headers:
```
Authorization: SharedAccessKey <put my key here>
```

This support has been added in Azure-Core to be released early June:
https://github.com/Azure/azure-sdk-for-java/pull/35010

Work item is to recognize the TypeSpec, and configure the AzureKeyCredentialPolicy with a prefix.

Cadl-Ranch test:
https://github.com/Azure/cadl-ranch/pull/262

**Comment by weidongxu-microsoft** [comment]
So azure-core will be available in early June.

@srnagar 
Do we still use `credential(AzureKeyCredential azureKeyCredential)` signature in Builder, or do we want to have a different name?

```java
    /*
     * The AzureKeyCredential used for authentication.
     */
    @Generated private AzureKeyCredential azureKeyCredential;

    /** {@inheritDoc}. */
    @Generated
    @Override
    public ApiKeyClientBuilder credential(AzureKeyCredential azureKeyCredential) {
        this.azureKeyCredential = azureKeyCredential;
        return this;
    }
```

**Comment by srnagar** [comment]
We should still use `credential(AzureKeyCredential credential)` as the user doesn't need to be aware of the prefix added to the token in the `AzureKeyCredentialPolicy`. Also, the prefix can be anything else and not just `SharedAccessKey`.

**Comment by weidongxu-microsoft** [comment]
Got it.

Yes, prefix can be anything from the `scheme` field.
