### ISSUE TITLE
Do not set required = true in @JsonProperty for deserialization of properties

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#2169]
When deserializing a service response, we should not fail if a required property is not included in the response. This is a use case for OpenAI where the streaming response will not have some fields that are otherwise required for non-streaming responses.

**Comment by weidongxu-microsoft** [comment]
Does it apply to "input-output" model, or "output-only" model?

We did a bit of this kind for `x-ms-secret` property (that even if `required`, won't return in response, and hence we don't add `required=true` to it).

**Comment by weidongxu-microsoft** [comment]
There is another issue about ctor and Jackson. https://github.com/Azure/autorest.java/issues/2169

We may want to remove `@JsonProperty` from ctor.

These on ctor would cause failure if missing.

`required = true` on class variable won't cause failure.
