### ISSUE TITLE
[Test Proxy] Test classes to extend from TestProxyTestBase instead of TestBase  

### ISSUE THREAD

**Issue by samvaity** [Azure/autorest.java#2180]
With TestProxy integration, libs should be extending from the `TestProxyTestBase` class instead of the previous `TestBase` class.
This will enable the TestProxy integration for the clients.
Make this default behavior.

We should also create the `assets.json` file for the SDK package with an empty tag reference. 
The empty tag ref will make sure that the package owners will need to push the recordings to the [assets repo](https://github.com/Azure/azure-sdk-assets/blob/main/README.md) and update the tag reference accordingly.

**Comment by weidongxu-microsoft** [comment]
Is asserts.json be this?

```json
{
  "AssetsRepo": "Azure/azure-sdk-assets",
  "AssetsRepoPrefixPath": "java",
  "TagPrefix": "java/<group>/<module>",
  "Tag": ""
}
```

---

Since data-plane service would use this to record their tests, do we know they know how to use test proxy, and has required permission to have it commit to asserts repo?

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/azure-sdk-for-java/wiki/Test-Proxy-Migration maybe a candidate doc about test proxy setup and usage. But for service, that is not a migration.

**Comment by samvaity** [comment]
> https://github.com/Azure/azure-sdk-for-java/wiki/Test-Proxy-Migration maybe a candidate doc about test proxy setup and usage. But for service, that is not a migration.

I am also adding more documentation for Test Proxy.
Just need to figure out the best place to have the documentation -https://github.com/Azure/azure-sdk-for-java/pull/35232
Since, we never had a Test Infra setup doc before.

**Comment by weidongxu-microsoft** [comment]
Sure.

DPG had a simple one here https://github.com/Azure/azure-sdk-for-java/wiki/TypeSpec-Java-Quickstart#adding-tests

But apparently it does not cover test proxy for now.

**Comment by samvaity** [comment]
> Sure.
> 
> DPG had a simple one here https://github.com/Azure/azure-sdk-for-java/wiki/TypeSpec-Java-Quickstart#adding-tests
> 
> But apparently it does not cover test proxy for now.

Oh ok. We should probably edit that to include Test Proxy changes.

**Comment by weidongxu-microsoft** [comment]
@samvaity 

I kind of think you would have a section in [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-java/blob/main/CONTRIBUTING.md) (it get direct refer from README.md)
Either a complete one, or a simple one which points to a complete guide on record testing.

Currently it has a section on live testing, but seems none for record testing.

Note I am not expert on the readme part, we probably need confirmation from Srikanta or Jonathan.

**Comment by weidongxu-microsoft** [comment]
PR https://github.com/Azure/autorest.java/pull/2222

I can merge it anytime.
Prefer to have some guide.

**Comment by samvaity** [comment]
> PR #2222
> 
> I can merge it anytime. Prefer to have some guide on how to setup TestProxy and how to record.

Thanks @weidongxu-microsoft !
Guide Links:
https://github.com/Azure/azure-sdk-for-java/wiki/Test-Proxy-Migration
https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/core/azure-core-test#azure-core-test-shared-library-for-java
