### ISSUE TITLE
DPG: Handle Non-standard special headers for client-Request-Id and return-Client-Resquest-Id

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#2216]
Based on the discussion: Azure.Core has a policy to append return-client-response-id and client-request-id.
So Codegen will automatically add this policy to pipeline in client constructors and remove those two head parameters from method signature.

**Comment by weidongxu-microsoft** [comment]
No policy to add return-client-response-id. It just get ignored.
