### ISSUE TITLE
Download language server to avoid bundling with jar

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#2227]
Thoughts on instead of using a temporary directory we use a well-known directory that has different version identifiers based on the Autorest Java version being used? Similar to what is done for Test Proxy. This way we can remove the entire need to bundle the Eclipse language server into Autorest Java and can instead use the download links provided by Eclipse to download the ZIP file if it doesn't exist, if it does exist we know all this work has already been done and can be skipped.

_Originally posted by @alzimmermsft in https://github.com/Azure/autorest.java/pull/2204#discussion_r1253033178_

**Comment by weidongxu-microsoft** [comment]
Alan should have done this.
