### ISSUE TITLE
[Bug] Compilation error: when using enable-sync-stack: true

### ISSUE THREAD

**Issue by samvaity** [Azure/autorest.java#2240]
@minnieliu reported this compilation error when using the enable-sync-stack: true flag on communication-rooms sdk.
Noticing that the generate sync API expects these two parameters https://github.com/minnieliu/azure-sdk-for-java/blob/d66ad21028e650de5fe49651b5fceebc6d9dd9fb/sdk/communication/azure-communication-rooms/src/main/java/com/azure/communication/rooms/implementation/RoomsImpl.java#L286-L287
That are not defined in the method body.

But as far the async version they should be defined in the method body like such
https://github.com/minnieliu/azure-sdk-for-java/blob/d66ad21028e650de5fe49651b5fceebc6d9dd9fb/sdk/communication/azure-communication-rooms/src/main/java/com/azure/communication/rooms/implementation/RoomsImpl.java#L200-L201

**Comment by weidongxu-microsoft** [comment]
@minnieliu 

What is the version of autorest-java?

The one in readme is too old
https://github.com/minnieliu/azure-sdk-for-java/blob/d66ad21028e650de5fe49651b5fceebc6d9dd9fb/sdk/communication/azure-communication-rooms/swagger/README.md

Latest be `@autorest/java@4.1.17`

**Comment by minnieliu** [comment]
@weidongxu-microsoft thanks, upgrading to the latest resolved the issue! Feel free to close the bug.
