### ISSUE TITLE
[Java]: Codebase Unification for DPG and mgmt. SDK

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#2283]
Describe the issue or request
Follow https://github.com/Azure/typespec-azure/issues/3424

Describe your ideas for solutions.

This is the step to ensure we could use typespec codeGen to also generate typespecs from mgmt. SDK
This includes:

Unified the behavior of the generated SDK for models, operation, etc.
Unified the CodeGen for APIs & models generation.

**Comment by weidongxu-microsoft** [comment]
Note that it would only include Lite packages (auto-generated).

It does not include Premium packages (which contains handwritten code).

**Comment by weidongxu-microsoft** [comment]
ref https://github.com/Azure/autorest.java/issues/2311

**Comment by ArthurMa1978** [comment]
dup with:
https://github.com/Azure/autorest.java/issues/2330
https://github.com/Azure/autorest.java/issues/2331
https://github.com/Azure/autorest.java/issues/2332
https://github.com/Azure/autorest.java/issues/2333
