### ISSUE TITLE
partial-update, getting wrong base directory 

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/autorest.java#2319]
https://github.com/Azure/azure-sdk-for-java/pull/36822#discussion_r1331010648

module-info.java not get partial updated becuase `projectBaseDirectoryPath` use `autorest.java` as base. So we cannot find existing file.
![image](https://github.com/Azure/autorest.java/assets/87355844/7bb4b546-e618-44c5-af2c-9fff52fad4c1)

**Comment by weidongxu-microsoft** [comment]
may consider not use outputFolder, if it is relative path.
