### ISSUE TITLE
[MPG][Java] Unify CodeGen - Support AutoRest Extensions for OpenAPI 2.0

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/autorest.java#2332]
https://github.com/weidongxu-microsoft/work-notes/pull/6/files#diff-a0291ccf094def4ea830dfc9fb671cb6c9eb5d8ec6547ff9f2fdc838e0588f91

**Comment by XiaofeiCao** [comment]
Common ones in https://github.com/weidongxu-microsoft/work-notes/pull/6/files#diff-a0291ccf094def4ea830dfc9fb671cb6c9eb5d8ec6547ff9f2fdc838e0588f91 have all been solved. 

For uncommon ones, `x-ms-client-flatten` has been solved by `@flattenProperty`. For others, we may see if any service uses it.
