### ISSUE TITLE
Java Emitter should produce LRO GetOperationStatus API

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#2456]
DeviceUpdate have 2 LRO APIs, ImportDevices and ImportUpdate that each has corresponding polling API GetOperationStatus.

The API is present in [old Swagger](https://github.com/Azure/azure-rest-api-specs-pr/blob/7ae8d80917d262746790f86c98c5191bd0ce8eff/specification/deviceupdate/data-plane/Microsoft.DeviceUpdate/stable/2022-10-01/deviceupdate.json#L537) and after move to [TypeSpec+DPG] (https://github.com/Azure/azure-rest-api-specs-pr/blob/0788c5a7d5375a141d66f2cb82266f7c8190550d/specification/deviceupdate/Microsoft.DeviceUpdate/routes.tsp#L200) 
Java won't generate GetOperationStatus API. 

Based on the recent discussion, all operations in the namespace where you define "@service" should be generated, independently of their usage or not with "@pollingOperation".

The requirement from service team could be found in https://github.com/Azure/autorest.csharp/issues/3964

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/autorest.java/pull/2454
