### ISSUE TITLE
[TypeSpec] Support @flattenProperty

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2460]
Generate flattened models when the TypeSpec contains this annotation

Needs TCGC: https://github.com/Azure/typespec-azure/issues/13
Needs cadl-ranch: https://github.com/Azure/cadl-ranch/issues/471

**Comment by weidongxu-microsoft** [comment]
code https://github.com/Azure/autorest.java/pull/2529

TODO add test with future cadl-ranch

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao Java may not enable it for DPG and hence current cadl-ranch test does not apply.

You can have local ARM test with flattenProperty. And close this issue if local ARM test works with flattenProperty.
