### ISSUE TITLE
We should not use the boolean value of 'branded' to decide branding/non-branding

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#2478]
Today, we are using the following option to decide whether to do branding or not:
https://github.com/Azure/autorest.java/blob/2927ca78e68911c5cad94f9dc3af1ca7da0b9f82/typespec-extension/src/emitter.ts#L20
```
"branded": { type: "boolean", nullable: true, default: true },
```

Based on the requirement, we should use the branding value that the user of the generator inputs.
so we need to update the implementation of the handling of Branded in Java code.

**Comment by srnagar** [comment]
@lirenhe Could you please elaborate on what the user input for this would be?

**Comment by lirenhe** [comment]
> @lirenhe Could you please elaborate on what the user input for this would be?

We should use a string about the manufacturer name like Azure/OpenAI etc.

**Comment by weidongxu-microsoft** [comment]
Likely replaced by https://github.com/Azure/autorest.java/issues/2596
