### ISSUE TITLE
mpg, api-version not present in service client(operation's api-version is empty in code-model)

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2503]

**Comment by weidongxu-microsoft** [comment]
This still exist?

It means the generated SDK cannot actually work, right?

**Comment by XiaofeiCao** [comment]
Yeah, it still exists. I'm looking into the issue.

**Comment by weidongxu-microsoft** [comment]
I guess it probably due to the difference to api-version parameter. In Swagger it is a constant with the version of that Swagger.

But in TypeSpec there be multiple versions, so we didn't do this to the api-version parameter.

**Comment by XiaofeiCao** [comment]
Current observation is, we do have a global api-version parameter with constant schema. Though each operation has its own api-version schema definition(which doesn't reference to the global parameter) and the schema is empty.

We may need to update the operation's api-version parameter's schema to refer to the global one like swagger does.

**Comment by weidongxu-microsoft** [comment]
We can refer to api-version in client (which can be more than one). But not api-version in code-model (which is only one).

TypeSpec can have different api-version on different namespace, which maps to client.

**Comment by weidongxu-microsoft** [comment]
And autorest also support mixing Swagger of different api-version (this is not same as the case above). I just mean even autorest does not always have a global api-version.

**Comment by XiaofeiCao** [comment]
For single api-version, m4 will put `api-version` in `globalParameters`. 
![image](https://github.com/Azure/autorest.java/assets/92354331/a433175f-1cb5-48b8-abcc-f2039da17330)
![image](https://github.com/Azure/autorest.java/assets/92354331/7a270e93-2f44-40f1-9584-8b990d55a907)

For mixing api-versions, m4 will put `api-version`'s constants into `constants`, and inline api-version parameter definition in `parameters` of `operation`.
![image](https://github.com/Azure/autorest.java/assets/92354331/31ed729a-82e8-41e4-9999-a4c684f435c1)
![image](https://github.com/Azure/autorest.java/assets/92354331/0525bdd6-4724-470b-8e05-e633a0095848)

Will align with this behavior.

**Comment by weidongxu-microsoft** [comment]
Maybe we first handle the former case.

**Comment by weidongxu-microsoft** [comment]
Is it now possible to send and receive a e.g. List from service (using tsp generated sdk)?

**Comment by XiaofeiCao** [comment]
> Is it now possible to send and receive a e.g. List from service (using tsp generated sdk)?

Yes, live test can pass for list:

```log
[ForkJoinPool.commonPool-worker-1] INFO com.azure.resourcemanager.sphere.implementation.CatalogsClientImpl$CatalogsService.list - {"az.sdk.message":"HTTP request","method":"GET","url":"https://management.azure.com/subscriptions/REDACTED/providers/Microsoft.AzureSphere/catalogs?api-version=2022-09-01-preview","tryCount":"1","Date":"Wed, 17 Jan 2024 06:02:00 GMT","Authorization":"REDACTED","Content-Length":"0","Content-Type":"application/json","x-ms-client-request-id":"7ce33643-1d96-4df6-8eda-c5dbcc891b2e","accept":"application/json","User-Agent":"azsdk-java-com.azure.resourcemanager.sphere/1.0.0-beta.1 (17.0.9; Mac OS X; 14.2; auto-generated)","contentLength":0}
[reactor-http-nio-3] INFO com.azure.resourcemanager.sphere.implementation.CatalogsClientImpl$CatalogsService.list - {"az.sdk.message":"HTTP response","contentLength":"12","statusCode":200,"url":"https://management.azure.com/subscriptions/REDACTED/providers/Microsoft.AzureSphere/catalogs?api-version=2022-09-01-preview","durationMs":749,"Date":"Wed, 17 Jan 2024 06:02:03 GMT","Content-Length":"12","Expires":"-1","X-Content-Type-Options":"REDACTED","x-ms-routing-request-id":"REDACTED","Content-Type":"application/json; charset=utf-8","x-ms-ratelimit-remaining-subscription-reads":"REDACTED","Cache-Control":"no-cache","x-ms-request-id":"c07c8d95-c1d5-4056-bac8-f3f1cbef15c7","Strict-Transport-Security":"REDACTED","x-ms-correlation-request-id":"REDACTED","Pragma":"no-cache","body":"{\"value\":[]}"}
```
