### ISSUE TITLE
Integrate with generation script, generate root pom, ci.yml, generate changelog diffs

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2518]
```[tasklist]
### Tasks
- [x] delete repo before generation
- [x] generate changelog
```

**Comment by weidongxu-microsoft** [comment]
An existing issue similar to https://github.com/Azure/autorest.java/issues/2141

If we do it in codegen, need to think whether we do it in TypeScript or Java module.

**Comment by XiaofeiCao** [comment]
PR: https://github.com/Azure/azure-sdk-for-java/pull/39832
