### ISSUE TITLE
Try the code on the branch 'getAllOperations'

### ISSUE THREAD

**Issue by haolingdong-msft** [Azure/autorest.java#2528]
https://gist.github.com/iscai-msft/b4f2d4f7a6313da04f1d2e981b3b1200

Currently it is on this branch: https://github.com/Azure/typespec-azure/tree/getAllOperations

**Comment by haolingdong-msft** [comment]
Environemnt issues met:
1. dependency resolving issue. typespec-java -> TCGC (unreleased version on feature branch)-> core (unreleased version on main)
2. hard to get the artifact url, contact Izzy: https://gist.github.com/iscai-msft/b4f2d4f7a6313da04f1d2e981b3b1200?permalink_comment_id=4845621#gistcomment-4845621

**Comment by weidongxu-microsoft** [comment]
1 maybe solved after upgrade to 0.52, that compiler code should be similar if not same
https://github.com/Azure/autorest.java/pull/2527
