### ISSUE TITLE
Upgrade Java Emitter to use TypeSpec 0.52

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#2530]
TypeSpec Core release notes: [January 2024 | TypeSpec](https://typespec.io/docs/release-notes/release-2024-01-23)
TypeSpec Azure release notes: [January 2024 | TypeSpec Azure](https://azure.github.io/typespec-azure/docs/release-notes/release-2024-01-23)

**Comment by lirenhe** [comment]
Seems Java side already completed this.

**Comment by weidongxu-microsoft** [comment]
released https://github.com/Azure/azure-sdk-for-java/pull/38485
