### ISSUE TITLE
Support @clientName and @encodedName

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#2535]
As encodedName is introduced in 0.52 of TypeSpec. 
```
model Widget {
  @key id: string;

  @encodedName("application/json", "WidgetWeight")
  weight: int32;
  
  color: "red" | "blue";
  @added(Versions.v2) name: string;
}
```
And @clientName is introduced in this PR https://github.com/Azure/typespec-azure/pull/127/files.

Please support them in the CodeGen.

**Comment by weidongxu-microsoft** [comment]
`@clientName` is supported in 0.13.0 onward and released.

**Comment by timotheeguerin** [comment]
@weidongxu-microsoft is `@encodedName` support still pending? We already had started migrating and recommending user to use that.

**Comment by weidongxu-microsoft** [comment]
@timotheeguerin 

`@encodedName` for `application/json` is supported in 0.13.2 (early Feb., synced to SDK repo)
https://github.com/Azure/autorest.java/blob/main/typespec-extension/changelog.md#0132-2024-02-02

I kept the issue open as I am not sure whether we would get `@encodedName("multipart/form-data")` or `@encodedName("application/xml")` anytime soon :-(

**Comment by timotheeguerin** [comment]
Yeah just json for now is fine we haven’t tested anything with xml yet in typespec.

**Comment by weidongxu-microsoft** [comment]
`@encodedName("application/json")` is supported. For other types will use a new issue.
