### ISSUE TITLE
MPG, migrate fluentgen modelerfour(/identity) naming settings to typespec-extension

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2548]
https://github.com/Azure/autorest.java/blob/5acb73c3e8bfa56271247d3616cb1f5e942a5848/fluentgen/readme.md

#### IPRules
**tsp**: https://github.com/Azure/azure-rest-api-specs/blob/f776434f63fb6505926273db8d4f9a93b75ee4a1/specification/networkanalytics/NetworkAnalytics.Management/main.tsp#L77-L83
**swagger**: https://github.com/Azure/azure-rest-api-specs/blob/f776434f63fb6505926273db8d4f9a93b75ee4a1/specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/networkanalytics.json#L1686

-----------------------------------------------

#### userName
**tsp**: https://github.com/Azure/azure-rest-api-specs/blob/f776434f63fb6505926273db8d4f9a93b75ee4a1/specification/networkanalytics/NetworkAnalytics.Management/main.tsp#L434
**swagger**: https://github.com/Azure/azure-rest-api-specs/blob/f776434f63fb6505926273db8d4f9a93b75ee4a1/specification/networkanalytics/resource-manager/Microsoft.NetworkAnalytics/stable/2023-11-15/networkanalytics.json#L2455
```[tasklist]
### Tasks
- [x] Naming override from FluentGen
- [ ] Naming override from m4
```

**Comment by weidongxu-microsoft** [comment]
Maybe not high priority?

**Comment by XiaofeiCao** [comment]
From the difference of tsp/swagger generated SDK for networkanalytics, there seems to be quite a few related to this, 
e.g. IpRules -> IPRules, timestamp -> timeStamp, etc..
https://apiview.dev/Assemblies/Review/d42c19683b6c4d17ab34625bc9f2b750?revisionId=2554ec62ec9d4bc18c34c77d8ac88bfe&diffOnly=False&doc=False&diffRevisionId=b222576086f949fea4540b6ea88f3822

**Comment by weidongxu-microsoft** [comment]
I see...

A bit unsure whether we should have emitter to handle it for them, or have service do `@clientName`.

Could you check e.g. `userName` still triggers a spotbug error on SDK repo?

**Comment by XiaofeiCao** [comment]
Currently not needed for greenfield. Will see whether `@clientName` can be used for brownfield.
