### ISSUE TITLE
use isErrorOrChildOfError method from tcgc to check if model is an error model

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2586]
The `isErrorModel` function in tsp core currently doesn't recursively mark children of error models as error models. This [issue](https://github.com/microsoft/typespec/issues/2957) is going to go up for design review. In the meantime, we want to support inheritance for child error models.

We want to switch uses of `isErrorModel` from tsp core in our emitter to use [isErrorOrChildOfError](https://github.com/Azure/typespec-azure/blob/ff7726fba2db9dc8ab1fa0385b7a1590b77b36bf/packages/typespec-client-generator-core/src/public-utils.ts#L537) from `tcgc`, since this will recurse through child models as well.

NOTE: need to use `0.40.0-dev.15` of `tcgc` to get `isErrorOrChildOfError` support

Cadl-Ranch is not yet implemented, the scenario can be seen in this playground [here](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQGVycm9yCm1vZGVsIEhhc0XED0RlY29yYXRvciB7CiAgY29kZTogc3RyaW5nOwp9CsctSW5oZXJpdNAyZXh0ZW5kc9hMaGlsZFByb3DNUUBwdXQKb3AgaNA0KCk60kk7CsQsadV%2FxDH2AJk7Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by weidongxu-microsoft** [comment]
@lmazuel 
Does any service depend on this "isErrorOrChildOfError"?

Reason is that typespec-java is currently on 0.13.x patch branch and 0.14.x release branch. 0.14.x switched to stream-style-serialization (basically it means the whole JSON serialization code is changed -- therefore we are still in the middle to migrating existing libs on SDK repo).
Therefore, SDK repo is currently still on 0.13.x. If any service has this dependency, we had to patch on 0.13.x as well.

**Comment by weidongxu-microsoft** [comment]
PR ready https://github.com/Azure/autorest.java/pull/2604

Hope we can release 0.14.1 tomorrow (PS: may want to include https://github.com/Azure/autorest.java/pull/2603).

**Comment by weidongxu-microsoft** [comment]
I will move back to `isErrorModel` when updating cadl-ranch on the ErrorModel test case.
