### ISSUE TITLE
Change default generation flavor and flags for generic codegen

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2596]
- Emitter should generate "unbranded" code by default
- Add a new flag `flavor` that generates azure code for the value `azure`. This is not case-sensitive. Any other value does nothing, and therefore generates unbranded code.
- Don't remove yet currently supported flag `branded` to help the transition to the new system. If both flags are set, read `flavor` first and ignore `branded` boolean flag.
- If `package-dir` starts with `azure`, auto-set `flavor` to `azure` if `flavor` was not set already. If `package-dir` is anything else, no specific behavior.

**Comment by weidongxu-microsoft** [comment]
We can do this, but as 2024/03/04 it would not be meaningful, as Java don't have a generic core published anywhere.
@srnagar

**Comment by srnagar** [comment]
As discussed, since the generic-core is not published to Maven Central yet, switching the default will result in unresolved dependencies for generic core. Also, the generic core APIs are still work in progress and we should not change the emitter to be generic by default until the APIs are stabilized.

**Comment by weidongxu-microsoft** [comment]
a bit of thought on internal impl

we probably still want to keep the boolean in internal, e.g. `isBranded` or `isAzure` or `isGeneric`. personally I don't want to see 10+ lines of `if ("azure".equalIgnoreCase(settings.getFlavor()) {` scattered around the whole repo.

**Comment by haolingdong-msft** [comment]
I'm going to close this task, and we will create other tasks related with unbranding later, e.g. adopting generic-core, embedding flavor to generated code, make non-azure code as default (after generic-core go public). @lmazuel @srnagar @lirenhe Please let me know if you have any concern on closing this task.
/cc @weidongxu-microsoft
