### ISSUE TITLE
[BUG] tsp sample generation, constructor error when required value is not present in example file

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2611]
missing required example value for constructor will result in generated code like `new LongRequest( , , )`.
issue PR: https://github.com/Azure/autorest.java/pull/2612

**Comment by weidongxu-microsoft** [comment]
Candidate:

1. `null` for non-primitive, 0 etc. for priminite
2. log error but keep current behavior
3. throw

**Comment by XiaofeiCao** [comment]
Missing required value seems invalid example to me. We should either throw or skip this file.

**Comment by XiaofeiCao** [comment]
I'll do throw first, see if we need to catch and skip.
