### ISSUE TITLE
Generate structured logs in azure and debranded libs

### ISSUE THREAD

**Issue by lmolkova** [Azure/autorest.java#2631]
Structured logging is supported in azure-core and generic-core: https://github.com/Azure/azure-sdk-for-java/wiki/Logging-in-Azure-SDK

Structured logging allows to:
- record  properties as key-value-pairs instead of formatted values
- record static log message

As a result, logs become query-able and aggregate-able.

Whenever we generate logging code, we need to make sure we use `logger.at<Level>().addKeyValue("key", "value").log()` pattern with static message and properties passed with `addKeyValue` method.

**Comment by weidongxu-microsoft** [comment]
Logging code generated by codegen has 2 patterns.

Case 1 is `throw LOGGER.logExceptionAsError(new IllegalArgumentException(`
This would be replaced by `throw LOGGER.atError().log(new IllegalArgumentException(`

Case 2 is `LOGGER.info("HttpPipeline is being set to 'null' when it was previously configured.");`
This would be replaced by `LOGGER.atInfo().log("HttpPipeline is being set to 'null' when it was previously configured.");`
(there appears not a candidate key value to set, as the pipeline is an object)

**Comment by lmolkova** [comment]
Thanks for checking, @weidongxu-microsoft !
This came up in the discussions around generic core and future plans. @srnagar do you think there is a benefit in changing these current occurrences of logs - using different overloads doesn't seem to bring any immediate benefit.
