### ISSUE TITLE
XML name should be used if present in JsonProperty annotation

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.java#264]
Based on some troubleshooting work I did with @rickle-msft. It seems like we don't properly handle cases where the XML name is different than the property name.

Sounds like @lmazuel is planning on adding test coverage in autorest.testserver so we may want to wait for that.

**Comment by lmazuel** [comment]
I do that today and send an email, thanks!

**Comment by lmazuel** [comment]
@RikkiGibson Done in testserver 2.5.17.
Python tests: https://github.com/Azure/autorest.python/pull/63

**Comment by RikkiGibson** [comment]
I hoped I'd fixed this problem in 265 but I introduced a new one-- I think it's necessary to use CompositeType.XmlProperties.Name instead of CompositeType.XmlName. Will try to get to this one today..

**Comment by lmazuel** [comment]
Hey @RikkiGibson 
What change in the modeler? Could you describe your scenario, so I test it in Python? If it works, it's definitely a Java issue :p. If it doesn't, might be a Java/Python issue or modeler. But my current feeling is that modeler has no trouble.
Thoughts?

**Comment by RikkiGibson** [comment]
@lmazuel and I hashed it out. I have basically concluded that this is a corner case where OpenAPI limitations interact with the AutoRest modeler such that it's not practical to make the AutoRest modeler just do the convenient thing for us.
