### ISSUE TITLE
[MPG] versioning for @added mixed with @removed

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2644]
```typescript
@added(Versions.v2022_09_02_preview)
@added(Versions.v2023_03_15_preview)
@added(Versions.v2023_06_15_preview)
@added(Versions.v2023_08_15_preview)
@removed(Versions.v2023_10_15)
@added(Versions.v2024_02_02_preview)
hubProfile?: FleetHubProfile;
```

https://github.com/Azure/azure-rest-api-specs/blob/80be470f83f16d693291beb988ee80cd9a0b8023/specification/containerservice/Fleet.Management/fleet.tsp#L50-L58

`TCGCContext` will likely contain a flag to only include operations in latest version: https://github.com/Azure/typespec-azure/issues/129#issuecomment-2011627278

TCGC `getAllOperations` will return operations/models with all the available versions.

Before TCGC supports it and we integrate `getAllOperations`, we could see if we can leverage [existsAtVersion](https://github.com/microsoft/typespec/blob/baac24ac0061910339304ae629fd9317a4e1f03e/packages/versioning/src/versioning.ts#L849) from versioning, using the default(latest) version.

**Comment by weidongxu-microsoft** [comment]
One suggestion is to have a e.g. "api-version" var in class (default to latest).

And codegen (in default mode -- not handling breaking changes caused by non-REST-API-break) would generate API (it may include parameter and model property) that is available in this "api-version".
