### ISSUE TITLE
Additional properties Java implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2654]

**Comment by weidongxu-microsoft** [comment]
Tried it weeks ago, seems does not incur emitter changes.

![image](https://github.com/Azure/autorest.java/assets/53292327/7da29069-4cf2-4a95-a66d-669335e556ec)

Though this likely also be involved on the migration to TCGC common.

**Comment by weidongxu-microsoft** [comment]
cadl-ranch tests integrated and pass
