### ISSUE TITLE
Additional properties Java design

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2658]

**Comment by lmazuel** [comment]
Based on what @weidongxu-microsoft said on the implementation issue #2654 , closing this issue as "designed already"

**Comment by weidongxu-microsoft** [comment]
Java's user-facing API is

```java
Map<String, T> getAdditionalProperties();

Model setAdditionalProperties(Map<String, T> additionalProperties);
```

`T` be the type. If it is a Union that cannot be easily interpretated (same as other places like type of model property), `BinaryData` is used.

**Comment by weidongxu-microsoft** [comment]
doc PR https://github.com/Azure/typespec-azure/pull/675
