### ISSUE TITLE
Method signature (alias / spread) User experience

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2670]

**Comment by weidongxu-microsoft** [comment]
https://github.com/Azure/autorest.java/issues/2678

**Comment by weidongxu-microsoft** [comment]
close it, but it may need update, as the current PR to typespec-azure contains invalid tsp

**Comment by weidongxu-microsoft** [comment]
update doc for "spread is spread"
https://github.com/Azure/typespec-azure/pull/1143
