### ISSUE TITLE
Method signature (alias / spread) Implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2671]

**Comment by weidongxu-microsoft** [comment]
WIP https://github.com/Azure/autorest.java/pull/2821

need TCGC release (so that it avoid `getEffectiveType`)

**Comment by weidongxu-microsoft** [comment]
The update of commit ID to that after `BodyParameter` is done via PR https://github.com/Azure/azure-sdk-for-java/pull/40992

There is some question about how best to customize the name of `body` parameter to e.g. keep backward-compatible (that applies to most languages). https://github.com/Azure/azure-rest-api-specs/issues/29696

**Comment by weidongxu-microsoft** [comment]
0.18.0 released

- merge to SDK repo https://github.com/Azure/azure-sdk-for-java/pull/41080
