### ISSUE TITLE
Generated JavaDoc is sometimes incorrectly laid out

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/autorest.java#271]
Refer to, for example, https://github.com/Azure/azure-sdk-for-java/blob/master/cognitiveservices/data-plane/search/bingcustomimagesearch/src/main/java/com/microsoft/azure/cognitiveservices/search/customimagesearch/BingCustomInstances.java#L418

On that line you will see JavaDoc in the following form:

```            /**
             * The zero-based offset that indicates the number of images to skip before returning images. The default is 0.
             *   The offset should be less than
             ([totalEstimatedMatches](htt*   ps://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#totalestimatedmatches)
             *   - count). Use this parameter along with the count parameter to page results. For example, if your user
             *   interface displays 20 images per page, set count to 20 and offset to 0 to get the first page of results. For
             *   each subsequent page, increment offset by 20 (for example, 0, 20, 40). It is possible for multiple pages to
             *   include some overlap in results. To prevent duplicates, see
             [nextO*   ffset](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/bing-images-api-v7-reference#nextoffset).
             *   Use this parameter only with the Image API. Do not specify this parameter when calling the Trending Images
             *   API or the Web Search API.
             *
             * @return next definition stage
             */
```

It appears to be using markdown syntax in JavaDoc, which should use the HTML syntax. Also, it is incorrectly positioning the * that should be at the front of each line.

**Comment by RikkiGibson** [comment]
That's good news--there should be approximately a zillion markdown to HTML utilities out there.

**Comment by JonathanGiles** [comment]
It would be interesting to do some analysis across all files you process to determine if any other markdown syntax appears. I wouldn't be surprised to find some other syntax being used (bold, italic, code formatting, etc). If these do turn up in your analysis, enabling support for converting them to their appropriate html syntax would be worthwhile too.

**Comment by JonathanGiles** [comment]
Is there any status update here? I'm seeing similar issues throughout the Azure/azure-libraries-for-java project, e.g. https://github.com/Azure/azure-libraries-for-java/blob/master/azure-mgmt-resources/src/main/java/com/microsoft/azure/management/resources/implementation/ProvidersInner.java#L427

Let me know if this is a different issue that should be handled separately (it's not directly markdown related). I know in the past I've resolved these manually, but we really need to fix it in autorest.

**Comment by RikkiGibson** [comment]
Don't think so--it's just something we need to make time for on our side.

**Comment by JonathanGiles** [comment]
Ok, thanks. Please talk with your team about the priority of this work. Without a fix, generating JavaDoc for some projects fails, which is a major issue blocking a great developer experience.

**Comment by JonathanGiles** [comment]
@RikkiGibson I was told by @selvasingh that this is now resolved and this issue is a duplicate issue of the fixed issue. Are you able to point me to the issue where this was resolved so that we can close this as a duplicate? Thanks.

**Comment by RikkiGibson** [comment]
Hi Jonathan. I've actually moved teams but it's possible Asir was thinking of issue https://github.com/Azure/autorest.java/issues/262? At a glance can't find anything that references the actually malformed JavaDoc, and not merely the missing `@params` and `@return` tags.

**Comment by lmazuel** [comment]
Assigning to @anuchandy for now, will discuss it tomorrow at scrum planning
