### ISSUE TITLE
Feature request: Client builders validate required parameters to build the client

### ISSUE THREAD

**Issue by billwert** [Azure/autorest.java#2719]
Today, `build(Async)Client()` method implementations on builders for service clients do not validate any state. This results in it being possible to build a client that will error when a service call is made. 

Given this:
```
@server("https://example.com/{route}", "My endpoint", {
    route: string,
    otherVar?: string
})
```
I would expect `buildClient()` to throw `InvalidStateException` if I hadn't called `setRoute(...)`.

I'm not entirely sure that optional parameters for services make sense but tsp doesn't complain about it. :)

**Comment by weidongxu-microsoft** [comment]
1st iterate on design https://github.com/Azure/azure-sdk-for-java/pull/39889/files
Would sync with Srikanta next week.
