### ISSUE TITLE
mgmt azure-json, `fromJson` cannot access read-only property from `Resource`

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2740]
## Issue
* part of https://github.com/Azure/azure-sdk-for-java/issues/38333
* also discussed in https://github.com/Azure/azure-sdk-for-java/pull/38322#discussion_r1455151628
*  `withId()` is generated in `fromJson` implementation, despite that it's not present on `Resource` or `ProxyResource`
* `id`, `name`, etc... in `Resource` cannot be accessed in child classes

Current generated code: 
```java
if ("id".equals(fieldName)) {
    deserializedDedicatedHostGroupInner.withId(reader.getString());
} else if ("name".equals(fieldName)) {
    deserializedDedicatedHostGroupInner.withName(reader.getString());
} else if ("type".equals(fieldName)) {
    deserializedDedicatedHostGroupInner.withType(reader.getString());
}
```

### Pros
1. Seemingly the most simple to implement. In fact, current codegen's working like magic as it assumes setter methods on parent classes. There's not much(if not none) codegen work involved.
### Cons
1. Protected setter methods are exposed though all `Resource`/`ProxyResource`'s subclasses.
### Pros
1. Exposed less amount(1 vs 3) protected methods than the setter
2. Preserves the "read-only" nature of these properties, compared to "setter"
### Cons
1. Protected constructor is exposed any way.
3. mgmt doesn't have constructors with parameters for now
4. Way more things to implement than protected setters. 
### Pros
1. No unnecessary exposed methods/properties
2. No core dev work
3. Potentially consistent with general case: https://github.com/Azure/autorest.java/issues/2741
### Cons
1. Duplicated shadowing properties across all inheritance hierarchy, making subclasses potentially cumbersome.
2. More dev work in codegen than protected setter approach.
### Pros
1. No exposed protected methods/constructors
### Cons
1. Violates the [Accessor Helper design](https://github.com/Azure/azure-sdk-for-java/wiki/Access-helpers#design), where the helper should be in implementation. 
> Access helpers are defined in implementation packages and should be defined in the package implementation.accesshelpers
2. Similar as above, instead of exposing protected methods, it exposes unnecessary public Accessor Helper class.

## Personal preference
From API's perspective, I prefer solution 3, which is the shadowing approach. It doesn't expose unnecessary APIs. Additionally, this may be consistent with the general case https://github.com/Azure/autorest.java/issues/2741, e.g. if the property is from parent and no public setter available, we shadow/duplicate it in child classes. 
Haven't dived deep into each of the implementation. I assume all the solutions except solution 1(protected setters) involve getting some information of the base class(`Resource`/`ProxyResource`) to determine property's access pattern.

**Comment by weidongxu-microsoft** [comment]
My vote probably on 3 as well. But please also initiate the discussion in channel.
