### ISSUE TITLE
[MPG] ExpandableEnum as discriminator is not generated

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2767]
compilation failure: https://github.com/XiaofeiCao/azure-sdk-for-java/pull/17/commits/9bef3650892e4754002563a84809118812509065#diff-7264e9e87a569c0f37901484ed4594085f26e67f12b642642d6f37127ab65580

**Comment by weidongxu-microsoft** [comment]
It seems also been removed by schema clean-up?

Add objectSchema.discriminator to schemaInUse?
