### ISSUE TITLE
[MPG] Empty models in tsp, what should we generate

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2779]
tsp: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/devopsinfrastructure/Microsoft.DevOpsInfrastructure/main.tsp#L314-L315

converted swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/devopsinfrastructure/resource-manager/Microsoft.DevOpsInfrastructure/preview/2024-04-04-preview/devopsinfrastructure.json#L1511-L1514

TCGC issue: https://github.com/Azure/typespec-azure/issues/846
copied from the issue: 
| Swagger | m4 | TypeSpec | TCGC |
| --- | --- | --- | --- |
| `{"type": "object"}` | `anyObject` | `{}` | anonymous model with no properties |
| `{"type": "object"}` | `anyObject` | `model EmptyModel {}` | named model with no properties |
| `{}` | `any` | `unknown` | `any` |

Considerations:
We probably need to check what code-model would it be, if it is
1. {} from tsp
2. model Model {} from tsp
Is it only anonymous model vs named model? Do we want to generate them both as empty class (DPG would do this)?
 
And can we distinguish this "empty model" from typespec, from e.g. "type": "object" from Swagger?

**Comment by XiaofeiCao** [comment]
> Is it only anonymous model vs named model?

From code-model point of view, it is. The generated code-model is the same. Though TCGC's result contains `isGeneratedName` for SdkModelType:
<img width="198" alt="Screenshot 2024-07-11 at 18 31 49" src="https://github.com/Azure/autorest.java/assets/92354331/0579f377-0902-4448-a313-4f8055106c0b">

> And can we distinguish this "empty model" from typespec, from e.g. "type": "object" from Swagger?

I'm not sure if TCGC has a way to represent `anyObject` in M4. If it has, we can modify our old M4 logic to detect `anyObject`(instead of treating it as `AnySchema`). If not, guess we can't.

**Comment by XiaofeiCao** [comment]
Discussion here: https://github.com/Azure/typespec-azure/issues/846#issuecomment-2224310829
> 1. Empty model in TypeSpec means model without properties, not `anyObject`. 
> 2. For brownfields, by default we convert `anyObject` as TypeSpec (anonymous)empty model. If service really wants `anyObject`, TypeSpec's equivalence is `Record<unknown>`.

@weidongxu-microsoft Guess for TypeSpec greenfield in MPG, we treat anonymous/named empty model as empty class. While for brownfields(since by default they convert `anyObject` to anonymous empty model), we treat them as `Object` to avoid breaking change?

**Comment by weidongxu-microsoft** [comment]
I think for tsp, empty model generate empty class.

Compatibility with brownfield is another topic. And we may not need exact same result (one reason is that m4 don't return empty model in the first place, and we likely won't solve that).

**Comment by XiaofeiCao** [comment]
Makes sense.
Guess we first extend ObjectMapper in TypeSpec: https://github.com/Azure/autorest.java/blob/b8d4f4d00f598ea463f1f5ce7e2749c539489422/javagen/src/main/java/com/azure/autorest/mapper/ObjectMapper.java#L86

And do a case by case for brownfields in the future.
