### ISSUE TITLE
Generated code is missing imports

### ISSUE THREAD

**Issue by hovsepm** [Azure/autorest.java#278]
https://github.com/Azure/azure-sdk-for-java/pull/2172 

`
[[1;31mERROR[m] COMPILATION ERROR : 
[[1;34mINFO[m] -------------------------------------------------------------
[[1;31mERROR[m] /home/travis/build/Azure/azure-sdk-for-java/applicationinsights/resource-manager/v2015_05_01/src/main/java/com/microsoft/azure/management/applicationinsights/v2015_05_01/implementation/WorkItemConfigurationsInner.java:[337,50] cannot find symbol
  symbol:   method items()
  location: class com.microsoft.azure.management.applicationinsights.v2015_05_01.implementation.WorkItemConfigurationInner
[[1;31mERROR[m] /home/travis/build/Azure/azure-sdk-for-java/applicationinsights/resource-manager/v2015_05_01/src/main/java/com/microsoft/azure/management/applicationinsights/v2015_05_01/implementation/ApplicationInsightsComponentFavoriteImpl.java:[37,75] cannot find symbol
  symbol:   method id()
  location: variable inner of type com.microsoft.azure.management.applicationinsights.v2015_05_01.implementation.ApplicationInsightsComponentFavoriteInner
[[1;31mERROR[m] /home/travis/build/Azure/azure-sdk-for-java/applicationinsights/resource-manager/v2015_05_01/src/main/java/com/microsoft/azure/management/applicationinsights/v2015_05_01/implementation/ApplicationInsightsComponentFavoriteImpl.java:[38,70] cannot find symbol
  symbol:   method id()
  location: variable inner of type com.microsoft.azure.management.applicationinsights.v2015_05_01.implementation.ApplicationInsightsComponentFavoriteInner
[[1;31mERROR[m] /home/travis/build/Azure/azure-sdk-for-java/applicationinsights/resource-manager/v2015_05_01/src/main/java/com/microsoft/azure/management/applicationinsights/v2015_05_01/implementation/ApplicationInsightsComponentFavoriteImpl.java:[39,68] cannot find symbol
  symbol:   method id()
  location: variable inner of type com.microsoft.azure.management.applicationinsights.v2015_05_01.implementation.ApplicationInsightsComponentFavoriteInner
[[1;31mERROR[m] /home/travis/build/Azure/azure-sdk-for-java/applicationinsights/resource-manager/v2015_05_01/src/main/java/com/microsoft/azure/management/applicationinsights/v2015_05_01/implementation/ApplicationInsightsComponentFavoriteImpl.java:[69,28] cannot find symbol
  symbol:   method id()
  location: class com.microsoft.azure.management.applicationinsights.v2015_05_01.implementation.ApplicationInsightsComponentFavoriteInner
[[1;34mINFO[m] 5 errors 
[[1;34mINFO[m] -----------------
`

**Comment by rickle-msft** [comment]
Storage SDKs are also noticing this issue. The only missing import for us is OffsetDateTime in the Generated clients. Once I manually import it, everything works fine, but it is consistently left off every time we generate.

**Comment by jianghaolu** [comment]
Please open new issue with more details if this is still an issue.
