### ISSUE TITLE
Sample generation Implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2808]

**Comment by weidongxu-microsoft** [comment]
mostly done
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/standbypool/azure-resourcemanager-standbypool/src/samples/java/com/azure/resourcemanager/standbypool/generated/StandbyContainerGroupPoolsCreateOrUpdateSamples.java

**Comment by weidongxu-microsoft** [comment]
Java will move to TCGC operation samples (let TCGC load the JSON).

The fine part will not be TCGC. This is in Java, and lots of specific logic there (e.g. mgmt has a different client and interfaces that is totally different from DPG).

**Comment by weidongxu-microsoft** [comment]
update due to TCGC behavior change
https://github.com/Azure/autorest.java/pull/2924
https://github.com/Azure/azure-sdk-tools/pull/8854
