### ISSUE TITLE
[versioning] add clear doc to inform customer risk to set api-version other than the latest one 

### ISSUE THREAD

**Issue by chunyu3** [Azure/autorest.java#2819]
Add an api-version section in SDK readme as following:
![image](https://github.com/Azure/autorest.java/assets/10458143/7194ee6a-5838-4dcc-929d-5d19d9dfc42d)

refer to https://github.com/Azure/autorest.csharp/tree/feature/v3/test/TestProjects/sdk/newprojecttypespec/Azure.NewProject.TypeSpec#service-api-versions

If you have capability to send the customized http request, you can add separate section on the bottom to guide customer how to send the rest api if there are breaking changes and current SDK API is not valid for a special api-version.

**Comment by weidongxu-microsoft** [comment]
@srnagar Any opinion?

We can add this section the README template for DPG.

**Comment by srnagar** [comment]
I am fine with adding this template to our READMEs. I would include this as part of the "Examples" section (after "Key Concepts") to show the code snippet on how to set the service version.
