### ISSUE TITLE
tsp, cadl-ranch add test case for ARM

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2822]
<img width="982" alt="Screenshot 2024-06-18 at 14 38 57" src="https://github.com/Azure/autorest.java/assets/92354331/894b3a7f-2314-4a93-89be-8de4eb61fa7b">

For ARM case, we may need to set the `AzureEnvironment`'s endpoint to `localhost:3000`, and use empty HttpPipeline:
```java
Map<String, String> endpoints = new HashMap<>();
endpoints.put("managementEndpointUrl", "http://localhost:3000");
endpoints.put("resourceManagerEndpointUrl", "http://localhost:3000");
AzureEnvironment azureEnvironment = new AzureEnvironment(endpoints);
HttpPipeline httpPipeline = new HttpPipelineBuilder().build();
XXManager manager = XXManager
        .authenticate(httpPipeline, new AzureProfile(azureEnvironment));

```

**Comment by v-hongli1** [comment]
Added test cases and merged they into main branch.
