### ISSUE TITLE
SDK azure-for-java check failing

### ISSUE THREAD

**Issue by htippanaboya** [Azure/autorest.java#2833]
Only SDK azure-for-java check failing in https://github.com/Azure/azure-rest-api-specs/pull/27034
All other sdk checks are passing successfully.

**Comment by weidongxu-microsoft** [comment]
Java is success?

https://github.com/Azure/azure-rest-api-specs/pull/27034/checks?check_run_id=19630539641

**Comment by weidongxu-microsoft** [comment]
OK, seems this
https://github.com/weidongxu-microsoft/autorest.java_ci/actions/runs/9634796973/job/26570877724#step:11:18113

**Comment by weidongxu-microsoft** [comment]
reason is the directive for renaming the operation group
https://github.com/Azure/azure-rest-api-specs/pull/29552
