### ISSUE TITLE
[mgmt] Remove `EnableBatchRelease` in ci.yml

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/autorest.java#2846]
It's been removed. We should update codegen.
https://github.com/Azure/azure-sdk-for-java/commit/14b17fac7456ba84df914cc73e970802e6342fa4#diff-85a473057c563d08e2f516aa1fa1df3fe982fd142b52626aa95a5f581c235085

**Comment by weidongxu-microsoft** [comment]
ci.yml is from script in eng/mgmt/automation
