### ISSUE TITLE
Support AllowReserved in Path Implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2896]

**Comment by weidongxu-microsoft** [comment]
reopen

Find our current implementation of x-ms-skip-url-encoding is not same as the URI template [Reserved Expansion](https://datatracker.ietf.org/doc/html/rfc6570#section-3.2.3).

When input is `/foo/bar/a b`, ours appears to keep it same, while URI template would give `/foo/bar/a%20b`

**Comment by weidongxu-microsoft** [comment]
Currently use same impl of `x-ms-skip-url-encoding`.

If we need to improve. it likely be same for both.
