### ISSUE TITLE
tsp, honor name for Enum in TypeSpec

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/autorest.java#2940]
For ARM, we didn't use the name for Enum
https://github.com/Azure/autorest.java/blob/main/javagen/src/main/java/com/azure/autorest/mapper/MapperUtils.java#L58-L66

We'd better use it for TypeSpec.

For impl, I guess a subclass, with a flag to util function?

**Comment by XiaofeiCao** [comment]
Yes, we should adopt TypeSpec. For swagger, we remain the same.

**Comment by weidongxu-microsoft** [comment]
BTW, the reason of the special handling for Swagger is that m4 would generate a name from the enum value (but we cannot distinguish whether the name is generated, or from x-ms-enum). And that name would already be processed and in many cases is worse that the enum value.
