### ISSUE TITLE
Namespace refactoring Implementation

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest.java#2968]

**Comment by weidongxu-microsoft** [comment]
design
- https://gist.github.com/srnagar/a695faa1a4d8a5dbf44af826f05916f0

depends
- https://github.com/Azure/typespec-azure/issues/1604
- fix in typespec about the namespace of template instance (it should be the namespace of where instantiation happens)

**Comment by weidongxu-microsoft** [comment]
Java design (base on TCGC `.namespace`)

## Azure

- Client classes would be under `<tcgc_namespace>`
- Model/enum classes would be under `<tcgc_namespace>.models`
- Internal model/enum classes would be under `<tcgc_namespace>.implementation.models`

## Unbranded

- Client/model/enum classes would be under `<tcgc_namespace>`
- Internal model/enum classes would be under `<tcgc_namespace>.implementation`

**Comment by weidongxu-microsoft** [comment]
Migration plan for Azure

- `namespace` option would override the client namespace from TCGC
- new onboard should not have `namespace` option
- migrate existing lib, update client.tsp to add `@clientNamespace`, and remove `namespace` option

**Comment by weidongxu-microsoft** [comment]
Current limitation

- operation group be in same package of client
- subclient be in same package of client
