### ISSUE TITLE
Java Emitter should work correctly with no tspconfig file

### ISSUE THREAD

**Issue by lirenhe** [Azure/autorest.java#2989]
tspconfig is an optional file, it shouldn't be necessary. 
This is the required scenario for un-branded

Please ensure the following steps would not crash the emitter and generate the right SDK:

```
tsp init # Chose generic restapi
tsp install
npm install @typespec/http-client-java
tsp compile . --emit @typespec/http-client-java
```

**Comment by weidongxu-microsoft** [comment]
tested and current version already does this without tspconfig
