### ISSUE TITLE
SQL generated code uses getByVersionAsync instead of getAsync

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest.java#299]
See the manual fix https://github.com/Azure/azure-sdk-for-java/pull/2768/commits/28b0d2c48356d8ab7a252ba7e80072bd168e1109 in the PR https://github.com/Azure/azure-sdk-for-java/pull/2768

**Comment by jianghaolu** [comment]
Closing out old issues - feel free to reopen if it's still an issue.
