### ISSUE TITLE
AutoRest: Explore alternative approaches for paged results

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/autorest.java#302]
As present paged results are returned in PagedList<T> (for sync) and rx.Observable<Page<T>> (for async). This issue has been created to track the discussion around removing the concept of a page, instead enabling a developer to request more results using the standard backpressure mechanism found in recent reactive streams APIs (RxJava with Flowable, Reactor with Flux).

Is there a good argument against this approach?

**Comment by lmazuel** [comment]
@JonathanGiles please try to make it specific, with code example as snippet, etc. assuming Reactor.

**Comment by JonathanGiles** [comment]
Based on the chat with Reactor engineers, the advice was to not expose pagination and to simply enable backpressure. Here is sample code pointed out to us: https://github.com/cloudfoundry/cf-java-client/blob/master/cloudfoundry-util/src/main/java/org/cloudfoundry/util/PaginationUtils.java#L29

**Comment by jianghaolu** [comment]
This is now complete in track 2 codegen.
