### ISSUE TITLE
AutoRest: Explore migration to Project Reactor for next major release

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/autorest.java#303]
Project Reactor is JDK 8 based and presents a number of convenience APIs to support JDK 8 developers (ability to move to streams, create optionals, etc). It is also built upon reactive streams and supports operator fusion, etc and has been benchmarked to be extremely fast. Additionally, it provides a reactor-netty project that can provide a backpressure-ready network engine.

It would be good to have this issue track the discussion around moving to use this for the next generation for AutoRest output. The alternative, RxJava 2.x, is also a viable option, but it lacks the improved JDK 8 support and is not as advanced as project reactor is.

**Comment by lmazuel** [comment]
Assign this explicitly to @anuchandy who as a lot of thinking already on this

**Comment by jianghaolu** [comment]
v4 is based on project reactor now.
