### ISSUE TITLE
Review of and improvements to the Http pipeline runtime API

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/autorest.java#311]
The API of the Http pipeline API should be reviewed in light of our movements to reactor and a JDK 8 baseline to ensure we cannot find better approaches to simplify the APIs. This work will be guided by discussions around the future generation of Java data plane SDKs.

Design goals:

- Must ensure pipeline supports telemetry, logging, tracing, retries, cancellation, and auth.
- Must ensure default pipelines can be easily created.
- Must ensure that custom pipelines can be built with relative ease (and sane default values so that it must not be built from scratch).

**Comment by jianghaolu** [comment]
This is now part of our Track2 guidelines & generator.
