### ISSUE TITLE
Improvements to autorest tooling to side-load additional language-specific documentation

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/autorest.java#312]
It would be great to be able to maintain a single document per project that would map replacement documentation onto classes and methods, and when this mapping fails (because the generated code has changed) to fail the build or notify people in a meaningful way.

**Comment by lmazuel** [comment]
Documentation is out of scope of Autorest V3 for now, but I agree on the idea

**Comment by jianghaolu** [comment]
This is now available through customizations's javadoc customization features.
