### ISSUE TITLE
Duplicate file generation SensitivityLabels.java

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest.java#323]
Attempting to generate from Microsoft.Sql/preview/2017-03-01-preview/sensitivityLabels.json failed with 

```
FATAL: System.Exception: Duplicate File Generation: src/main/java/com/microsoft/azure/management/sql/v2017_03_01_preview/SensitivityLabels.java
   at AutoRest.Core.CodeGenerator.<Write>d__13.MoveNext() in /home/vsts/work/1/s/autorest.common/src/CodeGenerator.cs:line 151
-
``` 

The segment causing failure is:

/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/recommendedSensitivityLabels

**Comment by anuchandy** [comment]
Related failing PR: https://github.com/Azure/azure-rest-api-specs/pull/5148

**Comment by jianghaolu** [comment]
Please try the new v4 generator and reopen if it's still an issue.
