### ISSUE TITLE
Checkstyles: unused imports in generated classes

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/autorest.java#330]
Generated classes are triggering checkstyle's UnusedImports errors.

https://github.com/alzimmermsft/azure-sdk-for-java/blob/master/batch/data-plane/src/main/java/com/microsoft/azure/batch/protocol/Accounts.java#L21

**Comment by srnagar** [comment]
This is no longer an issue as we are using code formatter that removes unused imports from generated code.
