### ISSUE TITLE
[v1] Remove 1.6.5 version of test jar from pom template

### ISSUE THREAD

**Issue by anuchandy** [Azure/autorest.java#340]
When we released 1.6.6, the arm-client-runtime test jar `azure-arm-client-runtime-1.6.6-tests.jar` didn't get out. See [here](https://search.maven.org/classic/#search%7Cgav%7C1%7Cg%3A%22com.microsoft.azure%22%20AND%20a%3A%22azure-arm-client-runtime%22), there is no test.jar for 1.6.6 arm-client-runtime. 

(1). The `azure-arm-client-runtime-1.6.6-tests.jar` cannot be pushed to maven individually or 
(2).  All 1.6.6 packages cannot be pushed again together. 

Attempting 1 failed as it requires main src jar 

```
Missing: no main jar artifact found in folder '/com/microsoft/azure/azure-arm-client-runtime/1.6.6'
```
Attempting 2 failed with error:

```
Artifact updating: Repository ='releases:Releases' does not allow updating artifact='/com/microsoft/azure/azure-arm-client-runtime/1.6.6/azure-arm-client-runtime-1.6.6.jar'
```

Hence needs to wait for runtime 1.6.7 release. Meantime 1.6.5 version of test.jar is hardcoded in auto-rest [pom template](https://github.com/Azure/autorest.java/pull/341).

`azure-arm-client-runtime-1.6.6-tests.jar` was missed to push as part of 1.6.6 release due to an entry in bundler.properties file for runtime repro. This is fixed in this [PR](https://github.com/Azure/autorest-clientruntime-for-java/pull/605). With this fix, no special action is needed to include test jar when releasing 1.6.7.

**Comment by jianghaolu** [comment]
This seems to have been fixed in later releases.
