### ISSUE TITLE
Problems generating withTags for hanaonazure v2017-11-preview

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.java#344]
https://github.com/Azure/azure-rest-api-specs/pull/5466

Error:(93, 29) java: withTags(java.util.Map<java.lang.String,java.lang.String>) in com.microsoft.azure.management.hanaonazure.v2017_11_03_preview.implementation.HanaInstanceImpl cannot override withTags(java.util.Map<java.lang.String,java.lang.String>) in com.microsoft.azure.arm.resources.models.implementation.ResourceImpl overridden method is final

**Comment by jianghaolu** [comment]
Please reopen if this is still an issue in v4 generator.
