### ISSUE TITLE
Fix issue with PR :https://github.com/Azure/azure-rest-api-specs/pull/5565

### ISSUE THREAD

**Issue by praries880** [Azure/autorest.java#346]
Autogenerator is not working finse, its failing because of this :
https://github.com/Azure/azure-rest-api-specs/pull/5565/files#diff-379b990d6c53de239f2f2f1dff634494R1331

The error :
```
Processing batch task - {"tag":"package-2018-01-preview"} .
FATAL: System.NotImplementedException: Handling return type 'Map<String, Integer>' for OtherMethod is not implemented
   at AutoRest.Java.Azure.Fluent.Model.OtherMethod.get_InnerReturnType() in /home/vsts/work/1/s/src/azurefluent/Model/FluentCommon/OtherMethods/OtherMethod.cs:line 69
```

According to @jianghaolu the error is caused by ` the generator cannot handle return type as list of maps either` and `the generator is not able to handle a method that's not a CRUD method and that returns a Map`

**Comment by jianghaolu** [comment]
Please reopen if this is still an issue for v4 generator.
