### ISSUE TITLE
Autorest Content-Length/Other headers not case insensitive

### ISSUE THREAD

**Issue by bgklein** [Azure/autorest.java#348]
According to https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2 headers should be case insensitive, but @JsonProperty does not respect this. 

![image](https://user-images.githubusercontent.com/18502617/59222646-d825b200-8b7e-11e9-8d5d-0f055018ed03.png)

**Comment by lmazuel** [comment]
Hi @bgklein 
Do you have a suggestion of fix?
Thanks!

**Comment by bgklein** [comment]
Might be a better issue for the azure-sdk-for-java repo, but essentially there should be an option to ignore case on an ObjectHandler https://mtyurt.net/post/jackson-case-insensitive-deserialization.html . Looks like the java core sdk ends up going the route of just writing its own handlers for additionalProperties: https://github.com/Azure/azure-sdk-for-java/blob/d8a9937fc26b68329825e7bfb02130867f35cd33/core/azure-core/src/main/java/com/azure/core/implementation/serializer/jackson/AdditionalPropertiesDeserializer.java

Not the highest priority feature as this only came about due to us accidentally changing the capitalization in our swagger spec from content-length to Content-Length, but thought I'd bring it up since technically it should have been fine.

**Comment by alzimmermsft** [comment]
Closing this issue as `azure-sdk-for-java`'s Track 2 SDKs treat headers as case-insensitive when using Jackson:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/jackson/ObjectMapperFactory.java#L83

And newer versions of Autorest leverage new capabilities where Jackson is mostly removed when handling objects based on HTTP headers:

https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/implementation/jackson/ObjectMapperShim.java#L294
