### ISSUE TITLE
No InputStream import

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.java#349]
Running into this issue when generating automation 's v2018_06_30 API

**Comment by anuchandy** [comment]
@iscai-msft please provide more details as mentioned here: https://github.com/Azure/autorest.java/issues/356#issuecomment-505163489

**Comment by iscai-msft** [comment]
In files RunnooksImpl, Runnooks, RunnookDrafts, RunbookDraftsImpl

```java
    @Override
    public Observable<InputStream> getContentAsync(String resourceGroupName, String automationAccountName, String runbookName) {
        RunbooksInner client = this.inner();
        return client.getContentAsync(resourceGroupName, automationAccountName, runbookName)
    ;}
```

**Comment by jianghaolu** [comment]
Please reopen if this is still an issue in v4 generator.
