### ISSUE TITLE
Default parameter value is ignored

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#35]
From @tdjin

Hi,

I’ve noticed a issue in the generated java code for entity search. The “market” parameter should default to “en-us” in the search method if not specified but it currently defaults to null and gets an error from the API. Can whoever is the contact for the autorest java generator please take a look and let me know if it’s an actual issue or if I’m possibly generating the code incorrectly?

I’m using autorest version 2.0.4166, which I believe is the latest. EntitySearch.json is attached.
Command line: autorest --input-file="C:\Azure\azure-rest-api-specs\specification\cognitiveservices\data-plane\EntitySearch\v1.0\EntitySearch.json" --java --output-folder=srcjava --add-credentials --namespace=Microsoft.CognitiveServices.Search.EntitySearch.

[EntitySearch.json](https://github.com/Azure/autorest.java/files/1463090/EntitySearch.txt)

**Comment by daschult** [comment]
I noticed this issue and it has been fixed in v2.
