### ISSUE TITLE
WithTags overriding fails during Compute v2018_10_01 generation

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.java#353]
Error:(78, 40) java: withTags(java.util.Map<java.lang.String,java.lang.String>) in com.microsoft.azure.management.compute.v2018_10_01.implementation.ProximityPlacementGroupImpl cannot override withTags(java.util.Map<java.lang.String,java.lang.String>) in com.microsoft.azure.arm.resources.models.implementation.ResourceImpl
  overridden method is final

**Comment by jianghaolu** [comment]
Please reopen if this is still an issue for v4 generator.
