### ISSUE TITLE
Type argument not within bounds of GroupableResourceCoreImpl during Consumption v2018_10_01 generation

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.java#354]
Error:(18, 98) java: type argument com.microsoft.azure.management.consumption.v2018_10_01.implementation.ReservationRecommendationInner is not within bounds of type-variable InnerModelT

Occurs in both ReservationRecommendationImpl and RservationRecommendationsImpl during Consumption v2018_10_01 generation.

**Comment by jianghaolu** [comment]
Please reopen if this is still an issue for v4 generator.
