### ISSUE TITLE
Incompatible parameter types during Consumption v2018_11_01_preview generation 

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.java#355]
incorrect parameters passed to getPostOrDeleteResultWIthHeadersAsync
Error:(132, 39) java: method getPostOrDeleteResultWithHeadersAsync in class com.microsoft.azure.AzureClient cannot be applied to given types;
  required: rx.Observable<retrofit2.Response<okhttp3.ResponseBody>>,java.lang.reflect.Type,java.lang.Class<THeader>
  found: rx.Observable<retrofit2.Response<okhttp3.ResponseBody>>,com.microsoft.azure.LongRunningOperationOptions,java.lang.reflect.Type,java.lang.Class<com.microsoft.azure.management.consumption.v2018_11_01_preview.InvoicePricesheetDownloadHeaders>
  reason: cannot infer type-variable(s) T,THeader
    (actual and formal argument lists differ in length)

Occurs in both InvoicePricesheetsInner and BillingProfilePricesheetsInner

**Comment by anuchandy** [comment]
@iscai-msft - Additional info: Bug in azure generator not in lite generator. As i mentioned https://github.com/Azure/autorest.java/issues/356#issuecomment-505163489, the way we identify it is - file BillingProfilePricesheetsInner is not an interface or interface impl, its azure generator gened type.

**Comment by jianghaolu** [comment]
Please reopen if this is still an issue for v4 generator.
