### ISSUE TITLE
Import statements cut off half way during Data Factory v2018_06_01 generation

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.java#356]
Import statements are cut off half way, example being
```java
import com.microsoft.azure.management.datafactory.v2018_06_01.;
```

No actual type relies on this import statement though, as there are no unimported errors.

**Comment by anuchandy** [comment]
@iscai-msft could please one more information - 

Is this an error in lite or azure generator. The way to identify this is - if the file contains an interface or implementation of an interface then it is lite otherwise it is azure.

Please provide this info for all issues you're opening

**Comment by jianghaolu** [comment]
Please reopen if this is still an issue for v4 generator.
