### ISSUE TITLE
Generate for property such as `_rid`, `_etag` is not Java checkstyle friendly

### ISSUE THREAD

**Issue by yaohaizh** [Azure/autorest.java#375]
For CosmodDB spec, there are some properties starting with `_`
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/cosmos-db.json

The generated member name, method name and parameter name cannot pass checkstyle's check by default.

**Comment by jianghaolu** [comment]
Please reopen if this is still an issue for v4 generator.
