### ISSUE TITLE
withTags cannot override error during CognitiveServices v2017_04_18 generation

### ISSUE THREAD

**Issue by iscai-msft** [Azure/autorest.java#379]
Error:(125, 41) java: withTags(java.util.Map<java.lang.String,java.lang.String>) in com.microsoft.azure.management.cognitiveservices.v2017_04_18.implementation.CognitiveServicesAccountImpl cannot override withTags(java.util.Map<java.lang.String,java.lang.String>) in com.microsoft.azure.arm.resources.models.implementation.ResourceImpl
  overridden method is final

```java
@Override
    public CognitiveServicesAccountImpl withTags(Map<String, String> tags) {
        this.utags = tags;
        return this;
    }
```

Unsure about what is causing this error, looked at CognitiveServicesAccountInner and that extends from Resource.

**Comment by jianghaolu** [comment]
Please reopen if this is still an issue for v4 generator.
