### ISSUE TITLE
Performance issue on generating network service in batch

### ISSUE THREAD

**Issue by PhoenixHe-TSP** [Azure/autorest.java#393]
https://github.com/Azure/azure-rest-api-specs/pull/7427/checks?check_run_id=252805169

![image](https://user-images.githubusercontent.com/2346051/66456487-5f892080-eaa0-11e9-9eb9-3706f1d95ea1.png)

![image](https://user-images.githubusercontent.com/2346051/66456875-6c5a4400-eaa1-11e9-90f2-6bddf6217e10.png)

Currently the network service needs more than 3 hours to run autorest which is unacceptable. Other SDK cost less than 1 hour so please improve the performance.

**Comment by zikalino** [comment]
this isssue should be prioritized as it makes swagger reviews / merging significantly slower

**Comment by NullMDR** [comment]
I'm working on a solution that only run against tags that has changed input file, Meanwhile the performance issue is still a thing.

**Comment by alzimmermsft** [comment]
@PhoenixHe-TSP I believe this can be closed as I've looked through some recent runs of SDK azure-sdk-for-java in azure-rest-api-specs and this doesn't appear to be an issue anymore

**Comment by weidongxu-microsoft** [comment]
that might be v1 codegen with multi-api (which basically run 20+ times for e.g. network).

currently track2 no longer support multi-api.
