### ISSUE TITLE
Generate code for body-formdata, formdata-urlencoded.json

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#417]

**Comment by weidongxu-microsoft** [comment]
```
FATAL: Error: Not able to process media type multipart/form-data at this moment.
  Error: Plugin modelerfour reported failure.
```

Same for 4.1.60

**Comment by jianghaolu** [comment]
@weidongxu-microsoft  feel free to report these errors on our Teams channel called "AutoRest - Engineering" https://teams.microsoft.com/l/channel/19%3a987876ab02634aaeaded0fb0de9f338a%40thread.skype/AutoRest%2520-%2520Engineering?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47

**Comment by mayurid** [comment]
@weidongxu-microsoft : Please report these issue on the modelerfour repo: https://github.com/Azure/autorest.modelerfour/issues and post it here.

**Comment by weidongxu-microsoft** [comment]
It's already there. https://github.com/Azure/autorest.modelerfour/issues/28

**Comment by weidongxu-microsoft** [comment]
@jianghaolu Do you know whether azure core support multipart/form-data now? The issue from modelerfour is fixed, but I seems not finding azure core support for multipart/form-data.

**Comment by jianghaolu** [comment]
I don't think so - I think only x-www-form-urlencoded is supported for now. Opened an issue at https://github.com/Azure/azure-sdk-for-java/issues/8702

**Comment by weidongxu-microsoft** [comment]
multipart/form-data is still not supported in azure-core
