### ISSUE TITLE
Support poller

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#426]

**Comment by jianghaolu** [comment]
pending https://github.com/Azure/azure-sdk-for-java/pull/6303

**Comment by weidongxu-microsoft** [comment]
Experimental implementation, not production ready.
https://github.com/weidongxu-microsoft/autorest.java/commit/d3390562eb10cf6d4d5ab2fbd2ecb14eade64e4a

**Comment by weidongxu-microsoft** [comment]
Code in PR https://github.com/weidongxu-microsoft/autorest.java/tree/v4_fluentgen

**Comment by weidongxu-microsoft** [comment]
LRO supported via https://github.com/Azure/autorest.java/pull/460
