### ISSUE TITLE
Generate separate clients for sync and async APIs

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#514]
V4 codegen generates a single service client with both sync and async APIs. Instead, create two separate sync and async client classes.

**Comment by weidongxu-microsoft** [comment]
If possible could we have an option for it? Switching at this stage would cost fluent lots of code changes (on code that already calling the combined client).

**Comment by weidongxu-microsoft** [comment]
I am OK if you need Fluent mgmt add a wrapper for separate clients (it might be easier than having a option to switch). Just let me know your plan, so I can plan accordingly.

**Comment by jianghaolu** [comment]
Separate clients are generated today.
