### ISSUE TITLE
Fix checkstyle issues in generated code

### ISSUE THREAD

**Issue by srnagar** [Azure/autorest.java#515]
- Remove unused imports
- Line length should be less than 120 chars
- Add `@ServiceClient` annotation to service client
- Remove public methods that don't have any implementation

**Comment by weidongxu-microsoft** [comment]
Currently we've got these in mgmt generated code (only sample of different kinds of checkstyle error). I will start to fix some (other than 120char, which seems easier to pass through a formatter).

@jianghaolu @srnagar Let me know whether any of below could be conflicting with data-plane code. (I think we are using same checkstyle config in azure-sdk-for-java)

```
[ERROR] C:\github\azure-sdk-for-java\sdk\resources\mgmt\src\main\java\com\azure\management\resources\models\ResourceManagementClientBuilder.java:105:5: @ServiceClientBuilder class should not have a method name, 'build' starting with 'build' but not ending with 'Client'. [ServiceClientBuilder]
[ERROR] C:\github\azure-sdk-for-java\sdk\resources\mgmt\src\main\java\com\azure\management\resources\models\ResourceManagementClientImpl.java:97:5: Field "httpPipeline" is only assigned in constructor and it is not final. You should consider making the field final, or suppressing the warning. [EnforceFinalFields]
[ERROR] C:\github\azure-sdk-for-java\sdk\resources\mgmt\src\main\java\com\azure\management\resources\models\ResourceManagementClientImpl.java:153:5: Field "resources" is only assigned in constructor and it is not final. You should consider making the field final, or suppressing the warning. [EnforceFinalFields]
[ERROR] C:\github\azure-sdk-for-java\sdk\resources\mgmt\src\main\java\com\azure\management\resources\models\ResourceManagementClientImpl.java:210: Line is longer than 120 characters (found 143). [LineLength]
[ERROR] C:\github\azure-sdk-for-java\sdk\resources\mgmt\src\main\java\com\azure\management\resources\models\ResourcesInner.java:49:5: Field "service" is only assigned in constructor and it is not final. You should consider making the field final, or suppressing the warning. [EnforceFinalFields]
[ERROR] C:\github\azure-sdk-for-java\sdk\resources\mgmt\src\main\java\com\azure\management\resources\models\ResourcesInner.java:54:5: Field "client" is only assigned in constructor and it is not final. You should consider making the field final, or suppressing the warning. [EnforceFinalFields]
[ERROR] C:\github\azure-sdk-for-java\sdk\resources\mgmt\src\main\java\com\azure\management\resources\models\ResourcesInner.java:62: Line is longer than 120 characters (found 121). [LineLength]
[ERROR] C:\github\azure-sdk-for-java\sdk\resources\mgmt\src\main\java\com\azure\management\resources\models\ResourcesInner.java:72:5: The 'name' property of @ServiceInterface, 'ResourceManagementClientResources' should be non-empty, alphanumeric and not more than 10 characters [ServiceInterface]
[ERROR] C:\github\azure-sdk-for-java\sdk\resources\mgmt\src\main\java\com\azure\management\resources\models\ResourcesInner.java:230: Expected @return tag. [JavadocMethod]
```

**Comment by weidongxu-microsoft** [comment]
Considering adding a same checkstyle to vanilla-tests and fluent-tests, though the one in azure-sdk-for-java got a self-build plugin `sdk-build-tools` in its own repo. Maybe we can just do without this one.

Anyway that is TODO after some of these get solved.

**Comment by weidongxu-microsoft** [comment]
Should we change `build()` to `buildClient()`? (I aware it could conflict with buildAsyncClient/buildClient)

**Comment by weidongxu-microsoft** [comment]
For `@return` javadoc, I will first try to use operation description if it starts with "get " or "gets ", then fallback to generic description on IType as in track1.

Let me know if there is better idea.

**Comment by weidongxu-microsoft** [comment]
google-java-format requires Java 11

I didn't find alternative.

**Comment by srnagar** [comment]
>Let me know whether any of below could be conflicting with data-plane code. (I think we are using same checkstyle config in azure-sdk-for-java)

Yes, we use the same checkstyle. So, no conflicting changes here.

> BTW, how do data-plane currently deal with these checkstyle issues, after code generated?

We have `checkstyles-suppression.xml` in where we add checkstyle exceptions to generated code.

> Should we change build() to buildClient()? (I aware it could conflict with buildAsyncClient/buildClient)

Yes, we should change `build()` to `buildClient()` if separate sync/async clients are not generated. If separate sync/async clients are generated, then we can call this `buildInnerClient()`. Thoughts?

> google-java-format requires Java 11

They removed the support for JDK 8 recently. Worth trying with JDK 8.

**Comment by weidongxu-microsoft** [comment]
Modified on comment.

There be 3 places worth noting:
1. Length limit of 20 on service interface name is hardcoded, and done by a simple truncate. This could cause same name after truncated. But I haven't get confirmation whether this would affect anything. https://github.com/Azure/autorest.java/blob/v4/javagen/src/main/java/com/azure/autorest/template/ProxyTemplate.java#L43
2. Length break for long URL is currently only done in fluentgen (again, with 120 hardcoded) https://github.com/Azure/autorest.java/blob/v4/fluentgen/src/main/java/com/azure/autorest/fluent/template/FluentProxyTemplate.java#L54
```
        @Head(
            "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}/providers"
                + "/{resourceProviderNamespace}/{parentResourcePath}/{resourceType}/{resourceName}")
```
3. Re-format by modified google-java-format is only done in fluentgen. It uses reflection so it will not affect on java 8 compile/runtime. We are still refining the modified lib by applying it on manual code https://github.com/Azure/autorest.java/blob/v4/fluentgen/src/main/java/com/azure/autorest/fluent/checker/JavaFormatter.java#L50

**Comment by weidongxu-microsoft** [comment]
It seems google-java-format 1.7 is still using java 8. I will try it a bit later.

**Comment by weidongxu-microsoft** [comment]
Also added this stupid function in fluentgen to break overlong string literal (like the URL in @Post).
It is not generic or even 100% correct, but still would do for most cases...

https://github.com/Azure/autorest.java/blob/v4/fluentgen/src/main/java/com/azure/autorest/fluent/checker/JavaFormatter.java#L72

```
        @Post(
            "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Network"
                + "/networkInterfaces/{networkInterfaceName}/effectiveRouteTable")
```
