### ISSUE TITLE
Support custom headers on method parameters

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#567]
In .NET they are generating
![MicrosoftTeams-image](https://user-images.githubusercontent.com/2320445/78391670-ac573b00-759b-11ea-8cf4-378ea659ab3f.png)

And we need to support that too in Java.

In azure-core there's a `HeaderCollection` annotation but it seems to require a common prefix. We will need to extend that.

**Comment by jianghaolu** [comment]
Customer opened issue in autorest repo: https://github.com/Azure/autorest/issues/3472

**Comment by alzimmermsft** [comment]
Closing as there is support for this using `Context` in the service client request.
