### ISSUE TITLE
Import HttpResponseException instead of ErrorResponseException

### ISSUE THREAD

**Issue by samvaity** [Azure/autorest.java#577]
Use `HttpResponseException` instead of `ErrorResponseException` form  `@UnexpectedResponseExceptionType` when generating the client code.

**Comment by srnagar** [comment]
This is generated as per [Swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.0/FormRecognizer.json). If there are error response types defined in the swagger for operations, AutoRest will annotate the proxy methods with those exceptions.

**Comment by weidongxu-microsoft** [comment]
A note (not related to this issue): mgmt plane might try to integrate with e.g. `ResourceNotFoundException` under https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/core/azure-core/src/main/java/com/azure/core/exception

But without multiple inheritance, it seems not easy to make a exception both `ResourceNotFoundException` and `ErrorResponseException`.

**Comment by weidongxu-microsoft** [comment]
A bit update on https://github.com/Azure/autorest.java/issues/582 (currently only for mgmt)
