### ISSUE TITLE
Improve class names in plural form

### ISSUE THREAD

**Issue by idear1203** [Azure/autorest.java#607]
Some class names in plural form are not good enough. It seems like current code generator simply add "s" behind the word.

Examples:
1. [DirectorysImpl](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/implementation/DirectorysImpl.java)
2. [SparkBatchsImpl](https://github.com/idear1203/azure-sdk-for-java-pr/blob/synapse_java_track_2_sdk/sdk/synapse/azure-analytics-synapse-spark/src/main/java/com/azure/analytics/synapse/spark/implementation/SparkBatchsImpl.java)

**Comment by weidongxu-microsoft** [comment]
A potential lib to get proper plural form. https://github.com/atteo/evo-inflector
Not tried yet.

**Comment by weidongxu-microsoft** [comment]
Another lib is
```
<dependency>
      <groupId>org.jibx</groupId>
      <artifactId>jibx-tools</artifactId>
      <version>1.3.3</version>
    </dependency>
```
