### ISSUE TITLE
Share serializer across method group clients

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#616]
Today we are creating a new serializer for each method group client but we should allow configuring a serializer on the service client builder and share it across the method group clients underneath this service client.

Example: 
at https://github.com/Azure/autorest.java/blob/v4/vanilla-tests/src/main/java/fixtures/url/Paths.java#L41 - we can pass a serializer as the 3rd parameter from the service client.

**Comment by conniey** [comment]
Yay! you're the best. :D

**Comment by srnagar** [comment]
Fixed in https://github.com/Azure/autorest.java/pull/669
