### ISSUE TITLE
Java post transformations in AutoRest

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#617]
## Issue
Some AutoRest.Java customers are not happy with the output Java code and want to make changes. Today they are doing the transformations in README in TypeScript and the experience is less than ideal.

## Why not...
**Q: Fix the generator to generate what they want?**
A: Some of the fixes they do are context specific, and require human input. AutoRest.Java v4 doesn't yet have AI built in. In some cases where our customers prefer one style over another, we simply can't make everyone happy out of the box.

**Q: Add dials and knobs (commandline arguments) to control output behavior?**
A: Some common requests or changes that require lots of transformations should absolutely be done by us and the users should be handed with a simple switch. But some are simple few-line changes that if added to AutoRest.Java, we will have a hundred commandline arguments. This not only makes many options less discoverable at least, it also gets AutoRest.Java contributor lost among the available features.

**Q: Add extensions to Swagger?**
A: For features that apply to other languages, yes, we will propose additions to current extensions or features in modeler four. But this proposal is focused on Java specific output changes.

**Q: Change output code directly after generation?**
A: As a contributor to AutoRest, I'm happy to take this solution :) But my conscience tells me to come up with a solution.

**Q: Write a convenience layer wrapping the output code?**
A: This is a viable solution and has been working well for some services. But we've seen some big models that require only one small change, that are deplicating lots of code. We want to offer a way to easily find the place to fix the small issue in the generated code.

**Q: Learn how to write TypeScript transformations in README?**
A: It's a steep learning curve for many Java developers who just want to generate some Java code and move on with their life. Also, the find-replace way to transform is not very definitive. We intend to replace it with a more definitive way to locate the code to modify and easily modify it.

### A post processor in the generation pipeline

Today we have a pipeline that generates Java code:
```
-> AutoRest Core (reads swagger)
-> ...
-> modeler four (outputs code model)
-> preprocessor (outputs modified code model)
-> javagen (outputs Java files)
```

We will add a step to allow changes to the final Java files. But text operations on the Java files directly are prune to errors and gives up lots of convenience in syntax processing and style processing in `javagen`. Thus the operations will be done on the DSL describing the files rather than the output files.
```
-> AutoRest Core (reads swagger)
-> ...
-> modeler four (outputs code model)
-> preprocessor (outputs modified code model)
-> javagen (outputs Java DSL)
-> postprocessor (outputs Java DSL)
-> javawriter (outputs Java files)
```

### An object based DSL
Luckly we already have [a set of DSL for Java files](https://github.com/Azure/autorest.java/tree/v4/javagen/src/main/java/com/azure/autorest/model/javamodel) in our code base. They are currently String based and it should be a simple coversion to make them object based with `toString()` method handling the conversion to String. This way we can still preview the output in the Debug window.

The structure looks like this today:
```
JavaLibrary
|- JavaPackage
  |- JavaFile
    |- JavaInterface
      |- JavaMethod
      |- JavaMethod
      ...
  |- JavaFile
    |- JavaClass
      |- JavaMemberVariable
      |- JavaMemberVariable
      |- JavaMethod
          |- JavaIfBlock
          |- JavaElseBlock
          ...
      |- JavaMethod
      ...
|- JavaPackage
  |- JavaFile
    |- JavaEnum
  ...
```

An example:
```
FooService
|- com.azure.foo
  |- FooClient.java
    |- FooClient
      |- createFoo()
      |- deleteFoo()
      ...
  |- FooClientBuilder.java
    |- FooClientBuilder
      |- HttpPipeline httpPipeline
      |- String connectionString
      |- httpPipeline(HttpPipeline)
      |- build()
        |- if (connectionString != null) { ... }
        |- else { ... }
      ...
|- com.azure.foo.models
  |- FooType.java
    |- FooType
      |- TYPE_A
      |- TYPE_B
      ...
  ...
```

Users will have access to the top level packages and make modifications on the DSL objects.

### Modifying the DSL in the post processor

Users don't have to learn how to add a plugin into the AutoRest pipeline. AutoRest Java will create a post processing pipeline, which will accept an implementation of `JavaModelProcessor`
```java
public interface JavaModelProcessor {
    public JavaLibrary process(JavaLibrary javaLibrary);
}
```

AutoRest Java will load the implementation class at runtime and process in our post processor.

### An example usage

```java
public class SearchServiceProcessor {
    public JavaLibrary process(JavaLibrary javaLibrary) {
        JavaPackage models = javaLibrary.getPackage("com.azure.search.models");
        JavaClass document = models.getFile("Document.java").getJavaClass();
        JavaMethod hasValueGetter = document.getMethod("isHasValue");
        document.publicMethod(hasValueGetter.visibility, hasValueGetter.returnType, "hasValue", hasValueGetter.parameters, hasValueGetter.methodBlock());
        document.removeMethod(hasValueGetter);
    }
}
```

## Tasks

1. Convert the current DSLs to be Object based, adding necessary methods to interact with the models
2. Add post processor module and dynamically load `JavaModelProcessor` implementation class

**Comment by weidongxu-microsoft** [comment]
My 2 cents:
Instead of a customized document object, will it help to use more well-known utils like JavacParser (java11) https://www.javadoc.io/doc/org.kohsuke.sorcerer/sorcerer-javac/latest/com/sun/tools/javac/parser/JavacParser.html, or JavaParser https://github.com/javaparser/javaparser

**Comment by jianghaolu** [comment]
Providing the Java files is probably easier but it will push users back to literal string find and replaces. It probably will work just fine but I'm trying to see if there are options that are more definitive and gives users access to DOMs directly.

The customized document object is actually just modified versions of what we have today. We are not really doing any parsing and I don't think most of our users are familiar with any well-known parsers out there anyways.

We can start with a literal string find-and-replace plugin, since that's easier.

**Comment by weidongxu-microsoft** [comment]
Agree. We could start with an easier file content, see what user will do to it (simply do regex replacement, or more complex as parse - modify - output), and improve on their feedback.

Let's check input from Srikanta @srnagar as well.

**Comment by weidongxu-microsoft** [comment]
Also is there any user proposal to add another plug-able point before preprocessor? If we really need to remove a method, there should be the best place. After java class generated, they need to do it in multiple places as client method, proxy method, etc.

Personally I do not have this kind of remove/add method case. The current case I might use a plugin before preprocessor is due to m4 bug (it mistakenly flattened a type to nothing in parameter).

My case as postprocessor would be due to service bug or core bug. I will need to add a few `@JsonInclude(content = JsonInclude.Include.ALWAYS)` to certain `Map` property since service will respond with error if that property is missing.

**Comment by jianghaolu** [comment]
Customizations support added.
