### ISSUE TITLE
[Query] fconfig cannot be processed while generating the code

### ISSUE THREAD

**Issue by xccc-msft** [Azure/autorest.java#620]
MyConfig: 
- spec: [Azure/sdk-for-java/signalr](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/mgmt/api-specs.json#L294-L302)
- script to cmd: [fconfig](https://github.com/Azure/azure-sdk-for-java/blob/master/eng/mgmt/gulpfile.js#L131-L149) 
- env: nodejs=10.19.0, autorest=2.0.4413, autorest.java=2.1.95

I also tried [fluentTest](https://github.com/Azure/autorest.java/tree/master/fluentTest) on my local and got same failure. The nodejs cannot verify `fconfig`.

My question: 
Is it required to install a specific version of nodejs or the script should be updated?

cc: @juniwang

**Comment by juniwang** [comment]
Very sorry I'm unable to help. I have little knowledge about the `fconfig`. Never run it nor run `autorest` against java.

**Comment by xccc-msft** [comment]
@juniwang I just cc you here to be updated. We will need help from generator side for this.

**Comment by weidongxu-microsoft** [comment]
autorest.java=2.1.95 never changed. So it is not likely the cause of your problem. More likely cause would be nodejs or new autorest v3.

**Comment by xccc-msft** [comment]
fconfig parsing only works with autorest v2 for now.
