### ISSUE TITLE
Support model conversion on simple sync and async methods

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#806]
Storage returns lots of data on headers instead of the body, thus a customized type is created and the headers are converted to the type: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/BlobContainerAsyncClient.java#L457

Work needed:
1) Create a new model class
2) Map an auto generated `Response` class to the new model class

**Comment by alzimmermsft** [comment]
Closing as this has been handled by #1395 and #1396
