### ISSUE TITLE
Customization - custom error handling

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#807]
Support custom error handling on certain status codes. E.g.: https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-java%2Fblob%2Fmaster%2Fsdk%2Fstorage%2Fazure-storage-blob%2Fsrc%2Fmain%2Fjava%2Fcom%2Fazure%2Fstorage%2Fblob%2FBlobContainerAsyncClient.java%23L302&data=04%7C01%7Cjianghlu%40microsoft.com%7Ccbb376f33e2d469fe8f508d880503238%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637400429213610008%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=B2fDZd3yUdsJ1a6wV%2FRxQ74LDsnJJMbHbzY68vvJoFU%3D&reserved=0

May be achievable through directives

**Comment by alzimmermsft** [comment]
Closing as this has been added by https://github.com/Azure/autorest.java/pull/1268
