### ISSUE TITLE
NotNull annotation for required parameters

### ISSUE THREAD

**Issue by RikkiGibson** [Azure/autorest.java#89]
RxJava2 has a `@NotNull` annotation that it applies to parameters to indicate that null must not be passed as a value for the parameter. This causes the IDE to show a warning when null is passed in an inappropriate way. This could be pretty helpful to users of the gen code. We should consider changing the generator to add such annotations when the parameter is marked required in Swagger.

**Comment by daschult** [comment]
I have a working implementation of this. I'm just waiting for https://github.com/Azure/autorest.java/pull/113 to get merged before I submit the pull request.
