### ISSUE TITLE
Support sync streams in requests

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#897]
Right now we generate `Flux<ByteBuffer>` for file uploads in sync methods: https://github.com/Azure/autorest.java/blob/v4/vanilla-tests/src/main/java/fixtures/mediatypes/MediaTypesClient.java#L203

May need stream support in azure-core too.

May be done as part of form data support.

**Comment by weidongxu-microsoft** [comment]
`InputStream` could get some implication with the retry policy ()/
