### ISSUE TITLE
Generate overriding setters for @fluent child classes

### ISSUE THREAD

**Issue by jianghaolu** [Azure/autorest.java#898]
![image](https://user-images.githubusercontent.com/2320445/104790400-e4ef8c00-574b-11eb-9131-640ac34a0cc4.png)

**Comment by weidongxu-microsoft** [comment]
This feature seems be already handled by `--model-override-setter-from-superclass` option.

https://github.com/Azure/autorest.java/issues/748

**Comment by srnagar** [comment]
Thanks @weidongxu-microsoft . Looks like this issue can be resolved using the above option.
