### ISSUE TITLE
EventGrid generated class MediaJobOutputAsset is not final while it should be

### ISSUE THREAD

**Issue by YijunXieMS** [Azure/autorest.java#977]
I manually added final to [MediaJobOutputAsset ](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventgrid/azure-messaging-eventgrid/src/main/java/com/azure/messaging/eventgrid/systemevents/MediaJobOutputAsset.java), which doesn't have subclasses.
It's because this class is a "flattened class". Autorest doesn't add "final" to flattened classes. This might need changing if there is no specific reason to not add "final" to flattened classes.

**Comment by alzimmermsft** [comment]
Closing as fixed as it appears this does generate with `final` now.
